-- [F-031] mod-azerothcore-high-elf: namegen: 7143 inserts, 0 updates, 0 deletes

-- New entries
DELETE FROM `namegen` WHERE `id` = 18600;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18600, 'Acheroth', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18601;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18601, 'Adonys', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18602;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18602, 'Alastor', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18603;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18603, 'Alendel', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18604;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18604, 'Alindian', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18605;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18605, 'Ammath', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18606;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18606, 'Anastalin', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18607;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18607, 'Andor', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18608;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18608, 'Ardeyn', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18609;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18609, 'Astaron', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18610;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18610, 'Basriel', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18611;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18611, 'Bironys', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18612;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18612, 'Borill', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18613;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18613, 'Bulinard', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18614;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18614, 'Capziel', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18615;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18615, 'Celoenus', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18616;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18616, 'Cerunath', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18617;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18617, 'Coridan', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18618;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18618, 'Daenil', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18619;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18619, 'Dakian', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18620;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18620, 'Danash', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18621;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18621, 'Denastrian', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18622;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18622, 'Dorann', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18623;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18623, 'Dorillian', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18624;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18624, 'Ellimast', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18625;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18625, 'Falin', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18626;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18626, 'Fastalor', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18627;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18627, 'Felendren', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18628;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18628, 'Fennidaul', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18629;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18629, 'Gabrial', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18630;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18630, 'Geranis', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18631;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18631, 'Geron', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18632;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18632, 'Gordring', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18633;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18633, 'Gullivan', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18634;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18634, 'Hacinth', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18635;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18635, 'Halis', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18636;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18636, 'Hathvelion', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18637;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18637, 'Hynalan', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18638;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18638, 'Iavis', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18639;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18639, 'Indorian', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18640;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18640, 'Istolus', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18641;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18641, 'Ithanas', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18642;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18642, 'Jesthenis', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18643;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18643, 'Jonovath', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18644;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18644, 'Kaladrin', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18645;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18645, 'Kuularin', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18646;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18646, 'Kelivard', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18647;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18647, 'Knastus', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18648;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18648, 'Kordril', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18649;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18649, 'Lammash', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18650;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18650, 'Landalor', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18651;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18651, 'Landorian', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18652;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18652, 'Lanthan', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18653;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18653, 'Lazuriel', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18654;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18654, 'Lennivan', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18655;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18655, 'Lorastian', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18656;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18656, 'Lothos', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18657;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18657, 'Luminorian', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18658;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18658, 'Mandarian', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18659;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18659, 'Martik', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18660;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18660, 'Mastinicus', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18661;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18661, 'Mathreyn', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18662;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18662, 'Myrokos', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18663;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18663, 'Narinicus', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18664;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18664, 'Nelluth', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18665;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18665, 'Nerendil', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18666;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18666, 'Nirael', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18667;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18667, 'Ophion', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18668;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18668, 'Orastian', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18669;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18669, 'Orthin', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18670;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18670, 'Perimath', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18671;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18671, 'Kiril', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18672;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18672, 'Rallin', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18673;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18673, 'Rameth', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18674;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18674, 'Regethon', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18675;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18675, 'Relivanth', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18676;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18676, 'Rindorell', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18677;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18677, 'Ruibar', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18678;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18678, 'Salindorian', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18679;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18679, 'Salovanth', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18680;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18680, 'Sarcyon', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18681;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18681, 'Sathein', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18682;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18682, 'Sathranis', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18683;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18683, 'Sennistan', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18684;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18684, 'Shalibar', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18685;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18685, 'Solastus', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18686;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18686, 'Symmael', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18687;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18687, 'Tarrath', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18688;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18688, 'Taumas', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18689;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18689, 'Telenus', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18690;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18690, 'Tennish', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18691;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18691, 'Thaelas', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18692;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18692, 'Theirean', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18693;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18693, 'Thorian', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18694;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18694, 'Ticonash', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18695;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18695, 'Vasyleios', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18696;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18696, 'Vedoran', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18697;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18697, 'Velendris', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18698;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18698, 'Westinar', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18699;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18699, 'Xanthus', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18700;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18700, 'Aendis', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18701;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18701, 'Aendron', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18702;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18702, 'Aenesh', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18703;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18703, 'Aeniel', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18704;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18704, 'Aenin', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18705;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18705, 'Aenlan', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18706;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18706, 'Aenleron', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18707;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18707, 'Aenllan', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18708;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18708, 'Aenlor', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18709;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18709, 'Aenstus', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18710;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18710, 'Amordis', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18711;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18711, 'Amordron', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18712;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18712, 'Amoresh', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18713;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18713, 'Amoriel', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18714;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18714, 'Amorin', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18715;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18715, 'Amorlan', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18716;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18716, 'Amorleron', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18717;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18717, 'Amorllan', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18718;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18718, 'Amorlor', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18719;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18719, 'Amorstus', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18720;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18720, 'Keedis', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18721;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18721, 'Keeiel', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18722;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18722, 'Keein', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18723;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18723, 'Keelan', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18724;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18724, 'Keelor', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18725;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18725, 'Keleron', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18726;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18726, 'Kellan', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18727;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18727, 'Keyadis', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18728;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18728, 'Keyadron', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18729;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18729, 'Keyaesh', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18730;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18730, 'Keyaiel', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18731;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18731, 'Keyain', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18732;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18732, 'Keyalan', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18733;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18733, 'Keyaleron', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18734;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18734, 'Keyallan', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18735;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18735, 'Keyalor', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18736;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18736, 'Keyastus', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18737;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18737, 'Kiedron', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18738;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18738, 'Kiestus', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18739;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18739, 'Kredis', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18740;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18740, 'Kredron', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18741;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18741, 'Kreiel', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18742;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18742, 'Krein', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18743;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18743, 'Krelan', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18744;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18744, 'Kreleron', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18745;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18745, 'Krellan', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18746;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18746, 'Krelor', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18747;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18747, 'Krestus', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18748;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18748, 'Kriesh', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18749;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18749, 'Myrodis', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18750;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18750, 'Myrodron', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18751;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18751, 'Myroesh', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18752;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18752, 'Myroiel', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18753;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18753, 'Myroin', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18754;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18754, 'Myrolan', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18755;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18755, 'Myroleron', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18756;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18756, 'Myrollan', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18757;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18757, 'Myrolor', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18758;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18758, 'Myrostus', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18759;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18759, 'Sandis', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18760;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18760, 'Sandron', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18761;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18761, 'Sanesh', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18762;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18762, 'Saniel', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18763;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18763, 'Sanin', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18764;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18764, 'Sanlan', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18765;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18765, 'Sanleron', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18766;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18766, 'Sanllan', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18767;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18767, 'Sanlor', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18768;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18768, 'Sanstus', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18769;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18769, 'Tydis', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18770;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18770, 'Tydron', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18771;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18771, 'Tyesh', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18772;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18772, 'Tyiel', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18773;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18773, 'Tyin', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18774;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18774, 'Tylan', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18775;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18775, 'Tyleron', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18776;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18776, 'Tyllan', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18777;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18777, 'Tylor', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18778;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18778, 'Tystus', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18779;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18779, 'Vyndis', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18780;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18780, 'Vyndron', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18781;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18781, 'Vynesh', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18782;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18782, 'Vyniel', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18783;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18783, 'Vynin', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18784;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18784, 'Vynlan', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18785;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18785, 'Vynleron', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18786;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18786, 'Vynllan', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18787;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18787, 'Vynlor', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18788;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18788, 'Vynstus', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18789;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18789, 'Weledis', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18790;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18790, 'Weledron', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18791;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18791, 'Weleiel', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18792;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18792, 'Welein', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18793;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18793, 'Welelan', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18794;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18794, 'Welelor', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18795;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18795, 'Welish', 13, 0);
DELETE FROM `namegen` WHERE `id` = 18796;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18796, 'Acantha', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18797;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18797, 'Aelyste', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18798;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18798, 'Aerin', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18799;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18799, 'Alectria', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18800;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18800, 'Aleinia', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18801;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18801, 'Alinderial', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18802;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18802, 'Anadarindia', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18803;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18803, 'Areyn', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18804;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18804, 'Astella', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18805;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18805, 'Avalina', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18806;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18806, 'Belamun', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18807;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18807, 'Belleria', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18808;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18808, 'Braelyn', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18809;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18809, 'Brisalyna', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18810;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18810, 'Cala', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18811;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18811, 'Callysta', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18812;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18812, 'Celina', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18813;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18813, 'Celosia', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18814;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18814, 'Charisse', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18815;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18815, 'Cyndala', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18816;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18816, 'Daestra', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18817;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18817, 'Delindis', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18818;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18818, 'Desdemina', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18819;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18819, 'Dorala', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18820;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18820, 'Dyonissa', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18821;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18821, 'Elianne', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18822;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18822, 'Elisara', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18823;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18823, 'Evelyne', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18824;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18824, 'Faelina', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18825;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18825, 'Faeraline', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18826;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18826, 'Felinis', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18827;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18827, 'Garridel', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18828;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18828, 'Gelindril', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18829;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18829, 'Genistina', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18830;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18830, 'Hycintha', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18831;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18831, 'Ilektra', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18832;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18832, 'Ionae', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18833;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18833, 'Irissa', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18834;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18834, 'Janeda', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18835;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18835, 'Jasmintha', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18836;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18836, 'Kaelynitha', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18837;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18837, 'Kanaria', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18838;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18838, 'Kelisendra', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18839;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18839, 'Larianna', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18840;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18840, 'Larissa', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18841;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18841, 'Lilatha', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18842;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18842, 'Lilithelys', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18843;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18843, 'Lindrys', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18844;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18844, 'Lionna', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18845;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18845, 'Liralei', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18846;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18846, 'Lithilia', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18847;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18847, 'Luminil', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18848;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18848, 'Medea', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18849;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18849, 'Melanthe', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18850;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18850, 'Mellindra', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18851;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18851, 'Meniara', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18852;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18852, 'Morgana', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18853;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18853, 'Nadina', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18854;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18854, 'Narcisse', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18855;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18855, 'Narina', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18856;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18856, 'Nesseline', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18857;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18857, 'Nymue', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18858;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18858, 'Nyssa', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18859;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18859, 'Oleanda', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18860;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18860, 'Ophira', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18861;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18861, 'Oriana', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18862;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18862, 'Pyranda', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18863;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18863, 'Pyrena', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18864;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18864, 'Keirra', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18865;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18865, 'Quelastia', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18866;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18866, 'Raelaria', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18867;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18867, 'Raelis', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18868;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18868, 'Rashelle', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18869;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18869, 'Reanna', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18870;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18870, 'Reladriel', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18871;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18871, 'Rinna', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18872;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18872, 'Sanossa', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18873;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18873, 'Sareyn', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18874;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18874, 'Sathiel', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18875;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18875, 'Savalyne', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18876;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18876, 'Sedina', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18877;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18877, 'Selestia', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18878;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18878, 'Selinasta', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18879;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18879, 'Selindia', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18880;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18880, 'Sharra', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18881;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18881, 'Shatharia', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18882;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18882, 'Sinaris', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18883;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18883, 'Solanna', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18884;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18884, 'Sunamun', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18885;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18885, 'Syrenni', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18886;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18886, 'Taina', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18887;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18887, 'Tannaria', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18888;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18888, 'Tannis', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18889;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18889, 'Teestina', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18890;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18890, 'Tyria', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18891;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18891, 'Thela', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18892;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18892, 'Thelindaria', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18893;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18893, 'Tirilliae', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18894;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18894, 'Tirivana', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18895;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18895, 'Vania', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18896;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18896, 'Vara', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18897;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18897, 'Varallia', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18898;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18898, 'Velaena', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18899;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18899, 'Velirra', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18900;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18900, 'Vynna', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18901;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18901, 'Wylethia', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18902;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18902, 'Xanthia', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18903;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18903, 'Zaliene', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18904;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18904, 'Braeda', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18905;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18905, 'Braedori', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18906;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18906, 'Braedra', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18907;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18907, 'Braedrel', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18908;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18908, 'Braeice', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18909;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18909, 'Braeline', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18910;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18910, 'Braendra', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18911;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18911, 'Braesong', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18912;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18912, 'Braevia', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18913;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18913, 'Deydori', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18914;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18914, 'Deydra', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18915;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18915, 'Deydrel', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18916;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18916, 'Deyeda', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18917;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18917, 'Deyice', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18918;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18918, 'Deyline', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18919;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18919, 'Deyndra', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18920;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18920, 'Deysong', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18921;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18921, 'Deyvia', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18922;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18922, 'Erodori', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18923;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18923, 'Erodra', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18924;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18924, 'Erodrel', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18925;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18925, 'Eroeda', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18926;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18926, 'Eroice', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18927;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18927, 'Eroline', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18928;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18928, 'Erondra', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18929;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18929, 'Erosong', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18930;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18930, 'Erovia', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18931;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18931, 'Galdori', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18932;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18932, 'Galdra', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18933;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18933, 'Galdrel', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18934;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18934, 'Galeda', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18935;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18935, 'Galice', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18936;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18936, 'Galline', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18937;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18937, 'Galndra', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18938;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18938, 'Galsong', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18939;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18939, 'Galvia', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18940;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18940, 'Lithdori', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18941;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18941, 'Lithdra', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18942;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18942, 'Lithdrel', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18943;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18943, 'Litheda', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18944;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18944, 'Lithice', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18945;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18945, 'Lithline', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18946;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18946, 'Lithndra', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18947;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18947, 'Lithsong', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18948;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18948, 'Lithvia', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18949;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18949, 'Noradori', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18950;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18950, 'Noradra', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18951;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18951, 'Noradrel', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18952;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18952, 'Noraeda', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18953;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18953, 'Noraice', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18954;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18954, 'Noraline', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18955;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18955, 'Norandra', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18956;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18956, 'Norasong', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18957;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18957, 'Noravia', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18958;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18958, 'Tanddori', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18959;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18959, 'Tanddra', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18960;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18960, 'Tanddrel', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18961;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18961, 'Tandeda', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18962;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18962, 'Tandice', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18963;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18963, 'Tandline', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18964;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18964, 'Tandndra', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18965;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18965, 'Tandsong', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18966;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18966, 'Tandvia', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18967;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18967, 'Traydori', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18968;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18968, 'Traydra', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18969;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18969, 'Traydrel', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18970;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18970, 'Trayeda', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18971;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18971, 'Trayice', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18972;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18972, 'Trayline', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18973;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18973, 'Trayndra', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18974;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18974, 'Traysong', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18975;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18975, 'Trayvia', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18976;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18976, 'Velidori', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18977;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18977, 'Velidra', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18978;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18978, 'Velidrel', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18979;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18979, 'Velieda', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18980;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18980, 'Veliice', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18981;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18981, 'Veliline', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18982;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18982, 'Velindra', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18983;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18983, 'Velisong', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18984;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18984, 'Velivia', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18985;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18985, 'Zaradori', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18986;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18986, 'Zaradra', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18987;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18987, 'Zaradrel', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18988;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18988, 'Zaraeda', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18989;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18989, 'Zaraice', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18990;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18990, 'Zaraline', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18991;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18991, 'Zarandra', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18992;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18992, 'Zarasong', 13, 1);
DELETE FROM `namegen` WHERE `id` = 18993;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18993, 'Zaravia', 13, 1);
