-- [F-031] mod-azerothcore-high-elf: skilllineability: 35 inserts, 61 updates, 0 deletes

-- New entries
DELETE FROM `skilllineability` WHERE `id` = 31463;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31463, 791, 110005, 4096, 1503, 0, 0, 1, 0, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31464;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31464, 791, 110006, 4096, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31465;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31465, 791, 110007, 4096, 32, 0, 0, 1, 0, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31466;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31466, 791, 110008, 4096, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31467;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31467, 791, 110009, 4096, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0);

-- Changed values
UPDATE `skilllineability` SET `required_races` = `required_races` | 4096 WHERE `id` = 590;
UPDATE `skilllineability` SET `required_races` = `required_races` | 4096 WHERE `id` = 592;
UPDATE `skilllineability` SET `required_races` = `required_races` | 4096 WHERE `id` = 727;
UPDATE `skilllineability` SET `required_races` = `required_races` | 4096 WHERE `id` = 3269;
UPDATE `skilllineability` SET `required_races` = `required_races` | 4096 WHERE `id` = 3270;
UPDATE `skilllineability` SET `required_races` = `required_races` | 4096 WHERE `id` = 3271;
UPDATE `skilllineability` SET `required_races` = `required_races` | 4096 WHERE `id` = 3272;
UPDATE `skilllineability` SET `required_races` = `required_races` | 4096 WHERE `id` = 3273;
UPDATE `skilllineability` SET `required_races` = `required_races` | 4096 WHERE `id` = 3274;
UPDATE `skilllineability` SET `required_races` = `required_races` | 4096 WHERE `id` = 5989;
UPDATE `skilllineability` SET `required_races` = `required_races` | 4096 WHERE `id` = 5990;
UPDATE `skilllineability` SET `required_races` = `required_races` | 4096 WHERE `id` = 5991;
UPDATE `skilllineability` SET `required_races` = `required_races` | 4096 WHERE `id` = 5992;
UPDATE `skilllineability` SET `required_races` = `required_races` | 4096 WHERE `id` = 5993;
UPDATE `skilllineability` SET `required_races` = `required_races` | 4096 WHERE `id` = 5994;
UPDATE `skilllineability` SET `required_races` = `required_races` | 4096 WHERE `id` = 7594;
UPDATE `skilllineability` SET `required_races` = `required_races` | 4096 WHERE `id` = 12518;
UPDATE `skilllineability` SET `required_races` = `required_races` | 4096 WHERE `id` = 13151;
UPDATE `skilllineability` SET `required_races` = `required_races` | 4096 WHERE `id` = 14013;
UPDATE `skilllineability` SET `required_races` = `required_races` | 4096 WHERE `id` = 14022;
UPDATE `skilllineability` SET `required_races` = `required_races` | 4096 WHERE `id` = 14023;
UPDATE `skilllineability` SET `required_races` = `required_races` | 4096 WHERE `id` = 14779;
UPDATE `skilllineability` SET `required_races` = `required_races` | 4096 WHERE `id` = 14784;
UPDATE `skilllineability` SET `required_races` = `required_races` | 4096 WHERE `id` = 14787;
UPDATE `skilllineability` SET `required_races` = `required_races` | 4096 WHERE `id` = 14788;
UPDATE `skilllineability` SET `required_races` = `required_races` | 4096 WHERE `id` = 14795;
UPDATE `skilllineability` SET `required_races` = `required_races` | 4096 WHERE `id` = 14815;
UPDATE `skilllineability` SET `required_races` = `required_races` | 4096 WHERE `id` = 14816;
UPDATE `skilllineability` SET `required_races` = `required_races` | 4096 WHERE `id` = 14817;
UPDATE `skilllineability` SET `required_races` = `required_races` | 4096 WHERE `id` = 14818;
UPDATE `skilllineability` SET `required_races` = `required_races` | 4096 WHERE `id` = 15034;
UPDATE `skilllineability` SET `required_races` = `required_races` | 4096 WHERE `id` = 15035;
UPDATE `skilllineability` SET `required_races` = `required_races` | 4096 WHERE `id` = 15040;
UPDATE `skilllineability` SET `required_races` = `required_races` | 4096 WHERE `id` = 15041;
UPDATE `skilllineability` SET `required_races` = `required_races` | 4096 WHERE `id` = 15252;
UPDATE `skilllineability` SET `required_races` = `required_races` | 4096 WHERE `id` = 15253;
UPDATE `skilllineability` SET `required_races` = `required_races` | 4096 WHERE `id` = 15606;
UPDATE `skilllineability` SET `required_races` = `required_races` | 4096 WHERE `id` = 15607;
UPDATE `skilllineability` SET `required_races` = `required_races` | 4096 WHERE `id` = 16999;
UPDATE `skilllineability` SET `required_races` = `required_races` | 4096 WHERE `id` = 17000;
UPDATE `skilllineability` SET `required_races` = `required_races` | 4096 WHERE `id` = 17003;
UPDATE `skilllineability` SET `required_races` = `required_races` | 4096 WHERE `id` = 17004;
UPDATE `skilllineability` SET `required_races` = `required_races` | 4096 WHERE `id` = 17510;
UPDATE `skilllineability` SET `required_races` = `required_races` | 4096 WHERE `id` = 18299;
UPDATE `skilllineability` SET `required_races` = `required_races` | 4096 WHERE `id` = 18308;
UPDATE `skilllineability` SET `required_races` = `required_races` | 4096 WHERE `id` = 18311;
UPDATE `skilllineability` SET `required_races` = `required_races` | 4096 WHERE `id` = 18314;
UPDATE `skilllineability` SET `required_races` = `required_races` | 4096 WHERE `id` = 20089;
UPDATE `skilllineability` SET `required_races` = `required_races` | 4096 WHERE `id` = 20090;
UPDATE `skilllineability` SET `required_races` = `required_races` | 4096 WHERE `id` = 20091;
UPDATE `skilllineability` SET `required_races` = `required_races` | 4096 WHERE `id` = 20092;
UPDATE `skilllineability` SET `required_races` = `required_races` | 4096 WHERE `id` = 20110;
UPDATE `skilllineability` SET `required_races` = `required_races` | 4096 WHERE `id` = 20171;
UPDATE `skilllineability` SET `required_races` = `required_races` | 4096 WHERE `id` = 20283;
UPDATE `skilllineability` SET `required_races` = `required_races` | 4096 WHERE `id` = 20289;
UPDATE `skilllineability` SET `required_races` = `required_races` | 4096 WHERE `id` = 20290;
UPDATE `skilllineability` SET `required_races` = `required_races` | 4096 WHERE `id` = 20665;
UPDATE `skilllineability` SET `required_races` = `required_races` | 4096 WHERE `id` = 20867;
UPDATE `skilllineability` SET `required_races` = `required_races` | 4096 WHERE `id` = 20868;
UPDATE `skilllineability` SET `required_races` = `required_races` | 4096 WHERE `id` = 21723;
UPDATE `skilllineability` SET `required_races` = `required_races` | 4096 WHERE `id` = 21724;
