-- [F-031] mod-azerothcore-high-elf: charhairgeosets: 123 inserts, 6 updates, 0 deletes

-- New entries
DELETE FROM `charhairgeosets` WHERE `id` = 570;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (570, 13, 0, 0, 2, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 571;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (571, 13, 1, 1, 3, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 572;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (572, 13, 1, 2, 4, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 573;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (573, 13, 0, 2, 4, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 574;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (574, 13, 0, 1, 3, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 575;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (575, 13, 0, 3, 5, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 576;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (576, 13, 0, 4, 6, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 577;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (577, 13, 0, 5, 7, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 578;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (578, 13, 0, 6, 8, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 579;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (579, 13, 0, 7, 9, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 580;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (580, 13, 0, 8, 10, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 581;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (581, 13, 0, 9, 11, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 582;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (582, 13, 0, 10, 12, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 583;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (583, 13, 1, 3, 5, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 584;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (584, 13, 1, 4, 6, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 585;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (585, 13, 1, 5, 7, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 586;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (586, 13, 1, 6, 8, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 587;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (587, 13, 1, 7, 9, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 588;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (588, 13, 1, 8, 10, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 589;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (589, 13, 1, 9, 11, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 590;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (590, 13, 1, 10, 12, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 591;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (591, 13, 1, 11, 13, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 592;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (592, 13, 1, 12, 14, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 593;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (593, 13, 1, 13, 15, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 594;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (594, 13, 1, 14, 16, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 595;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (595, 13, 1, 0, 2, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 596;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (596, 13, 1, 15, 17, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 597;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (597, 13, 1, 16, 18, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 598;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (598, 13, 1, 17, 19, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 599;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (599, 13, 1, 18, 20, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 600;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (600, 13, 1, 19, 21, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 601;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (601, 13, 0, 11, 13, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 602;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (602, 13, 0, 12, 14, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 603;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (603, 13, 0, 13, 15, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 604;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (604, 13, 0, 14, 16, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 605;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (605, 13, 0, 15, 17, 0);
