-- [F-031] mod-azerothcore-high-elf: characterfacialhairstyles: 19 inserts, 43 updates, 0 deletes

-- New entries
DELETE FROM `characterfacialhairstyles` WHERE `race` = 13 AND `gender` = 0 AND `variation_id` = 1;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (13, 0, 1, 2, 0, 0, 0, 2);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 13 AND `gender` = 0 AND `variation_id` = 2;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (13, 0, 2, 3, 0, 0, 0, 2);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 13 AND `gender` = 0 AND `variation_id` = 3;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (13, 0, 3, 4, 0, 0, 0, 2);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 13 AND `gender` = 0 AND `variation_id` = 4;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (13, 0, 4, 5, 0, 0, 0, 2);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 13 AND `gender` = 0 AND `variation_id` = 5;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (13, 0, 5, 6, 0, 0, 0, 2);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 13 AND `gender` = 0 AND `variation_id` = 6;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (13, 0, 6, 7, 0, 0, 0, 2);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 13 AND `gender` = 0 AND `variation_id` = 7;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (13, 0, 7, 8, 0, 0, 0, 2);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 13 AND `gender` = 0 AND `variation_id` = 8;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (13, 0, 8, 9, 0, 0, 0, 2);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 13 AND `gender` = 0 AND `variation_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (13, 0, 9, 10, 0, 0, 0, 2);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 13 AND `gender` = 1 AND `variation_id` = 1;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (13, 1, 1, 0, 2, 0, 0, 2);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 13 AND `gender` = 1 AND `variation_id` = 2;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (13, 1, 2, 0, 3, 0, 0, 2);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 13 AND `gender` = 1 AND `variation_id` = 3;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (13, 1, 3, 0, 4, 0, 0, 2);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 13 AND `gender` = 1 AND `variation_id` = 4;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (13, 1, 4, 0, 5, 0, 0, 2);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 13 AND `gender` = 1 AND `variation_id` = 5;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (13, 1, 5, 0, 6, 0, 0, 2);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 13 AND `gender` = 1 AND `variation_id` = 6;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (13, 1, 6, 0, 7, 0, 0, 2);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 13 AND `gender` = 1 AND `variation_id` = 7;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (13, 1, 7, 0, 8, 0, 0, 2);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 13 AND `gender` = 1 AND `variation_id` = 8;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (13, 1, 8, 0, 9, 0, 0, 2);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 13 AND `gender` = 1 AND `variation_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (13, 1, 9, 0, 10, 0, 0, 2);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 13 AND `gender` = 1 AND `variation_id` = 10;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (13, 1, 10, 0, 11, 0, 0, 2);
