// Generated by tools/earthen_race_pack.py from the pinned Earthen discovery.
#ifndef ESTERIA_EARTHEN_APPEARANCE_H
#define ESTERIA_EARTHEN_APPEARANCE_H

#include <array>
#include <cstdint>

namespace EarthenAppearance
{
    struct Option
    {
        std::uint16_t field;
        std::uint16_t count;
        std::uint16_t factor;
    };

    struct Requirement
    {
        std::uint16_t option;
        std::uint16_t value;
        std::uint16_t required;
        std::uint32_t mask;
    };

    inline constexpr std::array<Option, 16> MaleOptions = {{
        {0, 14, 1}, // Skin Color
        {1, 10, 1}, // Face
        {2, 11, 1}, // Hair Style
        {3, 14, 1}, // Hair Color
        {4, 11, 1}, // Beard Style
        {0, 14, 14}, // Gem Color
        {3, 14, 14}, // Eye Color
        {1, 4, 10}, // Eyesight
        {1, 2, 40}, // Eyebrows
        {5, 2, 25}, // Belt
        {2, 5, 11}, // Right Shoulder
        {4, 5, 11}, // Left Shoulder
        {2, 3, 55}, // Torso
        {5, 5, 1}, // Arms
        {4, 3, 55}, // Legs
        {5, 5, 5}, // Hands
    }};

    inline constexpr std::array<char const*, 16> MaleLabels = {
        "Skin Color",
        "Face",
        "Hair Style",
        "Hair Color",
        "Beard Style",
        "Gem Color",
        "Eye Color",
        "Eyesight",
        "Eyebrows",
        "Belt",
        "Right Shoulder",
        "Left Shoulder",
        "Torso",
        "Arms",
        "Legs",
        "Hands",
    };

    inline constexpr std::array<std::uint16_t, 6> MaleCapacities = {196, 80, 165, 196, 165, 50};

    inline constexpr std::array<Requirement, 0> MaleRequirements = {{
    }};

    inline constexpr std::array<Option, 16> FemaleOptions = {{
        {0, 14, 1}, // Skin Color
        {1, 10, 1}, // Face
        {2, 11, 1}, // Hair Style
        {3, 14, 1}, // Hair Color
        {4, 11, 1}, // Beard Style
        {0, 14, 14}, // Gem Color
        {3, 14, 14}, // Eye Color
        {1, 4, 10}, // Eyesight
        {1, 2, 40}, // Eyebrows
        {5, 2, 16}, // Belt
        {2, 5, 11}, // Right Shoulder
        {4, 5, 11}, // Left Shoulder
        {2, 3, 55}, // Torso
        {5, 4, 1}, // Arms
        {4, 3, 55}, // Legs
        {5, 4, 4}, // Hands
    }};

    inline constexpr std::array<char const*, 16> FemaleLabels = {
        "Skin Color",
        "Face",
        "Hair Style",
        "Hair Color",
        "Beard Style",
        "Gem Color",
        "Eye Color",
        "Eyesight",
        "Eyebrows",
        "Belt",
        "Right Shoulder",
        "Left Shoulder",
        "Torso",
        "Arms",
        "Legs",
        "Hands",
    };

    inline constexpr std::array<std::uint16_t, 6> FemaleCapacities = {196, 80, 165, 196, 165, 32};

    inline constexpr std::array<Requirement, 0> FemaleRequirements = {{
    }};

    template<class Options, class Requirements>
    constexpr bool ValidateProfile(std::array<std::uint8_t, 6> const& fields, Options const& options,
        Requirements const& requirements, std::array<std::uint16_t, 6> const& capacities)
    {
        for (unsigned i = 0; i < fields.size(); ++i)
            if (fields[i] >= capacities[i])
                return false;
        auto choice = [&](unsigned index)
        {
            Option const& option = options[index];
            return (fields[option.field] / option.factor) % option.count;
        };
        for (Requirement const& requirement : requirements)
            if (choice(requirement.option) == requirement.value
                && !(requirement.mask & (1u << choice(requirement.required))))
                return false;
        return true;
    }

    constexpr bool Validate(unsigned gender, std::array<std::uint8_t, 6> const& fields)
    {
        if (gender == 0)
            return ValidateProfile(fields, MaleOptions, MaleRequirements, MaleCapacities);
        if (gender == 1)
            return ValidateProfile(fields, FemaleOptions, FemaleRequirements, FemaleCapacities);
        return false;
    }
}

#endif
