// Generated by tools/haranir_race_pack.py from the pinned Haranir discovery.
#ifndef ESTERIA_HARANIR_APPEARANCE_H
#define ESTERIA_HARANIR_APPEARANCE_H

#include <array>
#include <cstdint>

namespace HaranirAppearance
{
    struct Option
    {
        std::uint16_t field;
        std::uint16_t count;
        std::uint16_t factor;
    };

    struct Requirement
    {
        std::uint16_t option;
        std::uint16_t value;
        std::uint16_t required;
        std::uint32_t mask;
    };

    inline constexpr std::array<Option, 29> MaleOptions = {{
        {2, 18, 1}, // Hair Style
        {2, 14, 18}, // Eyebrows
        {7, 4, 54}, // Tusk
        {5, 13, 18}, // Shoulder Spine
        {0, 20, 1}, // Skin Color
        {1, 8, 1}, // Face
        {3, 30, 1}, // Hair Color
        {8, 5, 1}, // Face Fur Pattern
        {4, 18, 8}, // Fur Color
        {5, 18, 1}, // Shoulder Spine Color
        {1, 23, 8}, // Hair Highlight Color
        {6, 10, 18}, // Ears
        {0, 12, 20}, // Eye Color
        {8, 2, 125}, // Nose
        {8, 5, 5}, // Earrings
        {10, 4, 5}, // Eyesight
        {9, 2, 125}, // Feet
        {8, 5, 25}, // Loincloth Color
        {9, 5, 1}, // Jewelry Color
        {10, 2, 80}, // Hair Spine Style
        {6, 18, 1}, // Hair Spine Color
        {4, 8, 1}, // Beard
        {9, 5, 5}, // Necklace
        {7, 9, 1}, // Sideburns
        {3, 6, 30}, // Moustache
        {9, 5, 25}, // Body Fur Pattern
        {7, 6, 9}, // Face Paint
        {10, 4, 20}, // Body Paint
        {10, 5, 1}, // Paint Color
    }};

    inline constexpr std::array<char const*, 29> MaleLabels = {
        "Hair Style",
        "Eyebrows",
        "Tusk",
        "Shoulder Spine",
        "Skin Color",
        "Face",
        "Hair Color",
        "Face Fur Pattern",
        "Fur Color",
        "Shoulder Spine Color",
        "Hair Highlight Color",
        "Ears",
        "Eye Color",
        "Nose",
        "Earrings",
        "Eyesight",
        "Feet",
        "Loincloth Color",
        "Jewelry Color",
        "Hair Spine Style",
        "Hair Spine Color",
        "Beard",
        "Necklace",
        "Sideburns",
        "Moustache",
        "Body Fur Pattern",
        "Face Paint",
        "Body Paint",
        "Paint Color",
    };

    inline constexpr std::array<std::uint16_t, 13> MaleCapacities =
        {240, 184, 252, 180, 144, 234, 180, 216, 250, 250, 160, 1, 1};

    inline constexpr std::array<Requirement, 0> MaleRequirements = {{
    }};

    inline constexpr std::array<Option, 28> FemaleOptions = {{
        {2, 18, 1}, // Hair Style
        {5, 10, 18}, // Ears
        {8, 2, 125}, // Nose
        {4, 14, 1}, // Eyebrows
        {9, 4, 5}, // Tusk
        {2, 13, 18}, // Shoulder Spine
        {7, 5, 6}, // Body Fur Pattern
        {3, 6, 30}, // Face Fur Pattern
        {0, 12, 20}, // Eye Color
        {1, 9, 1}, // Face
        {3, 30, 1}, // Hair Color
        {0, 20, 1}, // Skin Color
        {1, 23, 9}, // Hair Highlight Color
        {7, 5, 30}, // Jewelry
        {4, 18, 14}, // Shoulder Spine Color
        {9, 4, 20}, // Eyesight
        {9, 2, 80}, // Feet
        {10, 2, 4}, // Hair Spine Style
        {5, 18, 1}, // Hair Spine Color
        {6, 9, 18}, // Eyelashes
        {6, 18, 1}, // Fur Color
        {10, 2, 8}, // Underclothes Top
        {8, 5, 1}, // Underclothes Color
        {8, 5, 5}, // Necklace
        {8, 5, 25}, // Earrings
        {7, 6, 1}, // Face Paint
        {10, 4, 1}, // Body Paint
        {9, 5, 1}, // Paint Color
    }};

    inline constexpr std::array<char const*, 28> FemaleLabels = {
        "Hair Style",
        "Ears",
        "Nose",
        "Eyebrows",
        "Tusk",
        "Shoulder Spine",
        "Body Fur Pattern",
        "Face Fur Pattern",
        "Eye Color",
        "Face",
        "Hair Color",
        "Skin Color",
        "Hair Highlight Color",
        "Jewelry",
        "Shoulder Spine Color",
        "Eyesight",
        "Feet",
        "Hair Spine Style",
        "Hair Spine Color",
        "Eyelashes",
        "Fur Color",
        "Underclothes Top",
        "Underclothes Color",
        "Necklace",
        "Earrings",
        "Face Paint",
        "Body Paint",
        "Paint Color",
    };

    inline constexpr std::array<std::uint16_t, 13> FemaleCapacities =
        {240, 207, 234, 180, 252, 180, 162, 150, 250, 160, 16, 1, 1};

    inline constexpr std::array<Requirement, 0> FemaleRequirements = {{
    }};

    constexpr std::array<std::uint8_t, 13> Fields(std::uint8_t skin, std::uint8_t face,
        std::uint8_t hairStyle, std::uint8_t hairColor, std::uint8_t facialStyle, std::uint64_t extra)
    {
        std::array<std::uint8_t, 13> fields = {skin, face, hairStyle, hairColor, facialStyle};
        for (unsigned i = 0; i < 8; ++i)
            fields[5 + i] = static_cast<std::uint8_t>(extra >> (i * 8));
        return fields;
    }

    constexpr std::uint64_t Extra(std::array<std::uint8_t, 13> const& fields)
    {
        std::uint64_t extra = 0;
        for (unsigned i = 0; i < 8; ++i)
            extra |= std::uint64_t{fields[5 + i]} << (i * 8);
        return extra;
    }

    template<class Options, class Requirements>
    constexpr bool ValidateProfile(std::array<std::uint8_t, 13> const& fields, Options const& options,
        Requirements const& requirements, std::array<std::uint16_t, 13> const& capacities)
    {
        for (unsigned i = 0; i < fields.size(); ++i)
            if (fields[i] >= capacities[i])
                return false;
        auto choice = [&](unsigned index)
        {
            Option const& option = options[index];
            return (fields[option.field] / option.factor) % option.count;
        };
        for (Requirement const& requirement : requirements)
            if (choice(requirement.option) == requirement.value
                && !(requirement.mask & (1u << choice(requirement.required))))
                return false;
        return true;
    }

    constexpr bool Validate(unsigned gender, std::array<std::uint8_t, 13> const& fields)
    {
        if (gender == 0)
            return ValidateProfile(fields, MaleOptions, MaleRequirements, MaleCapacities);
        if (gender == 1)
            return ValidateProfile(fields, FemaleOptions, FemaleRequirements, FemaleCapacities);
        return false;
    }
}

#endif
