INSERT IGNORE INTO `playercreateinfo_spell_custom` VALUES
-- Sethrak Warrior
(@SethrakMask, @Warrior, '78', 'Heroic Strike'),
(@SethrakMask, @Warrior, '81', 'Dodge'),
(@SethrakMask, @Warrior, '107', 'Block'),
(@SethrakMask, @Warrior, '196', 'One-Handed Axes'),
(@SethrakMask, @Warrior, '197', 'Two-Handed Axes'),
(@SethrakMask, @Warrior, '201', 'One-Handed Swords'),
(@SethrakMask, @Warrior, '203', 'Unarmed'),
(@SethrakMask, @Warrior, '204', 'Defense'),
(@SethrakMask, @Warrior, '522', 'SPELLDEFENSE(DND)'),
(@SethrakMask, @Warrior, '669', 'Language Orcish'),
(@SethrakMask, @Warrior, '2382', 'Generic'),
(@SethrakMask, @Warrior, '2457', 'Battle Stance'),
(@SethrakMask, @Warrior, '2479', 'Honorless Target'),
(@SethrakMask, @Warrior, '3050', 'Detect'),
(@SethrakMask, @Warrior, '3365', 'Opening'),
(@SethrakMask, @Warrior, '5301', 'Defensive State(DND)'),
(@SethrakMask, @Warrior, '6233', 'Closing'),
(@SethrakMask, @Warrior, '6246', 'Closing'),
(@SethrakMask, @Warrior, '6247', 'Opening'),
(@SethrakMask, @Warrior, '6477', 'Opening'),
(@SethrakMask, @Warrior, '6478', 'Opening'),
(@SethrakMask, @Warrior, '6603', 'Attack'),
(@SethrakMask, @Warrior, '7266', 'Duel'),
(@SethrakMask, @Warrior, '7267', 'Grovel'),
(@SethrakMask, @Warrior, '7355', 'Stuck'),
(@SethrakMask, @Warrior, '7376', 'Defensive Stance Passive'),
(@SethrakMask, @Warrior, '7381', 'Berserker Stance Passive'),
(@SethrakMask, @Warrior, '8386', 'Attacking'),
(@SethrakMask, @Warrior, '8737', 'Mail'),
(@SethrakMask, @Warrior, '9077', 'Leather'),
(@SethrakMask, @Warrior, '9078', 'Cloth'),
(@SethrakMask, @Warrior, '9116', 'Shield'),
(@SethrakMask, @Warrior, '9125', 'Generic'),
(@SethrakMask, @Warrior, '110001', 'Ancestral Call'),
(@SethrakMask, @Warrior, '110002', 'Savage Blood'),
(@SethrakMask, @Warrior, '110004', 'Unwavering Will'),
(@SethrakMask, @Warrior, '21156', 'Battle Stance Passive'),
(@SethrakMask, @Warrior, '110003', 'Sympathetic Vigor'),
(@SethrakMask, @Warrior, '21651', 'Opening'),
(@SethrakMask, @Warrior, '21652', 'Closing'),
(@SethrakMask, @Warrior, '22027', 'Remove Insignia'),
(@SethrakMask, @Warrior, '22810', 'Opening - No Text'),
(@SethrakMask, @Warrior, '32215', 'Victorious State'),
(@SethrakMask, @Warrior, '2048', 'Battle Shout'),
(@SethrakMask, @Warrior, '30324', 'Heroic Strike'),
(@SethrakMask, @Warrior, '11578', 'Charge'),
(@SethrakMask, @Warrior, '25208', 'Rend'),
(@SethrakMask, @Warrior, '25264', 'Thunder Clap'),
(@SethrakMask, @Warrior, '2687', 'Bloodrage'),
(@SethrakMask, @Warrior, '71', 'Defensive Stance'),
(@SethrakMask, @Warrior, '25225', 'Sunder Armor'),
(@SethrakMask, @Warrior, '355', 'Taunt'),
(@SethrakMask, @Warrior, '11585', 'Overpower'),
(@SethrakMask, @Warrior, '29704', 'Shield Bash'),
(@SethrakMask, @Warrior, '25203', 'Demoralizing Shout'),
(@SethrakMask, @Warrior, '30357', 'Revenge'),
(@SethrakMask, @Warrior, '25266', 'Mocking Blow'),
(@SethrakMask, @Warrior, '2565', 'Shield Block'),
(@SethrakMask, @Warrior, '676', 'Disarm'),
(@SethrakMask, @Warrior, '25231', 'Cleave'),
(@SethrakMask, @Warrior, '20230', 'Retaliation'),
(@SethrakMask, @Warrior, '5246', 'Intimidating Shout'),
(@SethrakMask, @Warrior, '25236', 'Execute'),
(@SethrakMask, @Warrior, '1161', 'Challenging Shout'),
(@SethrakMask, @Warrior, '871', 'Shield Wall'),
(@SethrakMask, @Warrior, '2458', 'Berserker Stance'),
(@SethrakMask, @Warrior, '25275', 'Intercept'),
(@SethrakMask, @Warrior, '25242', 'Slam'),
(@SethrakMask, @Warrior, '18499', 'Berserker Rage'),
(@SethrakMask, @Warrior, '1680', 'Whirlwind'),
(@SethrakMask, @Warrior, '6554', 'Pummel'),
(@SethrakMask, @Warrior, '1719', 'Recklessness'),
(@SethrakMask, @Warrior, '34428', 'Victory Rush'),
(@SethrakMask, @Warrior, '23920', 'Spell Reflection'),
(@SethrakMask, @Warrior, '469', 'Commanding Shout'),
(@SethrakMask, @Warrior, '3411', 'Intervene'),
(@SethrakMask, @Warrior, '25212', 'Hamstring'),
(@SethrakMask, @Warrior, '674', 'Dual Wield'),
(@SethrakMask, @Warrior, '750', 'Plate Armor'),
(@SethrakMask, @Warrior, '12678', 'Stance Mastery'),
-- Sethrak Paladin
(@SethrakMask, @Paladin, '81', 'Dodge'),
(@SethrakMask, @Paladin, '107', 'Block'),
(@SethrakMask, @Paladin, '198', 'One-Handed Maces'),
(@SethrakMask, @Paladin, '199', 'Two-Handed Maces'),
(@SethrakMask, @Paladin, '203', 'Unarmed'),
(@SethrakMask, @Paladin, '204', 'Defense'),
(@SethrakMask, @Paladin, '522', 'SPELLDEFENSE(DND)'),
(@SethrakMask, @Paladin, '635', 'Holy Light'),
(@SethrakMask, @Paladin, '669', 'Language Orcish'),
(@SethrakMask, @Paladin, '750', 'Plate Armor'),
-- ('14', '2', '1020', 'Divine Shield'), -- Removed?
(@SethrakMask, @Paladin, '1038', 'Hand of Salvation'),
(@SethrakMask, @Paladin, '1044', 'Hand of Freedom'),
(@SethrakMask, @Paladin, '2382', 'Generic'),
(@SethrakMask, @Paladin, '2479', 'Honorless Target'),
(@SethrakMask, @Paladin, '3050', 'Detect'),
(@SethrakMask, @Paladin, '3127', 'Parry'),
(@SethrakMask, @Paladin, '3365', 'Opening'),
(@SethrakMask, @Paladin, '4987', 'Cleanse'),
(@SethrakMask, @Paladin, '5502', 'Sense Undead'),
-- ('14', '2', '5627', 'Turn Undead'), -- Removed?
(@SethrakMask, @Paladin, '6233', 'Closing'),
(@SethrakMask, @Paladin, '6246', 'Closing'),
(@SethrakMask, @Paladin, '6247', 'Opening'),
(@SethrakMask, @Paladin, '6477', 'Opening'),
(@SethrakMask, @Paladin, '6478', 'Opening'),
(@SethrakMask, @Paladin, '6603', 'Attack'),
(@SethrakMask, @Paladin, '7266', 'Duel'),
(@SethrakMask, @Paladin, '7267', 'Grovel'),
(@SethrakMask, @Paladin, '7355', 'Stuck'),
(@SethrakMask, @Paladin, '8386', 'Attacking'),
(@SethrakMask, @Paladin, '8737', 'Mail'),
(@SethrakMask, @Paladin, '9077', 'Leather'),
(@SethrakMask, @Paladin, '9078', 'Cloth'),
(@SethrakMask, @Paladin, '9116', 'Shield'),
(@SethrakMask, @Paladin, '9125', 'Generic'),
(@SethrakMask, @Paladin, '10278', 'Hand of Protection'),
(@SethrakMask, @Paladin, '10308', 'Hammer of Justice'),
(@SethrakMask, @Paladin, '10326', 'Turn Evil'),
(@SethrakMask, @Paladin, '19746', 'Concentration Aura'),
(@SethrakMask, @Paladin, '19752', 'Divine Intervention'),
(@SethrakMask, @Paladin, '20271', 'Judgement of Light'),
(@SethrakMask, @Paladin, '110001', 'Ancestral Call'),
(@SethrakMask, @Paladin, '110002', 'Savage Blood'),
(@SethrakMask, @Paladin, '110004', 'Unwavering Will'),
(@SethrakMask, @Paladin, '110003', 'Sympathetic Vigor'),
(@SethrakMask, @Paladin, '20773', 'Redemption'),
(@SethrakMask, @Paladin, '21084', 'Seal of Righteousness'),
(@SethrakMask, @Paladin, '21651', 'Opening'),
(@SethrakMask, @Paladin, '21652', 'Closing'),
(@SethrakMask, @Paladin, '22027', 'Remove Insignia'),
(@SethrakMask, @Paladin, '22810', 'Opening - No Text'),
(@SethrakMask, @Paladin, '23214', 'Charger'),
(@SethrakMask, @Paladin, '25780', 'Righteous Fury'),
-- ('14', '2', '25895', 'Greater Blessing of Salvation'), -- Removed?
(@SethrakMask, @Paladin, '25898', 'Greater Blessing of Kings'),
(@SethrakMask, @Paladin, '27136', 'Holy Light'),
(@SethrakMask, @Paladin, '27137', 'Flash of Light'),
(@SethrakMask, @Paladin, '27138', 'Exorcism'),
(@SethrakMask, @Paladin, '27139', 'Holy Wrath'),
(@SethrakMask, @Paladin, '27140', 'Blessing of Might'),
(@SethrakMask, @Paladin, '27141', 'Greater Blessing of Might'),
(@SethrakMask, @Paladin, '27142', 'Blessing of Wisdom'),
(@SethrakMask, @Paladin, '27143', 'Greater Blessing of Wisdom'),
-- ('14', '2', '27144', 'Blessing of Light'), -- Removed?
-- ('14', '2', '27145', 'Greater Blessing of Light'), -- Removed?
-- ('14', '2', '27148', 'Blessing of Sacrifice'), -- Removed?
(@SethrakMask, @Paladin, '27149', 'Devotion Aura'),
(@SethrakMask, @Paladin, '27150', 'Retribution Aura'),
(@SethrakMask, @Paladin, '27151', 'Shadow Resistance Aura'),
(@SethrakMask, @Paladin, '27152', 'Frost Resistance Aura'),
(@SethrakMask, @Paladin, '27153', 'Fire Resistance Aura'),
(@SethrakMask, @Paladin, '27154', 'Lay on Hands'),
-- ('14', '2', '27155', 'Seal of Righteousness'), -- Removed?
-- ('14', '2', '27158', 'Seal of the Crusader'), -- Removed?
-- ('14', '2', '27160', 'Seal of Light'), -- Removed?
-- ('14', '2', '27166', 'Seal of Wisdom'), -- Removed?
-- ('14', '2', '27169', 'Greater Blessing of Sanctuary'), -- Removed?
(@SethrakMask, @Paladin, '27173', 'Consecration'),
(@SethrakMask, @Paladin, '27180', 'Hammer of Wrath'),
(@SethrakMask, @Paladin, '27762', 'Libram'),
(@SethrakMask, @Paladin, '31789', 'Righteous Defense'),
(@SethrakMask, @Paladin, '31801', 'Seal of Vengeance'),
(@SethrakMask, @Paladin, '31884', 'Avenging Wrath'),
-- ('14', '2', '31895', 'Seal of Justice'), -- Removed?
(@SethrakMask, @Paladin, '32223', 'Crusader Aura'),
(@SethrakMask, @Paladin, '33776', 'Spiritual Attunement'),
-- Sethrak Hunter
(@SethrakMask, @Hunter, '75', 'Auto Shot'),
(@SethrakMask, @Hunter, '81', 'Dodge'),
(@SethrakMask, @Hunter, '196', 'One-Handed Axes'),
(@SethrakMask, @Hunter, '203', 'Unarmed'),
(@SethrakMask, @Hunter, '204', 'Defense'),
(@SethrakMask, @Hunter, '264', 'Bows'),
(@SethrakMask, @Hunter, '522', 'SPELLDEFENSE(DND)'),
(@SethrakMask, @Hunter, '669', 'Language Orcish'),
(@SethrakMask, @Hunter, '2382', 'Generic'),
(@SethrakMask, @Hunter, '2479', 'Honorless Target'),
(@SethrakMask, @Hunter, '2973', 'Raptor Strike'),
(@SethrakMask, @Hunter, '3050', 'Detect'),
(@SethrakMask, @Hunter, '3365', 'Opening'),
(@SethrakMask, @Hunter, '6233', 'Closing'),
(@SethrakMask, @Hunter, '6246', 'Closing'),
(@SethrakMask, @Hunter, '6247', 'Opening'),
(@SethrakMask, @Hunter, '6477', 'Opening'),
(@SethrakMask, @Hunter, '6478', 'Opening'),
(@SethrakMask, @Hunter, '6603', 'Attack'),
(@SethrakMask, @Hunter, '7266', 'Duel'),
(@SethrakMask, @Hunter, '7267', 'Grovel'),
(@SethrakMask, @Hunter, '7355', 'Stuck'),
(@SethrakMask, @Hunter, '8386', 'Attacking'),
(@SethrakMask, @Hunter, '9077', 'Leather'),
(@SethrakMask, @Hunter, '9078', 'Cloth'),
(@SethrakMask, @Hunter, '9125', 'Generic'),
(@SethrakMask, @Hunter, '13358', 'Defensive State(DND)'),
(@SethrakMask, @Hunter, '110001', 'Ancestral Call'),
(@SethrakMask, @Hunter, '110002', 'Savage Blood'),
(@SethrakMask, @Hunter, '110004', 'Unwavering Will'),
(@SethrakMask, @Hunter, '110003', 'Sympathetic Vigor'),
(@SethrakMask, @Hunter, '21651', 'Opening'),
(@SethrakMask, @Hunter, '21652', 'Closing'),
(@SethrakMask, @Hunter, '22027', 'Remove Insignia'),
(@SethrakMask, @Hunter, '22810', 'Opening - No Text'),
(@SethrakMask, @Hunter, '24949', 'Defensive State 2(DND)'),
(@SethrakMask, @Hunter, '34082', 'Advantaged State(DND)'),
(@SethrakMask, @Hunter, '27014', 'Raptor Strike'),
(@SethrakMask, @Hunter, '1494', 'Track Beasts'),
(@SethrakMask, @Hunter, '13163', 'Aspect of the Monkey'),
(@SethrakMask, @Hunter, '27016', 'Serpent Sting'),
(@SethrakMask, @Hunter, '27019', 'Arcane Shot'),
(@SethrakMask, @Hunter, '14325', 'Hunters Mark'),
(@SethrakMask, @Hunter, '5116', 'Concussive Shot'),
(@SethrakMask, @Hunter, '27044', 'Aspect of the Hawk'),
(@SethrakMask, @Hunter, '883', 'Call Pet'),
(@SethrakMask, @Hunter, '2641', 'Dismiss Pet'),
(@SethrakMask, @Hunter, '6991', 'Feed Pet'),
(@SethrakMask, @Hunter, '982', 'Revive Pet'),
(@SethrakMask, @Hunter, '1515', 'Tame Beast'),
(@SethrakMask, @Hunter, '19883', 'Track Humanoids'),
-- ('14', '4', '27020', 'Distracting Shot'), -- Removed?
(@SethrakMask, @Hunter, '27046', 'Mend Pet'),
(@SethrakMask, @Hunter, '14268', 'Alliance Flag'), -- What?
(@SethrakMask, @Hunter, '6197', 'Eagle Eye'),
(@SethrakMask, @Hunter, '1002', 'Eyes of the Beast'),
(@SethrakMask, @Hunter, '14327', 'Scare Beast'),
(@SethrakMask, @Hunter, '27023', 'Immolation Trap'),
(@SethrakMask, @Hunter, '36916', 'Mongoose Bite'),
(@SethrakMask, @Hunter, '27021', 'Multi-Shot'),
(@SethrakMask, @Hunter, '19884', 'Track Undead'),
(@SethrakMask, @Hunter, '5118', 'Aspect of the Cheetah'),
-- ('14', '4', '27015', 'Disengage'), -- Removed?
(@SethrakMask, @Hunter, '14311', 'Freezing Trap'),
(@SethrakMask, @Hunter, '3043', 'Scorpid Sting'),
(@SethrakMask, @Hunter, '1462', 'Beast Lore'),
(@SethrakMask, @Hunter, '19885', 'Track Hidden'),
(@SethrakMask, @Hunter, '3045', 'Rapid Fire'),
(@SethrakMask, @Hunter, '19880', 'Track Elementals'),
(@SethrakMask, @Hunter, '13809', 'Frost Trap'),
(@SethrakMask, @Hunter, '13161', 'Aspect of the Beast'),
(@SethrakMask, @Hunter, '5384', 'Feign Death'),
(@SethrakMask, @Hunter, '1543', 'Flare'),
(@SethrakMask, @Hunter, '19878', 'Track Demons'),
(@SethrakMask, @Hunter, '27025', 'Explosive Trap'),
-- ('14', '4', '27018', 'Viper Sting'), -- Removed?
(@SethrakMask, @Hunter, '13159', 'Aspect of the Pack'),
(@SethrakMask, @Hunter, '19882', 'Track Giants'),
(@SethrakMask, @Hunter, '27022', 'Volley'),
(@SethrakMask, @Hunter, '27045', 'Aspect of the Wild'),
(@SethrakMask, @Hunter, '19879', 'Track Dragonkin'),
(@SethrakMask, @Hunter, '19801', 'Tranquilizing Shot'),
(@SethrakMask, @Hunter, '34120', 'Steady Shot'),
(@SethrakMask, @Hunter, '34074', 'Aspect of the Viper'),
(@SethrakMask, @Hunter, '34026', 'Kill Command'),
(@SethrakMask, @Hunter, '34600', 'Snake Trap'),
(@SethrakMask, @Hunter, '34477', 'Misdirection'),
(@SethrakMask, @Hunter, '674', 'Dual Wield'),
(@SethrakMask, @Hunter, '8737', 'Mail'),
(@SethrakMask, @Hunter, '5149', 'Beast Training'), -- Only 8?
(@SethrakMask, @Hunter, '3127', 'Parry'),
-- Sethrak Rogue
(@SethrakMask, @Rogue, '81', 'Dodge'),
(@SethrakMask, @Rogue, '203', 'Unarmed'),
(@SethrakMask, @Rogue, '204', 'Defense'),
(@SethrakMask, @Rogue, '522', 'SPELLDEFENSE(DND)'),
(@SethrakMask, @Rogue, '669', 'Language Orcish'),
(@SethrakMask, @Rogue, '1180', 'Daggers'),
(@SethrakMask, @Rogue, '1752', 'Sinister Strike'),
(@SethrakMask, @Rogue, '2098', 'Eviscerate'),
(@SethrakMask, @Rogue, '2382', 'Generic'),
(@SethrakMask, @Rogue, '2479', 'Honorless Target'),
(@SethrakMask, @Rogue, '2567', 'Thrown'),
(@SethrakMask, @Rogue, '2764', 'Throw'),
(@SethrakMask, @Rogue, '3050', 'Detect'),
(@SethrakMask, @Rogue, '3365', 'Opening'),
(@SethrakMask, @Rogue, '6233', 'Closing'),
(@SethrakMask, @Rogue, '6246', 'Closing'),
(@SethrakMask, @Rogue, '6247', 'Opening'),
(@SethrakMask, @Rogue, '6477', 'Opening'),
(@SethrakMask, @Rogue, '6478', 'Opening'),
(@SethrakMask, @Rogue, '6603', 'Attack'),
(@SethrakMask, @Rogue, '7266', 'Duel'),
(@SethrakMask, @Rogue, '7267', 'Grovel'),
(@SethrakMask, @Rogue, '7355', 'Stuck'),
(@SethrakMask, @Rogue, '8386', 'Attacking'),
(@SethrakMask, @Rogue, '9077', 'Leather'),
(@SethrakMask, @Rogue, '9078', 'Cloth'),
(@SethrakMask, @Rogue, '9125', 'Generic'),
(@SethrakMask, @Rogue, '16092', 'Defensive State(DND)'),
(@SethrakMask, @Rogue, '110001', 'Ancestral Call'),
(@SethrakMask, @Rogue, '110002', 'Savage Blood'),
(@SethrakMask, @Rogue, '110004', 'Unwavering Will'),
(@SethrakMask, @Rogue, '21184', 'Rogue Passive(DND)'),
(@SethrakMask, @Rogue, '110003', 'Sympathetic Vigor'),
(@SethrakMask, @Rogue, '21651', 'Opening'),
(@SethrakMask, @Rogue, '21652', 'Closing'),
(@SethrakMask, @Rogue, '22027', 'Remove Insignia'),
(@SethrakMask, @Rogue, '22810', 'Opening - No Text'),
(@SethrakMask, @Rogue, '26865', 'Eviscerate'),
(@SethrakMask, @Rogue, '26862', 'Sinister Strike'),
(@SethrakMask, @Rogue, '1787', 'Stealth'),
(@SethrakMask, @Rogue, '26863', 'Backstab'),
(@SethrakMask, @Rogue, '921', 'Pick Pocket'),
(@SethrakMask, @Rogue, '38764', 'Gouge'),
(@SethrakMask, @Rogue, '26669', 'Evasion'),
(@SethrakMask, @Rogue, '11297', 'Sap'),
(@SethrakMask, @Rogue, '6774', 'Slice and Dice'),
(@SethrakMask, @Rogue, '11305', 'Sprint'),
(@SethrakMask, @Rogue, '38768', 'Kick'),
(@SethrakMask, @Rogue, '26866', 'Expose Armor'),
(@SethrakMask, @Rogue, '26884', 'Garrote'),
(@SethrakMask, @Rogue, '27448', 'Feint'),
(@SethrakMask, @Rogue, '1804', 'Pick Lock'),
(@SethrakMask, @Rogue, '27441', 'Ambush'),
(@SethrakMask, @Rogue, '2842', 'Poisons'),
(@SethrakMask, @Rogue, '1725', 'Distract'),
(@SethrakMask, @Rogue, '26867', 'Rupture'),
(@SethrakMask, @Rogue, '26889', 'Vanish'),
(@SethrakMask, @Rogue, '1833', 'Cheap Shot'),
(@SethrakMask, @Rogue, '1842', 'Disarm Trap'),
(@SethrakMask, @Rogue, '408', 'Kidney Shot'),
(@SethrakMask, @Rogue, '2094', 'Blind'),
(@SethrakMask, @Rogue, '32684', 'Envenom'),
(@SethrakMask, @Rogue, '26679', 'Deadly Throw'),
(@SethrakMask, @Rogue, '31224', 'Cloak of Shadows'),
(@SethrakMask, @Rogue, '5938', 'Shiv'),
(@SethrakMask, @Rogue, '8643', 'Kidney Shot'),
(@SethrakMask, @Rogue, '3127', 'Parry'),
(@SethrakMask, @Rogue, '674', 'Dual Wield'),
(@SethrakMask, @Rogue, '3776', 'Green Leather Bracers'),
-- ('14', '8', '9186', null), -- Removed?
(@SethrakMask, @Rogue, '21927', 'Natures Ally'),
(@SethrakMask, @Rogue, '22054', 'QAEnchant Bracer +7 Intellect'),
-- ('14', '8', '22055', null), -- Removed?
(@SethrakMask, @Rogue, '2836', 'Detect Traps'),
(@SethrakMask, @Rogue, '1860', 'Safe Fall'),
-- Sethrak Priest
(@SethrakMask, @Priest, '669', 'Language Orcish'),
(@SethrakMask, @Priest, '110001', 'Ancestral Call'),
(@SethrakMask, @Priest, '110002', 'Savage Blood'),
(@SethrakMask, @Priest, '110004', 'Unwavering Will'),
(@SethrakMask, @Priest, '110003', 'Sympathetic Vigor'),
(@SethrakMask, @Priest, '81', 'Dodge'),
(@SethrakMask, @Priest, '198', 'One-Handed Maces'),
(@SethrakMask, @Priest, '203', 'Unarmed'),
(@SethrakMask, @Priest, '204', 'Defense'),
(@SethrakMask, @Priest, '522', 'SPELLDEFENSE(DND)'),
(@SethrakMask, @Priest, '585', 'Smite'),
(@SethrakMask, @Priest, '2050', 'Lesser Heal'),
(@SethrakMask, @Priest, '2382', 'Generic'),
(@SethrakMask, @Priest, '2479', 'Honorless Target'),
(@SethrakMask, @Priest, '3050', 'Detect'),
(@SethrakMask, @Priest, '3365', 'Opening'),
(@SethrakMask, @Priest, '5009', 'Wands'),
(@SethrakMask, @Priest, '5019', 'Shoot'),
(@SethrakMask, @Priest, '6233', 'Closing'),
(@SethrakMask, @Priest, '6246', 'Closing'),
(@SethrakMask, @Priest, '6247', 'Opening'),
(@SethrakMask, @Priest, '6477', 'Opening'),
(@SethrakMask, @Priest, '6478', 'Opening'),
(@SethrakMask, @Priest, '6603', 'Attack'),
(@SethrakMask, @Priest, '7266', 'Duel'),
(@SethrakMask, @Priest, '7267', 'Grovel'),
(@SethrakMask, @Priest, '7355', 'Stuck'),
(@SethrakMask, @Priest, '8386', 'Attacking'),
(@SethrakMask, @Priest, '9078', 'Cloth'),
(@SethrakMask, @Priest, '9125', 'Generic'),
(@SethrakMask, @Priest, '21651', 'Opening'),
(@SethrakMask, @Priest, '21652', 'Closing'),
(@SethrakMask, @Priest, '22027', 'Remove Insignia'),
(@SethrakMask, @Priest, '22810', 'Opening - No Text'),
(@SethrakMask, @Priest, '25389', 'Power Word: Fortitude'),
(@SethrakMask, @Priest, '25364', 'Smite'),
(@SethrakMask, @Priest, '25368', 'Shadow Word: Pain'),
(@SethrakMask, @Priest, '25218', 'Power Word: Shield'),
-- ('14', '16', '25429', 'Fade'), -- Removed?
(@SethrakMask, @Priest, '25222', 'Renew'),
(@SethrakMask, @Priest, '25375', 'Mind Blast'),
(@SethrakMask, @Priest, '25435', 'Resurrection'),
(@SethrakMask, @Priest, '25431', 'Inner Fire'),
(@SethrakMask, @Priest, '528', 'Cure Disease'),
(@SethrakMask, @Priest, '10890', 'Psychic Scream'),
(@SethrakMask, @Priest, '988', 'Dispel Magic'),
(@SethrakMask, @Priest, '6346', 'Fear Ward'),
(@SethrakMask, @Priest, '25235', 'Flash Heal'),
(@SethrakMask, @Priest, '25384', 'Holy Fire'),
-- ('14', '16', '25596', 'Mind Soothe'), -- Removed?
(@SethrakMask, @Priest, '10955', 'Shackle Undead'),
(@SethrakMask, @Priest, '10909', 'Mind Vision'),
-- ('14', '16', '25380', 'Mana Burn'), -- Removed?
-- ('14', '16', '10912', 'Mind Control'), -- Removed?
(@SethrakMask, @Priest, '25308', 'Prayer of Healing'),
(@SethrakMask, @Priest, '25433', 'Shadow Protection'),
(@SethrakMask, @Priest, '552', 'Abolish Disease'),
(@SethrakMask, @Priest, '1706', 'Levitate'),
(@SethrakMask, @Priest, '25213', 'Greater Heal'),
(@SethrakMask, @Priest, '25392', 'Prayer of Fortitude'),
(@SethrakMask, @Priest, '39374', 'Prayer of Shadow Protection'),
(@SethrakMask, @Priest, '32999', 'Prayer of Spirit'),
(@SethrakMask, @Priest, '32996', 'Shadow Word: Death'),
(@SethrakMask, @Priest, '32546', 'Binding Heal'),
(@SethrakMask, @Priest, '34433', 'Shadowfiend'),
(@SethrakMask, @Priest, '33076', 'Prayer of Mending'),
(@SethrakMask, @Priest, '32375', 'Mass Dispel'),
-- ('14', '16', '25441', 'Feedback'), -- Removed?
(@SethrakMask, @Priest, '25312', 'Divine Spirit'),
(@SethrakMask, @Priest, '25437', 'Desperate Prayer'),
-- Sethrak Shaman
(@SethrakMask, @Shaman, '81', 'Dodge'),
(@SethrakMask, @Shaman, '107', 'Block'),
(@SethrakMask, @Shaman, '198', 'One-Handed Maces'),
(@SethrakMask, @Shaman, '203', 'Unarmed'),
(@SethrakMask, @Shaman, '204', 'Defense'),
(@SethrakMask, @Shaman, '227', 'Staves'),
(@SethrakMask, @Shaman, '331', 'Healing Wave'),
(@SethrakMask, @Shaman, '403', 'Lightning Bolt'),
(@SethrakMask, @Shaman, '522', 'SPELLDEFENSE(DND)'),
(@SethrakMask, @Shaman, '669', 'Language Orcish'),
(@SethrakMask, @Shaman, '2382', 'Generic'),
(@SethrakMask, @Shaman, '2479', 'Honorless Target'),
(@SethrakMask, @Shaman, '3050', 'Detect'),
(@SethrakMask, @Shaman, '3365', 'Opening'),
(@SethrakMask, @Shaman, '6233', 'Closing'),
(@SethrakMask, @Shaman, '6246', 'Closing'),
(@SethrakMask, @Shaman, '6247', 'Opening'),
(@SethrakMask, @Shaman, '6477', 'Opening'),
(@SethrakMask, @Shaman, '6478', 'Opening'),
(@SethrakMask, @Shaman, '6603', 'Attack'),
(@SethrakMask, @Shaman, '7266', 'Duel'),
(@SethrakMask, @Shaman, '7267', 'Grovel'),
(@SethrakMask, @Shaman, '7355', 'Stuck'),
(@SethrakMask, @Shaman, '8386', 'Attacking'),
(@SethrakMask, @Shaman, '9077', 'Leather'),
(@SethrakMask, @Shaman, '9078', 'Cloth'),
(@SethrakMask, @Shaman, '9116', 'Shield'),
(@SethrakMask, @Shaman, '9125', 'Generic'),
(@SethrakMask, @Shaman, '110002', 'Savage Blood'),
(@SethrakMask, @Shaman, '110004', 'Unwavering Will'),
(@SethrakMask, @Shaman, '110003', 'Sympathetic Vigor'),
(@SethrakMask, @Shaman, '21651', 'Opening'),
(@SethrakMask, @Shaman, '21652', 'Closing'),
(@SethrakMask, @Shaman, '22027', 'Remove Insignia'),
(@SethrakMask, @Shaman, '22810', 'Opening - No Text'),
(@SethrakMask, @Shaman, '27763', 'Totem'),
(@SethrakMask, @Shaman, '33697', 'Blood Fury'),
(@SethrakMask, @Shaman, '25396', 'Healing Wave'),
(@SethrakMask, @Shaman, '25449', 'Lightning Bolt'),
-- ('14', '64', '25485', 'Rockbiter Weapon'), -- Removed?
(@SethrakMask, @Shaman, '25454', 'Earth Shock'),
(@SethrakMask, @Shaman, '25509', 'Stoneskin Totem'),
(@SethrakMask, @Shaman, '2484', 'Earthbind Totem'),
(@SethrakMask, @Shaman, '25472', 'Lightning Shield'),
(@SethrakMask, @Shaman, '25525', 'Stoneclaw Totem'),
(@SethrakMask, @Shaman, '25457', 'Flame Shock'),
(@SethrakMask, @Shaman, '25489', 'Flametongue Weapon'),
(@SethrakMask, @Shaman, '25533', 'Searing Totem'),
(@SethrakMask, @Shaman, '25528', 'Strength of Earth Totem'),
(@SethrakMask, @Shaman, '20777', 'Ancestral Spirit'),
(@SethrakMask, @Shaman, '25547', 'Fire Nova'),
(@SethrakMask, @Shaman, '8012', 'Purge'),
(@SethrakMask, @Shaman, '526', 'Cure Toxins'),
(@SethrakMask, @Shaman, '8143', 'Tremor Totem'),
(@SethrakMask, @Shaman, '25464', 'Frost Shock'),
(@SethrakMask, @Shaman, '25500', 'Frostbrand Weapon'),
(@SethrakMask, @Shaman, '2645', 'Ghost Wolf'),
(@SethrakMask, @Shaman, '25567', 'Healing Stream Totem'),
(@SethrakMask, @Shaman, '25420', 'Lesser Healing Wave'),
-- ('14', '64', '2870', 'Cure Disease'), -- Removed?
(@SethrakMask, @Shaman, '8166', 'Poison Cleansing Totem'),
(@SethrakMask, @Shaman, '131', 'Water Breathing'),
(@SethrakMask, @Shaman, '25560', 'Frost Resistance Totem'),
(@SethrakMask, @Shaman, '6196', 'Far Sight'),
(@SethrakMask, @Shaman, '25552', 'Magma Totem'),
(@SethrakMask, @Shaman, '25570', 'Mana Spring Totem'),
(@SethrakMask, @Shaman, '25563', 'Fire Resistance Totem'),
(@SethrakMask, @Shaman, '25557', 'Flametongue Totem'),
(@SethrakMask, @Shaman, '546', 'Water Walking'),
(@SethrakMask, @Shaman, '556', 'Astral Recall'),
(@SethrakMask, @Shaman, '8177', 'Grounding Totem'),
(@SethrakMask, @Shaman, '25574', 'Nature Resistance Totem'),
(@SethrakMask, @Shaman, '36936', 'Totemic Recall'),
(@SethrakMask, @Shaman, '25505', 'Windfury Weapon'),
(@SethrakMask, @Shaman, '421', 'Chain Lightning'),
-- ('14', '64', '25587', 'Windfury Totem'), -- Removed?
(@SethrakMask, @Shaman, '6495', 'Sentry Totem'),
-- ('14', '64', '25577', 'Windwall Totem'), -- Removed?
(@SethrakMask, @Shaman, '8170', 'Cleansing Totem'),
(@SethrakMask, @Shaman, '25423', 'Chain Heal'),
-- ('14', '64', '25359', 'Grace of Air Totem'), -- Removed?
-- ('14', '64', '25908', 'Tranquil Air Totem'), -- Removed?
(@SethrakMask, @Shaman, '33736', 'Water Shield'),
(@SethrakMask, @Shaman, '3738', 'Wrath of Air Totem'),
(@SethrakMask, @Shaman, '2062', 'Earth Elemental Totem'),
(@SethrakMask, @Shaman, '2894', 'Fire Elemental Totem'),
(@SethrakMask, @Shaman, '2825', 'Bloodlust'), -- Only 9?
(@SethrakMask, @Shaman, '25442', 'Chain Lightning'), -- Only 6?
(@SethrakMask, @Shaman, '8737', 'Mail'),
(@SethrakMask, @Shaman, '20608', 'Reincarnation'), -- Only 6?
-- Sethrak Mage
(@SethrakMask, @Mage, '669', 'Language Orcish'),
(@SethrakMask, @Mage, '110001', 'Ancestral Call'),
(@SethrakMask, @Mage, '110002', 'Savage Blood'),
(@SethrakMask, @Mage, '110004', 'Unwavering Will'),
(@SethrakMask, @Mage, '110003', 'Sympathetic Vigor'),
(@SethrakMask, @Mage, '81', 'Dodge'),
(@SethrakMask, @Mage, '133', 'Fireball'),
(@SethrakMask, @Mage, '168', 'Frost Armor'),
(@SethrakMask, @Mage, '203', 'Unarmed'),
(@SethrakMask, @Mage, '204', 'Defense'),
(@SethrakMask, @Mage, '227', 'Staves'),
(@SethrakMask, @Mage, '522', 'SPELLDEFENSE(DND)'),
(@SethrakMask, @Mage, '2382', 'Generic'),
(@SethrakMask, @Mage, '2479', 'Honorless Target'),
(@SethrakMask, @Mage, '3050', 'Detect'),
(@SethrakMask, @Mage, '3365', 'Opening'),
(@SethrakMask, @Mage, '5009', 'Wands'),
(@SethrakMask, @Mage, '5019', 'Shoot'),
(@SethrakMask, @Mage, '6233', 'Closing'),
(@SethrakMask, @Mage, '6246', 'Closing'),
(@SethrakMask, @Mage, '6247', 'Opening'),
(@SethrakMask, @Mage, '6477', 'Opening'),
(@SethrakMask, @Mage, '6478', 'Opening'),
(@SethrakMask, @Mage, '6603', 'Attack'),
(@SethrakMask, @Mage, '7266', 'Duel'),
(@SethrakMask, @Mage, '7267', 'Grovel'),
(@SethrakMask, @Mage, '7355', 'Stuck'),
(@SethrakMask, @Mage, '8386', 'Attacking'),
(@SethrakMask, @Mage, '9078', 'Cloth'),
(@SethrakMask, @Mage, '9125', 'Generic'),
(@SethrakMask, @Mage, '21651', 'Opening'),
(@SethrakMask, @Mage, '21652', 'Closing'),
(@SethrakMask, @Mage, '22027', 'Remove Insignia'),
(@SethrakMask, @Mage, '22810', 'Opening - No Text'),
(@SethrakMask, @Mage, '27126', 'Arcane Intellect'),
(@SethrakMask, @Mage, '27070', 'Fireball'),
(@SethrakMask, @Mage, '22018', null),
(@SethrakMask, @Mage, '27072', 'Frostbolt'),
(@SethrakMask, @Mage, '22019', null),
(@SethrakMask, @Mage, '27079', 'Fire Blast'),
(@SethrakMask, @Mage, '38704', 'Arcane Missiles'),
(@SethrakMask, @Mage, '28272', 'Polymorph (Pig)'),
(@SethrakMask, @Mage, '28271', 'Polymorph (Turtle)'),
(@SethrakMask, @Mage, '12826', 'Polymorph (Sheep)'),
(@SethrakMask, @Mage, '27088', 'Frost Nova'),
(@SethrakMask, @Mage, '33944', 'Dampen Magic'),
(@SethrakMask, @Mage, '130', 'Slow Fall'),
(@SethrakMask, @Mage, '27082', 'Arcane Explosion'),
(@SethrakMask, @Mage, '27086', 'Flamestrike'),
(@SethrakMask, @Mage, '33946', 'Amplify Magic'),
(@SethrakMask, @Mage, '475', 'Remove Curse'),
(@SethrakMask, @Mage, '1953', 'Blink'),
(@SethrakMask, @Mage, '27085', 'Blizzard'),
(@SethrakMask, @Mage, '12051', 'Evocation'),
(@SethrakMask, @Mage, '27128', 'Fire Ward'),
(@SethrakMask, @Mage, '27131', 'Mana Shield'),
(@SethrakMask, @Mage, '32796', 'Frost Ward'),
(@SethrakMask, @Mage, '27074', 'Scorch'),
(@SethrakMask, @Mage, '2139', 'Counterspell'),
(@SethrakMask, @Mage, '27101', 'Conjure Mana Gem'),
(@SethrakMask, @Mage, '27124', 'Ice Armor'),
(@SethrakMask, @Mage, '45438', 'Ice Block'),
(@SethrakMask, @Mage, '27125', 'Mage Armor'),
(@SethrakMask, @Mage, '27127', 'Arcane Brilliance'),
(@SethrakMask, @Mage, '30482', 'Molten Armor'),
(@SethrakMask, @Mage, '30451', 'Arcane Blast'),
(@SethrakMask, @Mage, '30455', 'Ice Lance'),
(@SethrakMask, @Mage, '66', 'Invisibility'),
(@SethrakMask, @Mage, '43987', 'Ritual of Refreshment'),
(@SethrakMask, @Mage, '30449', 'Spellsteal'),
(@SethrakMask, @Mage, '27087', 'Cone of Cold'),
-- Sethrak Warlock
(@SethrakMask, @Warlock, '81', 'Dodge'),
(@SethrakMask, @Warlock, '203', 'Unarmed'),
(@SethrakMask, @Warlock, '204', 'Defense'),
(@SethrakMask, @Warlock, '522', 'SPELLDEFENSE(DND)'),
(@SethrakMask, @Warlock, '669', 'Language Orcish'),
(@SethrakMask, @Warlock, '686', 'Shadow Bolt'),
(@SethrakMask, @Warlock, '687', 'Demon Skin'),
(@SethrakMask, @Warlock, '1180', 'Daggers'),
(@SethrakMask, @Warlock, '2382', 'Generic'),
(@SethrakMask, @Warlock, '2479', 'Honorless Target'),
(@SethrakMask, @Warlock, '3050', 'Detect'),
(@SethrakMask, @Warlock, '3365', 'Opening'),
(@SethrakMask, @Warlock, '5009', 'Wands'),
(@SethrakMask, @Warlock, '5019', 'Shoot'),
(@SethrakMask, @Warlock, '6233', 'Closing'),
(@SethrakMask, @Warlock, '6246', 'Closing'),
(@SethrakMask, @Warlock, '6247', 'Opening'),
(@SethrakMask, @Warlock, '6477', 'Opening'),
(@SethrakMask, @Warlock, '6478', 'Opening'),
(@SethrakMask, @Warlock, '6603', 'Attack'),
(@SethrakMask, @Warlock, '7266', 'Duel'),
(@SethrakMask, @Warlock, '7267', 'Grovel'),
(@SethrakMask, @Warlock, '7355', 'Stuck'),
(@SethrakMask, @Warlock, '8386', 'Attacking'),
(@SethrakMask, @Warlock, '9078', 'Cloth'),
(@SethrakMask, @Warlock, '9125', 'Generic'),
(@SethrakMask, @Warlock, '110002', 'Savage Blood'),
(@SethrakMask, @Warlock, '110004', 'Unwavering Will'),
(@SethrakMask, @Warlock, '110003', 'Sympathetic Vigor'),
(@SethrakMask, @Warlock, '21651', 'Opening'),
(@SethrakMask, @Warlock, '21652', 'Closing'),
(@SethrakMask, @Warlock, '22027', 'Remove Insignia'),
(@SethrakMask, @Warlock, '22810', 'Opening - No Text'),
(@SethrakMask, @Warlock, '33702', 'Blood Fury'),
(@SethrakMask, @Warlock, '27215', 'Immolate'),
(@SethrakMask, @Warlock, '27209', 'Shadow Bolt'),
(@SethrakMask, @Warlock, '27216', 'Corruption'),
(@SethrakMask, @Warlock, '30909', 'Curse of Weakness'),
(@SethrakMask, @Warlock, '27222', 'Life Tap'),
(@SethrakMask, @Warlock, '27218', 'Curse of Agony'),
(@SethrakMask, @Warlock, '6215', 'Fear'),
(@SethrakMask, @Warlock, '27230', 'Create Healthstone'),
(@SethrakMask, @Warlock, '27217', 'Drain Soul'),
(@SethrakMask, @Warlock, '27259', 'Health Funnel'),
-- ('14', '256', '27226', 'Curse of Recklessness'), -- Removed?
(@SethrakMask, @Warlock, '27220', 'Drain Life'),
(@SethrakMask, @Warlock, '5697', 'Unending Breath'),
(@SethrakMask, @Warlock, '27238', 'Create Soulstone'),
(@SethrakMask, @Warlock, '30459', 'Searing Pain'),
(@SethrakMask, @Warlock, '27260', 'Demon Armor'),
(@SethrakMask, @Warlock, '27212', 'Rain of Fire'),
(@SethrakMask, @Warlock, '698', 'Ritual of Summoning'),
(@SethrakMask, @Warlock, '5500', 'Sense Demons'),
-- ('14', '256', '30908', 'Drain Mana'), -- Removed?
(@SethrakMask, @Warlock, '11719', 'Curse of Tongues'),
(@SethrakMask, @Warlock, '132', 'Detect Invisibility'),
(@SethrakMask, @Warlock, '18647', 'Banish'),
(@SethrakMask, @Warlock, '27213', 'Hellfire'),
(@SethrakMask, @Warlock, '11726', 'Subjugate Demon'),
(@SethrakMask, @Warlock, '27228', 'Curse of the Elements'),
(@SethrakMask, @Warlock, '28610', 'Shadow Ward'),
(@SethrakMask, @Warlock, '28172', 'Create Spellstone'),
(@SethrakMask, @Warlock, '27250', 'Create Firestone'),
(@SethrakMask, @Warlock, '17928', 'Howl of Terror'),
(@SethrakMask, @Warlock, '27223', 'Death Coil'),
-- ('14', '256', '27229', 'Curse of Shadow'), -- Removed?
(@SethrakMask, @Warlock, '30545', 'Soul Fire'),
(@SethrakMask, @Warlock, '30910', 'Curse of Doom'),
(@SethrakMask, @Warlock, '18540', 'Ritual of Doom'),
(@SethrakMask, @Warlock, '28189', 'Fel Armor'),
(@SethrakMask, @Warlock, '32231', 'Incinerate'),
(@SethrakMask, @Warlock, '29858', 'Soulshatter'),
(@SethrakMask, @Warlock, '29893', 'Ritual of Souls'),
(@SethrakMask, @Warlock, '27243', 'Seed of Corruption'),
(@SethrakMask, @Warlock, '23161', 'Dreadsteed'),
(@SethrakMask, @Warlock, '688', 'Summon Imp'),
(@SethrakMask, @Warlock, '697', 'Summon Voidwalker'),
(@SethrakMask, @Warlock, '712', 'Summon Succubus'),
(@SethrakMask, @Warlock, '691', 'Summon Felhunter'),
(@SethrakMask, @Warlock, '126', 'Eye of Kilrogg'),
-- Sethrak Druid
(@SethrakMask, @Druid, '669', 'Language Orcish'),
(@SethrakMask, @Druid, '110001', 'Ancestral Call'),
(@SethrakMask, @Druid, '110002', 'Savage Blood'),
(@SethrakMask, @Druid, '110004', 'Unwavering Will'),
(@SethrakMask, @Druid, '110003', 'Sympathetic Vigor'),
(@SethrakMask, @Druid, '81', 'Dodge'),
(@SethrakMask, @Druid, '198', 'One-Handed Maces'),
(@SethrakMask, @Druid, '203', 'Unarmed'),
(@SethrakMask, @Druid, '204', 'Defense'),
(@SethrakMask, @Druid, '227', 'Staves'),
(@SethrakMask, @Druid, '522', 'SPELLDEFENSE(DND)'),
(@SethrakMask, @Druid, '1178', 'Bear Form(Passive)'),
(@SethrakMask, @Druid, '2382', 'Generic'),
(@SethrakMask, @Druid, '2479', 'Honorless Target'),
(@SethrakMask, @Druid, '3025', 'Cat Form(Passive)'),
(@SethrakMask, @Druid, '3050', 'Detect'),
(@SethrakMask, @Druid, '3365', 'Opening'),
(@SethrakMask, @Druid, '5176', 'Wrath'),
(@SethrakMask, @Druid, '5185', 'Healing Touch'),
(@SethrakMask, @Druid, '5419', 'Travel Form(Passive)'),
(@SethrakMask, @Druid, '5420', 'Tree of Life'),
(@SethrakMask, @Druid, '5421', 'Aquatic Form(Passive)'),
(@SethrakMask, @Druid, '6233', 'Closing'),
(@SethrakMask, @Druid, '6246', 'Closing'),
(@SethrakMask, @Druid, '6247', 'Opening'),
(@SethrakMask, @Druid, '6477', 'Opening'),
(@SethrakMask, @Druid, '6478', 'Opening'),
(@SethrakMask, @Druid, '6603', 'Attack'),
(@SethrakMask, @Druid, '7266', 'Duel'),
(@SethrakMask, @Druid, '7267', 'Grovel'),
(@SethrakMask, @Druid, '7355', 'Stuck'),
(@SethrakMask, @Druid, '8386', 'Attacking'),
(@SethrakMask, @Druid, '9077', 'Leather'),
(@SethrakMask, @Druid, '9078', 'Cloth'),
(@SethrakMask, @Druid, '9125', 'Generic'),
(@SethrakMask, @Druid, '9635', 'Dire Bear Form(Passive)'),
(@SethrakMask, @Druid, '21178', 'Bear Form(Passive2)'),
(@SethrakMask, @Druid, '21651', 'Opening'),
(@SethrakMask, @Druid, '21652', 'Closing'),
(@SethrakMask, @Druid, '22027', 'Remove Insignia'),
(@SethrakMask, @Druid, '22810', 'Opening - No Text'),
(@SethrakMask, @Druid, '24905', 'Moonkin Form(Passive)'),
(@SethrakMask, @Druid, '27764', 'Fetish'),
(@SethrakMask, @Druid, '33948', 'Flight Form(Passive)'),
(@SethrakMask, @Druid, '34123', 'Tree of Life(Passive)'),
(@SethrakMask, @Druid, '40121', 'Swift Flight Form(Passive)'),
(@SethrakMask, @Druid, '26979', 'Healing Touch'),
(@SethrakMask, @Druid, '26990', 'Mark of the Wild'),
(@SethrakMask, @Druid, '26985', 'Wrath'),
(@SethrakMask, @Druid, '26988', 'Moonfire'),
(@SethrakMask, @Druid, '26982', 'Rejuvenation'),
(@SethrakMask, @Druid, '26992', 'Thorns'),
(@SethrakMask, @Druid, '26989', 'Entangling Roots'),
(@SethrakMask, @Druid, '26998', 'Demoralizing Roar'),
(@SethrakMask, @Druid, '6795', 'Growl'),
(@SethrakMask, @Druid, '26996', 'Maul'),
(@SethrakMask, @Druid, '18960', 'Teleport: Moonglade'),
(@SethrakMask, @Druid, '9634', 'Dire Bear Form'),
(@SethrakMask, @Druid, '768', 'Cat Form'),
(@SethrakMask, @Druid, '783', 'Travel Form'),
(@SethrakMask, @Druid, '1066', 'Aquatic Form'),
(@SethrakMask, @Druid, '40120', 'Swift Flight Form'),
(@SethrakMask, @Druid, '5229', 'Enrage'),
(@SethrakMask, @Druid, '26980', 'Regrowth'),
(@SethrakMask, @Druid, '8983', 'Bash'),
(@SethrakMask, @Druid, '8946', 'Cure Poison'),
(@SethrakMask, @Druid, '26997', 'Swipe (Bear)'),
-- ('14', '1024', '26993', 'Faerie Fire'), -- Removed?
(@SethrakMask, @Druid, '18658', 'Hibernate'),
(@SethrakMask, @Druid, '27000', 'Claw'),
(@SethrakMask, @Druid, '9913', 'Prowl'),
(@SethrakMask, @Druid, '26994', 'Rebirth'),
(@SethrakMask, @Druid, '27008', 'Rip'),
(@SethrakMask, @Druid, '26986', 'Starfire'),
(@SethrakMask, @Druid, '27002', 'Shred'),
(@SethrakMask, @Druid, '26995', 'Soothe Animal'),
(@SethrakMask, @Druid, '27003', 'Rake'),
(@SethrakMask, @Druid, '2782', 'Remove Curse'),
(@SethrakMask, @Druid, '9846', 'Tigers Fury'),
(@SethrakMask, @Druid, '2893', 'Abolish Poison'),
(@SethrakMask, @Druid, '33357', 'Dash'),
(@SethrakMask, @Druid, '5209', 'Challenging Roar'),
(@SethrakMask, @Druid, '27004', 'Cower'),
(@SethrakMask, @Druid, '26983', 'Tranquility'),
(@SethrakMask, @Druid, '24248', 'Ferocious Bite'),
(@SethrakMask, @Druid, '27005', 'Ravage'),
(@SethrakMask, @Druid, '5225', 'Track Humanoids'),
-- ('14', '1024', '26999', 'Frenzied Regeneration'), -- Removed?
(@SethrakMask, @Druid, '27012', 'Hurricane'),
(@SethrakMask, @Druid, '27006', 'Pounce'),
(@SethrakMask, @Druid, '29166', 'Innervate'),
(@SethrakMask, @Druid, '22812', 'Bark Skin'),
(@SethrakMask, @Druid, '26991', 'Gift of the Wild'),
(@SethrakMask, @Druid, '22570', 'Maim'),
(@SethrakMask, @Druid, '33763', 'Lifebloom'),
(@SethrakMask, @Druid, '33745', 'Lacerate'),
(@SethrakMask, @Druid, '33786', 'Cyclone'),
(@SethrakMask, @Druid, '20719', 'Feline Grace');
