-- creaturedisplayinfo: 12 inserts, 0 updates, 0 deletes

-- New entries
/* Playable Races */
DELETE FROM `creaturedisplayinfo` WHERE `id` = 94217; -- male orc
INSERT INTO `creaturedisplayinfo` (`id`, `model_id`, `sound_id`, `extended_display_info_id`, `creature_model_scale`, `creature_model_alpha`, `texture_variation_1`, `texture_variation_2`, `texture_variation_3`, `portrait_texture_name`, `blood_level`, `blood_id`, `npc_sound_id`, `praticle_color_id`, `creature_geoset_data`, `obj_effect_package_id`) VALUES (94217, 51, 0, 45428, '1.0000000000000000', 255, '', '', '', '', 0, 0, 0, 0, 0, 0);
DELETE FROM `creaturedisplayinfo` WHERE `id` = 94218; -- female dwarf
INSERT INTO `creaturedisplayinfo` (`id`, `model_id`, `sound_id`, `extended_display_info_id`, `creature_model_scale`, `creature_model_alpha`, `texture_variation_1`, `texture_variation_2`, `texture_variation_3`, `portrait_texture_name`, `blood_level`, `blood_id`, `npc_sound_id`, `praticle_color_id`, `creature_geoset_data`, `obj_effect_package_id`) VALUES (94218, 54, 0, 45429, '1.0000000000000000', 255, '', '', '', '', 0, 0, 0, 0, 0, 0);
DELETE FROM `creaturedisplayinfo` WHERE `id` = 94219; -- female night elf
INSERT INTO `creaturedisplayinfo` (`id`, `model_id`, `sound_id`, `extended_display_info_id`, `creature_model_scale`, `creature_model_alpha`, `texture_variation_1`, `texture_variation_2`, `texture_variation_3`, `portrait_texture_name`, `blood_level`, `blood_id`, `npc_sound_id`, `praticle_color_id`, `creature_geoset_data`, `obj_effect_package_id`) VALUES (94219, 56, 0, 45430, '1.0000000000000000', 255, '', '', '', '', 0, 0, 0, 0, 0, 0);
DELETE FROM `creaturedisplayinfo` WHERE `id` = 94220; -- female troll
INSERT INTO `creaturedisplayinfo` (`id`, `model_id`, `sound_id`, `extended_display_info_id`, `creature_model_scale`, `creature_model_alpha`, `texture_variation_1`, `texture_variation_2`, `texture_variation_3`, `portrait_texture_name`, `blood_level`, `blood_id`, `npc_sound_id`, `praticle_color_id`, `creature_geoset_data`, `obj_effect_package_id`) VALUES (94220, 186, 0, 45431, '1.0000000000000000', 255, '', '', '', '', 0, 0, 0, 0, 0, 0);
DELETE FROM `creaturedisplayinfo` WHERE `id` = 94221; -- male draenei
INSERT INTO `creaturedisplayinfo` (`id`, `model_id`, `sound_id`, `extended_display_info_id`, `creature_model_scale`, `creature_model_alpha`, `texture_variation_1`, `texture_variation_2`, `texture_variation_3`, `portrait_texture_name`, `blood_level`, `blood_id`, `npc_sound_id`, `praticle_color_id`, `creature_geoset_data`, `obj_effect_package_id`) VALUES (94221, 2248, 0, 45432, '1.0000000000000000', 255, '', '', '', '', 0, 0, 0, 0, 0, 0);
DELETE FROM `creaturedisplayinfo` WHERE `id` = 94224; -- male undead
INSERT INTO `creaturedisplayinfo` (`id`, `model_id`, `sound_id`, `extended_display_info_id`, `creature_model_scale`, `creature_model_alpha`, `texture_variation_1`, `texture_variation_2`, `texture_variation_3`, `portrait_texture_name`, `blood_level`, `blood_id`, `npc_sound_id`, `praticle_color_id`, `creature_geoset_data`, `obj_effect_package_id`) VALUES (94224, 57, 0, 45435, '1.0000000000000000', 255, '', '', '', '', 0, 0, 0, 0, 0, 0);
DELETE FROM `creaturedisplayinfo` WHERE `id` = 94225; -- female undead
INSERT INTO `creaturedisplayinfo` (`id`, `model_id`, `sound_id`, `extended_display_info_id`, `creature_model_scale`, `creature_model_alpha`, `texture_variation_1`, `texture_variation_2`, `texture_variation_3`, `portrait_texture_name`, `blood_level`, `blood_id`, `npc_sound_id`, `praticle_color_id`, `creature_geoset_data`, `obj_effect_package_id`) VALUES (94225, 58, 0, 45436, '1.0000000000000000', 255, '', '', '', '', 0, 0, 0, 0, 0, 0);

/* NPC Races */
DELETE FROM `creaturedisplayinfo` WHERE `id` = 94228; -- female fel orc
INSERT INTO `creaturedisplayinfo` (`id`, `model_id`, `sound_id`, `extended_display_info_id`, `creature_model_scale`, `creature_model_alpha`, `texture_variation_1`, `texture_variation_2`, `texture_variation_3`, `portrait_texture_name`, `blood_level`, `blood_id`, `npc_sound_id`, `praticle_color_id`, `creature_geoset_data`, `obj_effect_package_id`) VALUES (94228, 2298, 0, 14488, '1.0000000000000000', 255, '', '', '', '', 1, 0, 0, 0, 0, 0);
DELETE FROM `creaturedisplayinfo` WHERE `id` = 94229; -- male naga
INSERT INTO `creaturedisplayinfo` (`id`, `model_id`, `sound_id`, `extended_display_info_id`, `creature_model_scale`, `creature_model_alpha`, `texture_variation_1`, `texture_variation_2`, `texture_variation_3`, `portrait_texture_name`, `blood_level`, `blood_id`, `npc_sound_id`, `praticle_color_id`, `creature_geoset_data`, `obj_effect_package_id`) VALUES (94229, 332, 0, 45441, '1.0000000000000000', 255, '', '', '', '', 1, 0, 0, 0, 0, 0);
DELETE FROM `creaturedisplayinfo` WHERE `id` = 94230; -- female naga
INSERT INTO `creaturedisplayinfo` (`id`, `model_id`, `sound_id`, `extended_display_info_id`, `creature_model_scale`, `creature_model_alpha`, `texture_variation_1`, `texture_variation_2`, `texture_variation_3`, `portrait_texture_name`, `blood_level`, `blood_id`, `npc_sound_id`, `praticle_color_id`, `creature_geoset_data`, `obj_effect_package_id`) VALUES (94230, 531, 0, 45442, '1.0000000000000000', 255, '', '', '', '', 1, 0, 0, 0, 0, 0);
DELETE FROM `creaturedisplayinfo` WHERE `id` = 94231; -- female broken
INSERT INTO `creaturedisplayinfo` (`id`, `model_id`, `sound_id`, `extended_display_info_id`, `creature_model_scale`, `creature_model_alpha`, `texture_variation_1`, `texture_variation_2`, `texture_variation_3`, `portrait_texture_name`, `blood_level`, `blood_id`, `npc_sound_id`, `praticle_color_id`, `creature_geoset_data`, `obj_effect_package_id`) VALUES (94231, 2368, 0, 45443, '1.0000000000000000', 255, '', '', '', '', 1, 0, 0, 0, 0, 0);
DELETE FROM `creaturedisplayinfo` WHERE `id` = 94232; -- male skeleton
INSERT INTO `creaturedisplayinfo` (`id`, `model_id`, `sound_id`, `extended_display_info_id`, `creature_model_scale`, `creature_model_alpha`, `texture_variation_1`, `texture_variation_2`, `texture_variation_3`, `portrait_texture_name`, `blood_level`, `blood_id`, `npc_sound_id`, `praticle_color_id`, `creature_geoset_data`, `obj_effect_package_id`) VALUES (94232, 2369, 0, 45444, '1.0000000000000000', 255, '', '', '', '', 1, 0, 0, 0, 0, 0);
DELETE FROM `creaturedisplayinfo` WHERE `id` = 94233; -- female skeleton
INSERT INTO `creaturedisplayinfo` (`id`, `model_id`, `sound_id`, `extended_display_info_id`, `creature_model_scale`, `creature_model_alpha`, `texture_variation_1`, `texture_variation_2`, `texture_variation_3`, `portrait_texture_name`, `blood_level`, `blood_id`, `npc_sound_id`, `praticle_color_id`, `creature_geoset_data`, `obj_effect_package_id`) VALUES (94233, 2370, 0, 45445, '1.0000000000000000', 255, '', '', '', '', 1, 0, 0, 0, 0, 0);
DELETE FROM `creaturedisplayinfo` WHERE `id` = 94234; -- male vrykul
INSERT INTO `creaturedisplayinfo` (`id`, `model_id`, `sound_id`, `extended_display_info_id`, `creature_model_scale`, `creature_model_alpha`, `texture_variation_1`, `texture_variation_2`, `texture_variation_3`, `portrait_texture_name`, `blood_level`, `blood_id`, `npc_sound_id`, `praticle_color_id`, `creature_geoset_data`, `obj_effect_package_id`) VALUES (94234, 2594, 0, 45446, '1.0000000000000000', 255, '', '', '', '', 1, 0, 0, 0, 0, 0);
DELETE FROM `creaturedisplayinfo` WHERE `id` = 94235; -- female vrykul
INSERT INTO `creaturedisplayinfo` (`id`, `model_id`, `sound_id`, `extended_display_info_id`, `creature_model_scale`, `creature_model_alpha`, `texture_variation_1`, `texture_variation_2`, `texture_variation_3`, `portrait_texture_name`, `blood_level`, `blood_id`, `npc_sound_id`, `praticle_color_id`, `creature_geoset_data`, `obj_effect_package_id`) VALUES (94235, 2595, 0, 45447, '1.0000000000000000', 255, '', '', '', '', 1, 0, 0, 0, 0, 0);
DELETE FROM `creaturedisplayinfo` WHERE `id` = 94236; -- male tuskarr
INSERT INTO `creaturedisplayinfo` (`id`, `model_id`, `sound_id`, `extended_display_info_id`, `creature_model_scale`, `creature_model_alpha`, `texture_variation_1`, `texture_variation_2`, `texture_variation_3`, `portrait_texture_name`, `blood_level`, `blood_id`, `npc_sound_id`, `praticle_color_id`, `creature_geoset_data`, `obj_effect_package_id`) VALUES (94236, 2604, 0, 45448, '1.0000000000000000', 255, '', '', '', '', 1, 0, 0, 0, 0, 0);
DELETE FROM `creaturedisplayinfo` WHERE `id` = 94237; -- female tuskarr
INSERT INTO `creaturedisplayinfo` (`id`, `model_id`, `sound_id`, `extended_display_info_id`, `creature_model_scale`, `creature_model_alpha`, `texture_variation_1`, `texture_variation_2`, `texture_variation_3`, `portrait_texture_name`, `blood_level`, `blood_id`, `npc_sound_id`, `praticle_color_id`, `creature_geoset_data`, `obj_effect_package_id`) VALUES (94237, 2605, 0, 45449, '1.0000000000000000', 255, '', '', '', '', 1, 0, 0, 0, 0, 0);
DELETE FROM `creaturedisplayinfo` WHERE `id` = 94238; -- male forest troll
INSERT INTO `creaturedisplayinfo` (`id`, `model_id`, `sound_id`, `extended_display_info_id`, `creature_model_scale`, `creature_model_alpha`, `texture_variation_1`, `texture_variation_2`, `texture_variation_3`, `portrait_texture_name`, `blood_level`, `blood_id`, `npc_sound_id`, `praticle_color_id`, `creature_geoset_data`, `obj_effect_package_id`) VALUES (94238, 2613, 0, 45450, '1.0000000000000000', 255, '', '', '', '', 1, 0, 0, 0, 0, 0);
DELETE FROM `creaturedisplayinfo` WHERE `id` = 94239; -- female forest troll (second male model placeholder)
INSERT INTO `creaturedisplayinfo` (`id`, `model_id`, `sound_id`, `extended_display_info_id`, `creature_model_scale`, `creature_model_alpha`, `texture_variation_1`, `texture_variation_2`, `texture_variation_3`, `portrait_texture_name`, `blood_level`, `blood_id`, `npc_sound_id`, `praticle_color_id`, `creature_geoset_data`, `obj_effect_package_id`) VALUES (94239, 2614, 0, 45451, '1.0000000000000000', 255, '', '', '', '', 1, 0, 0, 0, 0, 0);
DELETE FROM `creaturedisplayinfo` WHERE `id` = 94240; -- male taunka
INSERT INTO `creaturedisplayinfo` (`id`, `model_id`, `sound_id`, `extended_display_info_id`, `creature_model_scale`, `creature_model_alpha`, `texture_variation_1`, `texture_variation_2`, `texture_variation_3`, `portrait_texture_name`, `blood_level`, `blood_id`, `npc_sound_id`, `praticle_color_id`, `creature_geoset_data`, `obj_effect_package_id`) VALUES (94240, 2891, 0, 45452, '1.0000000000000000', 255, '', '', '', '', 1, 0, 0, 0, 0, 0);
DELETE FROM `creaturedisplayinfo` WHERE `id` = 94241; -- female taunka (second male model placeholder)
INSERT INTO `creaturedisplayinfo` (`id`, `model_id`, `sound_id`, `extended_display_info_id`, `creature_model_scale`, `creature_model_alpha`, `texture_variation_1`, `texture_variation_2`, `texture_variation_3`, `portrait_texture_name`, `blood_level`, `blood_id`, `npc_sound_id`, `praticle_color_id`, `creature_geoset_data`, `obj_effect_package_id`) VALUES (94241, 2892, 0, 45453, '1.0000000000000000', 255, '', '', '', '', 1, 0, 0, 0, 0, 0);
DELETE FROM `creaturedisplayinfo` WHERE `id` = 94242; -- male Northrend skeleton
INSERT INTO `creaturedisplayinfo` (`id`, `model_id`, `sound_id`, `extended_display_info_id`, `creature_model_scale`, `creature_model_alpha`, `texture_variation_1`, `texture_variation_2`, `texture_variation_3`, `portrait_texture_name`, `blood_level`, `blood_id`, `npc_sound_id`, `praticle_color_id`, `creature_geoset_data`, `obj_effect_package_id`) VALUES (94242, 2940, 0, 45454, '1.0000000000000000', 255, '', '', '', '', 1, 0, 0, 0, 0, 0);
DELETE FROM `creaturedisplayinfo` WHERE `id` = 94243; -- female Northrend skeleton (second male model placeholder)
INSERT INTO `creaturedisplayinfo` (`id`, `model_id`, `sound_id`, `extended_display_info_id`, `creature_model_scale`, `creature_model_alpha`, `texture_variation_1`, `texture_variation_2`, `texture_variation_3`, `portrait_texture_name`, `blood_level`, `blood_id`, `npc_sound_id`, `praticle_color_id`, `creature_geoset_data`, `obj_effect_package_id`) VALUES (94243, 2941, 0, 45455, '1.0000000000000000', 255, '', '', '', '', 1, 0, 0, 0, 0, 0);
DELETE FROM `creaturedisplayinfo` WHERE `id` = 94244; -- male ice troll
INSERT INTO `creaturedisplayinfo` (`id`, `model_id`, `sound_id`, `extended_display_info_id`, `creature_model_scale`, `creature_model_alpha`, `texture_variation_1`, `texture_variation_2`, `texture_variation_3`, `portrait_texture_name`, `blood_level`, `blood_id`, `npc_sound_id`, `praticle_color_id`, `creature_geoset_data`, `obj_effect_package_id`) VALUES (94244, 2942, 0, 45456, '1.0000000000000000', 255, '', '', '', '', 1, 0, 0, 0, 0, 0);
DELETE FROM `creaturedisplayinfo` WHERE `id` = 94245; -- female ice troll (second male model placeholder)
INSERT INTO `creaturedisplayinfo` (`id`, `model_id`, `sound_id`, `extended_display_info_id`, `creature_model_scale`, `creature_model_alpha`, `texture_variation_1`, `texture_variation_2`, `texture_variation_3`, `portrait_texture_name`, `blood_level`, `blood_id`, `npc_sound_id`, `praticle_color_id`, `creature_geoset_data`, `obj_effect_package_id`) VALUES (94245, 2943, 0, 45457, '1.0000000000000000', 255, '', '', '', '', 1, 0, 0, 0, 0, 0);
