/*
 * mod-azeroth-plex loader
 *
 * The name below is generated by the core's module loader from the module directory name
 * ("mod-azeroth-plex" -> "mod_azeroth_plex" -> "Addmod_azeroth_plexScripts"), so it must not change.
 */

void AddSC_mod_azeroth_plex();

void Addmod_azeroth_plexScripts()
{
    AddSC_mod_azeroth_plex();
}
