"""Stable six-byte Highmountain codec shared by the native helper and server validator."""

import json
import highmountain_race_pack as h

# Packet appearance order plus one explicit extension byte. Never reorder an installed codec.
GROUPS = {
    "male": (("Skin Color", "Eye Color"), ("Face", "Hair", "Nose Piercing"),
             ("Horn Style", "Beard", "Horn Markings"), ("Foremane", "Horn Decoration", "Body Paint"),
             ("Horn Wraps", "Tail Decoration", "Horn Color", "Eyesight"),
             ("Body Paint Color", "Headdress", "Tail", "Feather", "Eye Style")),
    "female": (("Skin Color", "Eye Color"), ("Face", "Body Paint", "Hair Decoration", "Nose Piercing"),
               ("Hair", "Horn Style", "Body Paint Color"), ("Foremane", "Earrings", "Tail Decoration"),
               ("Horn Color", "Necklace", "Eyesight", "Headdress"),
               ("Eye Style", "Horn Markings", "Feather", "Horn Wraps", "Horn Decoration", "Tail")),
}


def codec(audit=None):
    audit = audit or h.audit()
    result = {}
    choice_indices = {}
    for sex, profile in audit["sexes"].items():
        options = profile["options"]
        indices = {o["label"]: i for i, o in enumerate(options)}
        descriptors = [None] * len(options)
        capacities = []
        for field, labels in enumerate(GROUPS[sex]):
            factor = 1
            for label in labels:
                index = indices[label]
                count = len(options[index]["choices"])
                descriptors[index] = (field, count, factor)
                factor *= count
            if factor > 256:
                raise ValueError(f"{sex} field {field} exceeds the byte capacity")
            capacities.append(factor)
        for index, option in enumerate(options):
            if descriptors[index] is None:
                if len(option["choices"]) != 1:
                    raise ValueError(f"Unencoded customization: {sex} {option['label']}")
                descriptors[index] = (5, 1, 1)
            for value, choice in enumerate(option["choices"]):
                choice_indices[choice["ID"]] = (sex, index, value)
        result[sex] = {"options": options, "descriptors": descriptors, "capacities": capacities,
                       "requirements": []}
    requirements = {}
    for row in audit["requirement_choices"]:
        sex, index, value = choice_indices[row["ChrCustomizationChoiceID"]]
        requirements.setdefault(row["ChrCustomizationReqID"], {}).setdefault((sex, index), 0)
        requirements[row["ChrCustomizationReqID"]][sex, index] |= 1 << value
    for sex, profile in result.items():
        for index, option in enumerate(profile["options"]):
            for value, choice in enumerate(option["choices"]):
                required_choices = requirements.get(choice["ChrCustomizationReqID"], {})
                for (required_sex, required_index), mask in required_choices.items():
                    if required_sex != sex:
                        raise ValueError("Cross-gender customization requirement")
                    profile["requirements"].append((index, value, required_index, mask))
    return result


def decode(profile, fields):
    if len(fields) != 6 or any(not 0 <= value < cap for value, cap in zip(fields, profile["capacities"])):
        raise ValueError("Invalid Highmountain appearance byte")
    return [(fields[field] // factor) % count for field, count, factor in profile["descriptors"]]


def valid(profile, fields):
    try:
        choices = decode(profile, fields)
    except ValueError:
        return False
    return all(choices[option] != value or mask & (1 << choices[required])
               for option, value, required, mask in profile["requirements"])


def encode(profile, choices):
    fields = [0] * 6
    for value, (field, count, factor) in zip(choices, profile["descriptors"], strict=True):
        if not 0 <= value < count:
            raise ValueError("Invalid Highmountain choice")
        if count > 1:
            fields[field] += value * factor
    if not valid(profile, fields):
        raise ValueError("Incompatible Highmountain choices")
    return fields


def generate():
    profiles = codec()
    lines = ["// Generated by tools/highmountain_appearance.py from the pinned Highmountain discovery.",
             "#ifndef ESTERIA_HIGHMOUNTAIN_APPEARANCE_H", "#define ESTERIA_HIGHMOUNTAIN_APPEARANCE_H", "",
             "#include <array>", "#include <cstdint>", "", "namespace HighmountainAppearance", "{",
             "    struct Option", "    {", "        std::uint16_t field;", "        std::uint16_t count;",
             "        std::uint16_t factor;", "    };", "", "    struct Requirement", "    {",
             "        std::uint16_t option;", "        std::uint16_t value;", "        std::uint16_t required;",
             "        std::uint32_t mask;", "    };", ""]
    for sex, profile in profiles.items():
        title = sex.title()
        lines.append(f"    inline constexpr std::array<Option, {len(profile['options'])}> {title}Options = {{{{")
        for option, (field, count, factor) in zip(profile["options"], profile["descriptors"]):
            lines.append(f"        {{{field}, {count}, {factor}}}, // {option['label']}")
        lines.extend(["    }};", "", f"    inline constexpr std::array<char const*, {len(profile['options'])}> "
                      f"{title}Labels = {{"])
        lines.extend("        " + json.dumps(o["label"]) + "," for o in profile["options"])
        lines.extend(["    };", "", f"    inline constexpr std::array<std::uint16_t, 6> {title}Capacities = "
                      "{" + ", ".join(map(str, profile["capacities"])) + "};", "",
                      f"    inline constexpr std::array<Requirement, {len(profile['requirements'])}> "
                      f"{title}Requirements = {{{{"])
        lines.extend("        {" + ", ".join(map(str, row)) + "}," for row in profile["requirements"])
        lines.extend(["    }};", ""])
    lines.extend('''    template<class Options, class Requirements>
    constexpr bool ValidateProfile(std::array<std::uint8_t, 6> const& fields, Options const& options,
        Requirements const& requirements, std::array<std::uint16_t, 6> const& capacities)
    {
        for (unsigned i = 0; i < fields.size(); ++i)
            if (fields[i] >= capacities[i])
                return false;
        auto choice = [&](unsigned index)
        {
            Option const& option = options[index];
            return (fields[option.field] / option.factor) % option.count;
        };
        for (Requirement const& requirement : requirements)
            if (choice(requirement.option) == requirement.value
                && !(requirement.mask & (1u << choice(requirement.required))))
                return false;
        return true;
    }

    constexpr bool Validate(unsigned gender, std::array<std::uint8_t, 6> const& fields)
    {
        if (gender == 0)
            return ValidateProfile(fields, MaleOptions, MaleRequirements, MaleCapacities);
        if (gender == 1)
            return ValidateProfile(fields, FemaleOptions, FemaleRequirements, FemaleCapacities);
        return false;
    }
}

#endif
'''.splitlines())
    target = h.p.ROOT / "src/server/shared/HighmountainAppearance.h"
    target.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    h.save(h.ROOT / "integration/codec.json", profiles)
    print(target)


if __name__ == "__main__":
    generate()
