-- chrraces: 1 inserts, 1 updates, 0 deletes

-- Changed values
DELETE FROM `chrraces` WHERE ID = @Goblin;
INSERT INTO `chrraces` (`id`, `flags`, `faction_id`, `exploration_sound_id`, `male_display_id`, `female_display_id`, `client_prefix`, `base_language`, `creature_type`, `res_sickness_spell_id`, `splash_sound_id`, `client_filestring`, `cinematic_sequence_id`, `alliance`, `name_neutral_enus`, `name_neutral_kokr`, `name_neutral_frfr`, `name_neutral_dede`, `name_neutral_zhcn`, `name_neutral_zhtw`, `name_neutral_eses`, `name_neutral_esmx`, `name_neutral_ruru`, `name_neutral_jajp`, `name_neutral_ptpt`, `name_neutral_itit`, `name_neutral_unused_1`, `name_neutral_unused_2`, `name_neutral_unused_3`, `name_neutral_unused_4`, `name_neutral_flags`, `name_female_enus`, `name_female_kokr`, `name_female_frfr`, `name_female_dede`, `name_female_zhcn`, `name_female_zhtw`, `name_female_eses`, `name_female_esmx`, `name_female_ruru`, `name_female_jajp`, `name_female_ptpt`, `name_female_itit`, `name_female_unused_1`, `name_female_unused_2`, `name_female_unused_3`, `name_female_unused_4`, `name_female_flags`, `name_male_enus`, `name_male_kokr`, `name_male_frfr`, `name_male_dede`, `name_male_zhcn`, `name_male_zhtw`, `name_male_eses`, `name_male_esmx`, `name_male_ruru`, `name_male_jajp`, `name_male_ptpt`, `name_male_itit`, `name_male_unused_1`, `name_male_unused_2`, `name_male_unused_3`, `name_male_unused_4`, `name_male_flags`, `facial_hair_customization_1`, `facial_hair_customization_2`, `hair_customization`, `required_expansion`) VALUES (@Goblin, 4, 2, 4141, 6894, 6895, 'Go', 1, 7, 15007, 1096, 'Goblin', 21, 1, 'Goblin', '고블린', 'Gobelin', 'Goblin', '地精', '', 'Goblin', 'Goblin', 'Гоблин', '', '', '', '', '', '', '', 16712190, '', '', 'Gobeline', '', '', '', 'Goblin', 'Goblin', '', '', '', '', '', '', '', '', 16712172, '', '', 'Gobelin', 'Goblin', '', '', 'Goblin', 'Goblin', 'Гоблин', '', '', '', '', '', '', '', 16712172, 'PIERCINGS', 'PIERCINGS', 'NORMAL', 0);


-- New values
DELETE FROM `chrraces` WHERE ID = @Worgen;
INSERT INTO `chrraces` (`id`, `flags`, `faction_id`, `exploration_sound_id`, `male_display_id`, `female_display_id`, `client_prefix`, `base_language`, `creature_type`, `res_sickness_spell_id`, `splash_sound_id`, `client_filestring`, `cinematic_sequence_id`, `alliance`, `name_neutral_enus`, `name_neutral_kokr`, `name_neutral_frfr`, `name_neutral_dede`, `name_neutral_zhcn`, `name_neutral_zhtw`, `name_neutral_eses`, `name_neutral_esmx`, `name_neutral_ruru`, `name_neutral_jajp`, `name_neutral_ptpt`, `name_neutral_itit`, `name_neutral_unused_1`, `name_neutral_unused_2`, `name_neutral_unused_3`, `name_neutral_unused_4`, `name_neutral_flags`, `name_female_enus`, `name_female_kokr`, `name_female_frfr`, `name_female_dede`, `name_female_zhcn`, `name_female_zhtw`, `name_female_eses`, `name_female_esmx`, `name_female_ruru`, `name_female_jajp`, `name_female_ptpt`, `name_female_itit`, `name_female_unused_1`, `name_female_unused_2`, `name_female_unused_3`, `name_female_unused_4`, `name_female_flags`, `name_male_enus`, `name_male_kokr`, `name_male_frfr`, `name_male_dede`, `name_male_zhcn`, `name_male_zhtw`, `name_male_eses`, `name_male_esmx`, `name_male_ruru`, `name_male_jajp`, `name_male_ptpt`, `name_male_itit`, `name_male_unused_1`, `name_male_unused_2`, `name_male_unused_3`, `name_male_unused_4`, `name_male_flags`, `facial_hair_customization_1`, `facial_hair_customization_2`, `hair_customization`, `required_expansion`) VALUES (@Worgen, 6, 1, 4143, 29422, 29423, 'Wo', 7, 7, 15007, 1096, 'Worgen', 61, 0, 'Worgen', '늑대인간', 'Worgen', 'Worgen', '狼人', 'Huargen', 'Huargen', 'Ворген', '', '', '', '', '', '', '', '', 16712190, '', '', 'Worgen', '', '', '', 'Huargen', 'Huargen', '', '', '', '', '', '', '', '', 16712172, '', '', 'Worgen', 'Worgen', '', '', 'Huargen', 'Huargen', 'Ворген', '', '', '', '', '', '', '', 16712172, 'FEATURES', 'EARS', 'NORMAL', 0);
