-- New entries
DELETE FROM `creaturedisplayinfo` WHERE `id` = 92600;
INSERT INTO `creaturedisplayinfo` (`id`, `model_id`, `sound_id`, `extended_display_info_id`, `creature_model_scale`, `creature_model_alpha`, `texture_variation_1`, `texture_variation_2`, `texture_variation_3`, `portrait_texture_name`, `blood_level`, `blood_id`, `npc_sound_id`, `praticle_color_id`, `creature_geoset_data`, `obj_effect_package_id`) VALUES (92600, 3141, 0, 62100, '1.0000000000000000', 255, '', '', '', '', 0, 0, 0, 0, 0, 0);
DELETE FROM `creaturedisplayinfo` WHERE `id` = 92601;
INSERT INTO `creaturedisplayinfo` (`id`, `model_id`, `sound_id`, `extended_display_info_id`, `creature_model_scale`, `creature_model_alpha`, `texture_variation_1`, `texture_variation_2`, `texture_variation_3`, `portrait_texture_name`, `blood_level`, `blood_id`, `npc_sound_id`, `praticle_color_id`, `creature_geoset_data`, `obj_effect_package_id`) VALUES (92601, 3141, 0, 62101, '1.0000000000000000', 255, '', '', '', '', 0, 0, 0, 0, 0, 0);
DELETE FROM `creaturedisplayinfo` WHERE `id` = 92602;
INSERT INTO `creaturedisplayinfo` (`id`, `model_id`, `sound_id`, `extended_display_info_id`, `creature_model_scale`, `creature_model_alpha`, `texture_variation_1`, `texture_variation_2`, `texture_variation_3`, `portrait_texture_name`, `blood_level`, `blood_id`, `npc_sound_id`, `praticle_color_id`, `creature_geoset_data`, `obj_effect_package_id`) VALUES (92602, 3142, 0, 62102, '1.0000000000000000', 255, '', '', '', '', 0, 0, 0, 0, 0, 0);
DELETE FROM `creaturedisplayinfo` WHERE `id` = 92603;
INSERT INTO `creaturedisplayinfo` (`id`, `model_id`, `sound_id`, `extended_display_info_id`, `creature_model_scale`, `creature_model_alpha`, `texture_variation_1`, `texture_variation_2`, `texture_variation_3`, `portrait_texture_name`, `blood_level`, `blood_id`, `npc_sound_id`, `praticle_color_id`, `creature_geoset_data`, `obj_effect_package_id`) VALUES (92603, 3142, 0, 62103, '1.0000000000000000', 255, '', '', '', '', 0, 0, 0, 0, 0, 0);
DELETE FROM `creaturedisplayinfo` WHERE `id` = 92604;
INSERT INTO `creaturedisplayinfo` (`id`, `model_id`, `sound_id`, `extended_display_info_id`, `creature_model_scale`, `creature_model_alpha`, `texture_variation_1`, `texture_variation_2`, `texture_variation_3`, `portrait_texture_name`, `blood_level`, `blood_id`, `npc_sound_id`, `praticle_color_id`, `creature_geoset_data`, `obj_effect_package_id`) VALUES (92604, 3142, 0, 62104, '1.0000000000000000', 255, '', '', '', '', 0, 0, 0, 0, 0, 0);
DELETE FROM `creaturedisplayinfo` WHERE `id` = 92605;
INSERT INTO `creaturedisplayinfo` (`id`, `model_id`, `sound_id`, `extended_display_info_id`, `creature_model_scale`, `creature_model_alpha`, `texture_variation_1`, `texture_variation_2`, `texture_variation_3`, `portrait_texture_name`, `blood_level`, `blood_id`, `npc_sound_id`, `praticle_color_id`, `creature_geoset_data`, `obj_effect_package_id`) VALUES (92605, 3141, 0, 62105, '1.0000000000000000', 255, '', '', '', '', 0, 0, 0, 0, 0, 0);

-- Worgen racial support
DELETE FROM `creaturedisplayinfo` WHERE `id` = 94133; -- male running wild
INSERT INTO `creaturedisplayinfo` (`id`, `model_id`, `sound_id`, `extended_display_info_id`, `creature_model_scale`, `creature_model_alpha`, `texture_variation_1`, `texture_variation_2`, `texture_variation_3`, `portrait_texture_name`, `blood_level`, `blood_id`, `npc_sound_id`, `praticle_color_id`, `creature_geoset_data`, `obj_effect_package_id`) VALUES (94133, 3626, 0, 45424, 1, 255, '', '', '', '', 3, 0, 0, 0, 0, 0);
DELETE FROM `creaturedisplayinfo` WHERE `id` = 94134; -- female running wild
INSERT INTO `creaturedisplayinfo` (`id`, `model_id`, `sound_id`, `extended_display_info_id`, `creature_model_scale`, `creature_model_alpha`, `texture_variation_1`, `texture_variation_2`, `texture_variation_3`, `portrait_texture_name`, `blood_level`, `blood_id`, `npc_sound_id`, `praticle_color_id`, `creature_geoset_data`, `obj_effect_package_id`) VALUES (94134, 3627, 0, 45425, 1, 255, '', '', '', '', 3, 0, 0, 0, 0, 0);
DELETE FROM `creaturedisplayinfo` WHERE `id` = 94135; -- male Gilnean
INSERT INTO `creaturedisplayinfo` (`id`, `model_id`, `sound_id`, `extended_display_info_id`, `creature_model_scale`, `creature_model_alpha`, `texture_variation_1`, `texture_variation_2`, `texture_variation_3`, `portrait_texture_name`, `blood_level`, `blood_id`, `npc_sound_id`, `praticle_color_id`, `creature_geoset_data`, `obj_effect_package_id`) VALUES (94135, 3628, 0, 13749, 1, 255, '', '', '', '', 1, 0, 0, 0, 0, 0);
DELETE FROM `creaturedisplayinfo` WHERE `id` = 94136; -- female Gilnean
INSERT INTO `creaturedisplayinfo` (`id`, `model_id`, `sound_id`, `extended_display_info_id`, `creature_model_scale`, `creature_model_alpha`, `texture_variation_1`, `texture_variation_2`, `texture_variation_3`, `portrait_texture_name`, `blood_level`, `blood_id`, `npc_sound_id`, `praticle_color_id`, `creature_geoset_data`, `obj_effect_package_id`) VALUES (94136, 3629, 0, 13750, 1, 255, '', '', '', '', 1, 0, 0, 0, 0, 0);

-- Cataclysm druid forms
DELETE FROM `creaturedisplayinfo` WHERE `id` = 33650;
INSERT INTO `creaturedisplayinfo` (`id`, `model_id`, `sound_id`, `extended_display_info_id`, `creature_model_scale`, `creature_model_alpha`, `texture_variation_1`, `texture_variation_2`, `texture_variation_3`, `portrait_texture_name`, `blood_level`, `blood_id`, `npc_sound_id`, `praticle_color_id`, `creature_geoset_data`, `obj_effect_package_id`) VALUES (33650, 3516, 0, 0, '1.0000000000000000', 255, 'DruidBearWorgen', '', '', '', 1, 0, 0, 0, 0, 0);
DELETE FROM `creaturedisplayinfo` WHERE `id` = 33651;
INSERT INTO `creaturedisplayinfo` (`id`, `model_id`, `sound_id`, `extended_display_info_id`, `creature_model_scale`, `creature_model_alpha`, `texture_variation_1`, `texture_variation_2`, `texture_variation_3`, `portrait_texture_name`, `blood_level`, `blood_id`, `npc_sound_id`, `praticle_color_id`, `creature_geoset_data`, `obj_effect_package_id`) VALUES (33651, 3516, 0, 0, '1.0000000000000000', 255, 'DruidBearWorgenBlack', '', '', '', 1, 0, 0, 0, 0, 0);
DELETE FROM `creaturedisplayinfo` WHERE `id` = 33652;
INSERT INTO `creaturedisplayinfo` (`id`, `model_id`, `sound_id`, `extended_display_info_id`, `creature_model_scale`, `creature_model_alpha`, `texture_variation_1`, `texture_variation_2`, `texture_variation_3`, `portrait_texture_name`, `blood_level`, `blood_id`, `npc_sound_id`, `praticle_color_id`, `creature_geoset_data`, `obj_effect_package_id`) VALUES (33652, 3516, 0, 0, '1.0000000000000000', 255, 'DruidBearWorgenBrown', '', '', '', 1, 0, 0, 0, 0, 0);
DELETE FROM `creaturedisplayinfo` WHERE `id` = 33653;
INSERT INTO `creaturedisplayinfo` (`id`, `model_id`, `sound_id`, `extended_display_info_id`, `creature_model_scale`, `creature_model_alpha`, `texture_variation_1`, `texture_variation_2`, `texture_variation_3`, `portrait_texture_name`, `blood_level`, `blood_id`, `npc_sound_id`, `praticle_color_id`, `creature_geoset_data`, `obj_effect_package_id`) VALUES (33653, 3516, 0, 0, '1.0000000000000000', 255, 'DruidBearWorgenTan', '', '', '', 1, 0, 0, 0, 0, 0);
DELETE FROM `creaturedisplayinfo` WHERE `id` = 33654;
INSERT INTO `creaturedisplayinfo` (`id`, `model_id`, `sound_id`, `extended_display_info_id`, `creature_model_scale`, `creature_model_alpha`, `texture_variation_1`, `texture_variation_2`, `texture_variation_3`, `portrait_texture_name`, `blood_level`, `blood_id`, `npc_sound_id`, `praticle_color_id`, `creature_geoset_data`, `obj_effect_package_id`) VALUES (33654, 3516, 0, 0, '1.0000000000000000', 255, 'DruidBearWorgenWhite', '', '', '', 1, 0, 0, 0, 0, 0);
DELETE FROM `creaturedisplayinfo` WHERE `id` = 33655;
INSERT INTO `creaturedisplayinfo` (`id`, `model_id`, `sound_id`, `extended_display_info_id`, `creature_model_scale`, `creature_model_alpha`, `texture_variation_1`, `texture_variation_2`, `texture_variation_3`, `portrait_texture_name`, `blood_level`, `blood_id`, `npc_sound_id`, `praticle_color_id`, `creature_geoset_data`, `obj_effect_package_id`) VALUES (33655, 3517, 0, 0, '1.0000000000000000', 255, 'DruidBearTrollBlue', '', '', '', 1, 0, 0, 0, 0, 0);
DELETE FROM `creaturedisplayinfo` WHERE `id` = 33656;
INSERT INTO `creaturedisplayinfo` (`id`, `model_id`, `sound_id`, `extended_display_info_id`, `creature_model_scale`, `creature_model_alpha`, `texture_variation_1`, `texture_variation_2`, `texture_variation_3`, `portrait_texture_name`, `blood_level`, `blood_id`, `npc_sound_id`, `praticle_color_id`, `creature_geoset_data`, `obj_effect_package_id`) VALUES (33656, 3517, 0, 0, '1.0000000000000000', 255, 'DruidBearTrollPurple', '', '', '', 1, 0, 0, 0, 0, 0);
DELETE FROM `creaturedisplayinfo` WHERE `id` = 33657;
INSERT INTO `creaturedisplayinfo` (`id`, `model_id`, `sound_id`, `extended_display_info_id`, `creature_model_scale`, `creature_model_alpha`, `texture_variation_1`, `texture_variation_2`, `texture_variation_3`, `portrait_texture_name`, `blood_level`, `blood_id`, `npc_sound_id`, `praticle_color_id`, `creature_geoset_data`, `obj_effect_package_id`) VALUES (33657, 3517, 0, 0, '1.0000000000000000', 255, 'DruidBearTrollRed', '', '', '', 1, 0, 0, 0, 0, 0);
DELETE FROM `creaturedisplayinfo` WHERE `id` = 33658;
INSERT INTO `creaturedisplayinfo` (`id`, `model_id`, `sound_id`, `extended_display_info_id`, `creature_model_scale`, `creature_model_alpha`, `texture_variation_1`, `texture_variation_2`, `texture_variation_3`, `portrait_texture_name`, `blood_level`, `blood_id`, `npc_sound_id`, `praticle_color_id`, `creature_geoset_data`, `obj_effect_package_id`) VALUES (33658, 3517, 0, 0, '1.0000000000000000', 255, 'DruidBearTrollWhite', '', '', '', 1, 0, 0, 0, 0, 0);
DELETE FROM `creaturedisplayinfo` WHERE `id` = 33659;
INSERT INTO `creaturedisplayinfo` (`id`, `model_id`, `sound_id`, `extended_display_info_id`, `creature_model_scale`, `creature_model_alpha`, `texture_variation_1`, `texture_variation_2`, `texture_variation_3`, `portrait_texture_name`, `blood_level`, `blood_id`, `npc_sound_id`, `praticle_color_id`, `creature_geoset_data`, `obj_effect_package_id`) VALUES (33659, 3517, 0, 0, '1.0000000000000000', 255, 'DruidBearTrollYellow', '', '', '', 1, 0, 0, 0, 0, 0);
DELETE FROM `creaturedisplayinfo` WHERE `id` = 33660;
INSERT INTO `creaturedisplayinfo` (`id`, `model_id`, `sound_id`, `extended_display_info_id`, `creature_model_scale`, `creature_model_alpha`, `texture_variation_1`, `texture_variation_2`, `texture_variation_3`, `portrait_texture_name`, `blood_level`, `blood_id`, `npc_sound_id`, `praticle_color_id`, `creature_geoset_data`, `obj_effect_package_id`) VALUES (33660, 3518, 0, 0, '1.0000000000000000', 255, 'DruidCatSkinWorgen', '', '', '', -1, 0, 0, 0, 0, 0);
DELETE FROM `creaturedisplayinfo` WHERE `id` = 33661;
INSERT INTO `creaturedisplayinfo` (`id`, `model_id`, `sound_id`, `extended_display_info_id`, `creature_model_scale`, `creature_model_alpha`, `texture_variation_1`, `texture_variation_2`, `texture_variation_3`, `portrait_texture_name`, `blood_level`, `blood_id`, `npc_sound_id`, `praticle_color_id`, `creature_geoset_data`, `obj_effect_package_id`) VALUES (33661, 3518, 0, 0, '1.0000000000000000', 255, 'DruidCatSkinWorgenBlack', '', '', '', -1, 0, 0, 0, 0, 0);
DELETE FROM `creaturedisplayinfo` WHERE `id` = 33662;
INSERT INTO `creaturedisplayinfo` (`id`, `model_id`, `sound_id`, `extended_display_info_id`, `creature_model_scale`, `creature_model_alpha`, `texture_variation_1`, `texture_variation_2`, `texture_variation_3`, `portrait_texture_name`, `blood_level`, `blood_id`, `npc_sound_id`, `praticle_color_id`, `creature_geoset_data`, `obj_effect_package_id`) VALUES (33662, 3518, 0, 0, '1.0000000000000000', 255, 'DruidCatSkinWorgenBrown', '', '', '', -1, 0, 0, 0, 0, 0);
DELETE FROM `creaturedisplayinfo` WHERE `id` = 33663;
INSERT INTO `creaturedisplayinfo` (`id`, `model_id`, `sound_id`, `extended_display_info_id`, `creature_model_scale`, `creature_model_alpha`, `texture_variation_1`, `texture_variation_2`, `texture_variation_3`, `portrait_texture_name`, `blood_level`, `blood_id`, `npc_sound_id`, `praticle_color_id`, `creature_geoset_data`, `obj_effect_package_id`) VALUES (33663, 3518, 0, 0, '1.0000000000000000', 255, 'DruidCatSkinWorgenWhite', '', '', '', -1, 0, 0, 0, 0, 0);
DELETE FROM `creaturedisplayinfo` WHERE `id` = 33664;
INSERT INTO `creaturedisplayinfo` (`id`, `model_id`, `sound_id`, `extended_display_info_id`, `creature_model_scale`, `creature_model_alpha`, `texture_variation_1`, `texture_variation_2`, `texture_variation_3`, `portrait_texture_name`, `blood_level`, `blood_id`, `npc_sound_id`, `praticle_color_id`, `creature_geoset_data`, `obj_effect_package_id`) VALUES (33664, 3518, 0, 0, '1.0000000000000000', 255, 'DruidCatSkinWorgenYellow', '', '', '', -1, 0, 0, 0, 0, 0);
DELETE FROM `creaturedisplayinfo` WHERE `id` = 33665;
INSERT INTO `creaturedisplayinfo` (`id`, `model_id`, `sound_id`, `extended_display_info_id`, `creature_model_scale`, `creature_model_alpha`, `texture_variation_1`, `texture_variation_2`, `texture_variation_3`, `portrait_texture_name`, `blood_level`, `blood_id`, `npc_sound_id`, `praticle_color_id`, `creature_geoset_data`, `obj_effect_package_id`) VALUES (33665, 3519, 0, 0, '1.0000000000000000', 255, 'DruidCatTrollSkinBlack', '', '', '', -1, 0, 0, 0, 0, 0);
DELETE FROM `creaturedisplayinfo` WHERE `id` = 33666;
INSERT INTO `creaturedisplayinfo` (`id`, `model_id`, `sound_id`, `extended_display_info_id`, `creature_model_scale`, `creature_model_alpha`, `texture_variation_1`, `texture_variation_2`, `texture_variation_3`, `portrait_texture_name`, `blood_level`, `blood_id`, `npc_sound_id`, `praticle_color_id`, `creature_geoset_data`, `obj_effect_package_id`) VALUES (33666, 3519, 0, 0, '1.0000000000000000', 255, 'DruidCatTrollSkinBlue', '', '', '', -1, 0, 0, 0, 0, 0);
DELETE FROM `creaturedisplayinfo` WHERE `id` = 33667;
INSERT INTO `creaturedisplayinfo` (`id`, `model_id`, `sound_id`, `extended_display_info_id`, `creature_model_scale`, `creature_model_alpha`, `texture_variation_1`, `texture_variation_2`, `texture_variation_3`, `portrait_texture_name`, `blood_level`, `blood_id`, `npc_sound_id`, `praticle_color_id`, `creature_geoset_data`, `obj_effect_package_id`) VALUES (33667, 3519, 0, 0, '1.0000000000000000', 255, 'DruidCatTrollSkinGreen', '', '', '', -1, 0, 0, 0, 0, 0);
DELETE FROM `creaturedisplayinfo` WHERE `id` = 33668;
INSERT INTO `creaturedisplayinfo` (`id`, `model_id`, `sound_id`, `extended_display_info_id`, `creature_model_scale`, `creature_model_alpha`, `texture_variation_1`, `texture_variation_2`, `texture_variation_3`, `portrait_texture_name`, `blood_level`, `blood_id`, `npc_sound_id`, `praticle_color_id`, `creature_geoset_data`, `obj_effect_package_id`) VALUES (33668, 3519, 0, 0, '1.0000000000000000', 255, 'DruidCatTrollSkinRed', '', '', '', -1, 0, 0, 0, 0, 0);
DELETE FROM `creaturedisplayinfo` WHERE `id` = 33669;
INSERT INTO `creaturedisplayinfo` (`id`, `model_id`, `sound_id`, `extended_display_info_id`, `creature_model_scale`, `creature_model_alpha`, `texture_variation_1`, `texture_variation_2`, `texture_variation_3`, `portrait_texture_name`, `blood_level`, `blood_id`, `npc_sound_id`, `praticle_color_id`, `creature_geoset_data`, `obj_effect_package_id`) VALUES (33669, 3519, 0, 0, '1.0000000000000000', 255, 'DruidCatTrollSkinWhite', '', '', '', -1, 0, 0, 0, 0, 0);