-- Gilnean race support

DELETE FROM `namegen` WHERE `id` = 19100;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19100, 'Agamand', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19101;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19101, 'Andromath', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19102;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19102, 'Antonidas', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19103;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19103, 'Fordred', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19104;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19104, 'Nielas', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19105;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19105, 'Nielas', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19106;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19106, 'Arius', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19107;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19107, 'Arugal', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19108;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19108, 'Sten', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19109;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19109, 'Ballador', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19110;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19110, 'Barthilas', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19111;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19111, 'Aedelas', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19112;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19112, 'Conjurus', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19113;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19113, 'Rex', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19114;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19114, 'Danath', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19115;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19115, 'Saidin', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19116;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19116, 'Dalar', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19117;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19117, 'Alonsus', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19118;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19118, 'Tenn', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19119;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19119, 'Tirion', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19120;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19120, 'Taelan', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19121;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19121, 'Gavinrad', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19122;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19122, 'Granis', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19123;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19123, 'Genn', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19124;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19124, 'Nandis', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19125;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19125, 'Geros', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19126;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19126, 'Jorn', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19127;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19127, 'Khadgar', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19128;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19128, 'Landazar', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19129;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19129, 'Shal', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19130;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19130, 'Anduin', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19131;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19131, 'Doril', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19132;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19132, 'Marn', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19133;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19133, 'Malak', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19134;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19134, 'Manadar', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19135;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19135, 'Medivh', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19136;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19136, 'Arthas', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19137;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19137, 'Terenas', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19138;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19138, 'Morlune', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19139;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19139, 'Moroes', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19140;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19140, 'Daelin', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19141;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19141, 'Rhonin', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19142;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19142, 'Sage', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19143;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19143, 'Duncan', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19144;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19144, 'Manos', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19145;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19145, 'Peril', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19146;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19146, 'Aran', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19147;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19147, 'Thoras', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19148;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19148, 'Turalyon', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19149;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19149, 'Uther', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19150;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19150, 'Varien', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19151;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19151, 'Llane', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19152;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19152, 'Zann', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19153;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19153, 'Aegwynn', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19154;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19154, 'Taretha', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19155;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19155, 'Calia', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19156;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19156, 'Maevis', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19157;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19157, 'Alexis', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19158;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19158, 'Ariandra', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19159;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19159, 'Kassandra', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19160;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19160, 'Wilhelmina', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19161;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19161, 'Gloriana', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19162;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19162, 'Sarah', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19163;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19163, 'Samantha', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19164;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19164, 'Kitiara', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19165;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19165, 'April', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19166;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19166, 'Jorune', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19167;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19167, 'Brunhilde', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19168;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19168, 'Sithaya', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19169;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19169, 'Andra', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19170;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19170, 'Amora', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19171;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19171, 'Dierdre', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19172;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19172, 'Sandris', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19173;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19173, 'Adelaide', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19174;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19174, 'Alice', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19175;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19175, 'Amaria', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19176;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19176, 'Amelia', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19177;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19177, 'Avelina', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19178;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19178, 'Barbara', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19179;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19179, 'Beatrix', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19180;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19180, 'Betta', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19181;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19181, 'Brigit', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19182;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19182, 'Calli', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19183;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19183, 'Candis', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19184;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19184, 'Carolyn', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19185;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19185, 'Catherine', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19186;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19186, 'Catin', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19187;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19187, 'Christiana', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19188;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19188, 'Christine', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19189;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19189, 'Cicely', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19190;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19190, 'Constance', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19191;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19191, 'Cristina', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19192;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19192, 'Dagny', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19193;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19193, 'Danielle', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19194;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19194, 'Darcy', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19195;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19195, 'Desiree', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19196;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19196, 'Felicity', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19197;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19197, 'Florencia', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19198;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19198, 'Giliana', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19199;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19199, 'Gladys', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19200;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19200, 'Grace', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19201;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19201, 'Heloise', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19202;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19202, 'Honor', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19203;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19203, 'Hope', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19204;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19204, 'Jane', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19205;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19205, 'Joy', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19206;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19206, 'Kaisa', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19207;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19207, 'Kamilla', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19208;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19208, 'Kimberly', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19209;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19209, 'Lia', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19210;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19210, 'Lois', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19211;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19211, 'Lola', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19212;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19212, 'Lucille', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19213;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19213, 'Margery', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19214;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19214, 'Marilyn', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19215;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19215, 'Marlena', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19216;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19216, 'Meghan', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19217;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19217, 'Mercy', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19218;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19218, 'Mirabell', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19219;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19219, 'Naomi', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19220;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19220, 'Pamela', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19221;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19221, 'Peggy', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19222;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19222, 'Prudence', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19223;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19223, 'Reyna', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19224;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19224, 'Rhoda', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19225;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19225, 'Sabeline', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19226;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19226, 'Theda', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19227;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19227, 'Thelma', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19228;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19228, 'Theresa', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19229;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19229, 'Tiffany', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19230;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19230, 'Tina', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19231;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19231, 'Tracy', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19232;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19232, 'Verity', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19233;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19233, 'Aimery', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19234;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19234, 'Alex', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19235;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19235, 'Alonso', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19236;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19236, 'Ander', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19237;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19237, 'Anselm', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19238;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19238, 'Apollo', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19239;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19239, 'Arlan', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19240;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19240, 'Benedict', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19241;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19241, 'Berenger', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19242;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19242, 'Bertren', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19243;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19243, 'Bruce', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19244;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19244, 'Carl', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19245;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19245, 'Carlin', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19246;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19246, 'Carter', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19247;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19247, 'Cedric', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19248;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19248, 'Clement', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19249;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19249, 'Clinton', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19250;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19250, 'Daniel', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19251;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19251, 'Darren', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19252;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19252, 'Derek', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19253;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19253, 'Eric', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19254;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19254, 'Errol', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19255;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19255, 'Everard', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19256;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19256, 'Garth', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19257;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19257, 'Geoff', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19258;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19258, 'Graham', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19259;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19259, 'Gregory', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19260;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19260, 'Guillaume', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19261;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19261, 'Hadrian', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19262;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19262, 'Halian', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19263;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19263, 'Harold', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19264;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19264, 'Isaac', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19265;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19265, 'Jack', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19266;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19266, 'Jacob', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19267;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19267, 'Jed', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19268;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19268, 'Jeff', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19269;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19269, 'Jeremiah', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19270;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19270, 'Jessie', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19271;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19271, 'Jethro', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19272;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19272, 'Johan', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19273;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19273, 'Judd', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19274;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19274, 'Leroy', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19275;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19275, 'Mitchell', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19276;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19276, 'Paul', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19277;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19277, 'Raiford', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19278;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19278, 'Reese', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19279;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19279, 'Regis', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19280;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19280, 'Reid', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19281;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19281, 'Robert', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19282;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19282, 'Rodney', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19283;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19283, 'Taylor', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19284;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19284, 'Thibault', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19285;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19285, 'Todd', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19286;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19286, 'Walter', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19287;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19287, 'Warin', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19288;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19288, 'Warren', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19289;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19289, 'Wayne', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19290;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19290, 'Wymon', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19291;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19291, 'Xander', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19292;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19292, 'Yves', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19293;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19293, 'Abelard', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19294;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19294, 'Adin', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19295;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19295, 'Adorian', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19296;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19296, 'Aiden', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19297;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19297, 'Aironus', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19298;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19298, 'Alden', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19299;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19299, 'Alexios', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19300;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19300, 'Anders', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19301;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19301, 'Anson', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19302;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19302, 'Artim', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19303;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19303, 'Ashton', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19304;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19304, 'Austen', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19305;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19305, 'Bailby', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19306;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19306, 'Barraud', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19307;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19307, 'Benes', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19308;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19308, 'Brayden', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19309;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19309, 'Caleb', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19310;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19310, 'Cayden', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19311;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19311, 'Cayne', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19312;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19312, 'Cedrick', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19313;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19313, 'Clark', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19314;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19314, 'Clayton', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19315;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19315, 'Corey', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19316;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19316, 'Curtis', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19317;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19317, 'Daician', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19318;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19318, 'Dallin', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19319;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19319, 'Damone', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19320;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19320, 'Davin', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19321;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19321, 'Devon', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19322;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19322, 'Dewey', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19323;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19323, 'Draven', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19324;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19324, 'Dyrius', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19325;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19325, 'Eames', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19326;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19326, 'Edward', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19327;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19327, 'Elgar', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19328;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19328, 'Elroy', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19329;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19329, 'Ethon', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19330;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19330, 'Fanley', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19331;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19331, 'Filmore', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19332;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19332, 'Fletcher', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19333;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19333, 'Franklin', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19334;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19334, 'Gage', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19335;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19335, 'Galan', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19336;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19336, 'Gannet', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19337;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19337, 'Gerrick', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19338;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19338, 'Gunnar', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19339;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19339, 'Haiden', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19340;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19340, 'Haldane', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19341;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19341, 'Halsey', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19342;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19342, 'Holden', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19343;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19343, 'Hudson', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19344;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19344, 'Iridian', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19345;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19345, 'Jaaron', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19346;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19346, 'Jairund', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19347;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19347, 'Jarek', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19348;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19348, 'Jayson', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19349;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19349, 'Jesse', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19350;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19350, 'Joel', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19351;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19351, 'Jonah', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19352;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19352, 'Jonathan', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19353;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19353, 'Justus', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19354;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19354, 'Kai', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19355;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19355, 'Kalvin', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19356;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19356, 'Karsh', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19357;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19357, 'Kashel', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19358;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19358, 'Kaylan', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19359;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19359, 'Keifer', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19360;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19360, 'Keion', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19361;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19361, 'Kenton', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19362;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19362, 'Kevyn', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19363;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19363, 'Koby', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19364;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19364, 'Korban', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19365;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19365, 'Kuthbert', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19366;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19366, 'Lamarre', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19367;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19367, 'Lars', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19368;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19368, 'Lashan', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19369;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19369, 'Layton', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19370;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19370, 'Leland', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19371;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19371, 'Maddox', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19372;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19372, 'Marius', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19373;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19373, 'Marlon', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19374;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19374, 'Miccah', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19375;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19375, 'Nathan', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19376;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19376, 'Nelson', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19377;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19377, 'Nolen', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19378;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19378, 'Oren', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19379;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19379, 'Padrik', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19380;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19380, 'Parker', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19381;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19381, 'Patrick', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19382;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19382, 'Payton', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19383;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19383, 'Phillip', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19384;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19384, 'Piotyr', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19385;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19385, 'Quin', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19386;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19386, 'Quincey', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19387;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19387, 'Sebastian', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19388;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19388, 'Silas', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19389;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19389, 'Symon', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19390;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19390, 'Tanner', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19391;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19391, 'Tavish', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19392;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19392, 'Theodore', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19393;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19393, 'Vale', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19394;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19394, 'Walton', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19395;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19395, 'Waylen', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19396;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19396, 'Willifred', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19397;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19397, 'Yancy', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19398;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19398, 'Yani', @Gilnean, 0;
DELETE FROM `namegen` WHERE `id` = 19399;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19399, 'Acacia', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19400;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19400, 'Alessandra', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19401;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19401, 'Amadria', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19402;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19402, 'Andraia', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19403;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19403, 'Annalea', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19404;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19404, 'Ardyth', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19405;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19405, 'Astradyn', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19406;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19406, 'Autumn', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19407;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19407, 'Becky', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19408;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19408, 'Blythe', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19409;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19409, 'Briar', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19410;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19410, 'Brylee', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19411;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19411, 'Callista', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19412;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19412, 'Cassandra', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19413;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19413, 'Cassima', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19414;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19414, 'Challie', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19415;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19415, 'Chana', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19416;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19416, 'Chelsea', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19417;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19417, 'Chiara', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19418;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19418, 'Dannison', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19419;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19419, 'Daphne', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19420;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19420, 'Darla', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19421;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19421, 'Deandra', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19422;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19422, 'Dellah', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19423;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19423, 'Dominique', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19424;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19424, 'Doriah', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19425;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19425, 'Dorothy', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19426;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19426, 'Edith', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19427;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19427, 'Elaina', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19428;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19428, 'Elenore', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19429;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19429, 'Emilee', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19430;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19430, 'Emma', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19431;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19431, 'Everette', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19432;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19432, 'Evie', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19433;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19433, 'Farrah', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19434;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19434, 'Fiorella', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19435;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19435, 'Galiya', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19436;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19436, 'Gillian', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19437;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19437, 'Gizela', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19438;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19438, 'Gracelyn', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19439;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19439, 'Heidie', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19440;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19440, 'Ilana', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19441;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19441, 'Ione', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19442;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19442, 'Jaimie', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19443;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19443, 'Jalissa', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19444;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19444, 'Janessa', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19445;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19445, 'Jinnea', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19446;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19446, 'Johanna', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19447;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19447, 'Jolanda', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19448;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19448, 'Jolene', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19449;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19449, 'Kaiah', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19450;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19450, 'Kaiya', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19451;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19451, 'Karleigh', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19452;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19452, 'Kelsea', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19453;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19453, 'Kirsten', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19454;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19454, 'Korla', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19455;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19455, 'Kyara', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19456;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19456, 'Leiah', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19457;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19457, 'Leliani', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19458;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19458, 'Lennith', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19459;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19459, 'Lisbeth', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19460;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19460, 'Lisette', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19461;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19461, 'Lynn', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19462;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19462, 'Magdelyn', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19463;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19463, 'Maira', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19464;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19464, 'Manja', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19465;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19465, 'Marguerite', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19466;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19466, 'Marisol', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19467;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19467, 'Marit', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19468;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19468, 'Meadow', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19469;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19469, 'Melodie', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19470;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19470, 'Millicent', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19471;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19471, 'Mistiana', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19472;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19472, 'Myrtha', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19473;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19473, 'Naima', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19474;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19474, 'Neranna', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19475;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19475, 'Odelle', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19476;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19476, 'Ophelia', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19477;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19477, 'Pacey', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19478;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19478, 'Rachael', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19479;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19479, 'Radmila', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19480;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19480, 'Rayna', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19481;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19481, 'Rebekka', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19482;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19482, 'Roberta', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19483;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19483, 'Roselle', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19484;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19484, 'Saige', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19485;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19485, 'Scarlet', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19486;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19486, 'Shancai', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19487;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19487, 'Shanna', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19488;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19488, 'Talia', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19489;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19489, 'Tasha', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19490;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19490, 'Valanese', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19491;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19491, 'Valeska', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19492;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19492, 'Vannah', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19493;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19493, 'Viridiana', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19494;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19494, 'Whittany', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19495;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19495, 'Wynna', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19496;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19496, 'Xara', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19497;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19497, 'Yarina', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19498;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19498, 'Zivanka', @Gilnean, 1;
DELETE FROM `namegen` WHERE `id` = 19499;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19499, 'Zoe', @Gilnean, 1;
