# -*- coding: utf-8 -*-
"""Emit one creature_template per Battlemon form so nameplates are not Cow.

IDs (keep in sync with src/BattlemonOverworld.h):
    creature_template.entry = 1000000 + formId
    creature_template_model display = 50000 + formId
    creature_model_info also covers shiny displays 70000 + formId

    python tools/export_form_npcs_sql.py
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path

FORM_ENTRY_BASE = 1000000
DISPLAY_NORMAL_BASE = 50000
DISPLAY_SHINY_BASE = 70000
CHUNK = 80

DEFAULT_FORMS = Path(
    r"D:\new-client\vanilla test\3.3.5a - Chromie (Reforged)"
    r"\Interface\AddOns\Battlemon\Data\csv\forms.csv"
)
DEFAULT_OUT = (
    Path(__file__).resolve().parents[1]
    / "data"
    / "sql"
    / "world"
    / "base"
    / "2026_08_21_02_battlemon_overworld_form_npcs.sql"
)

TEMPLATE_COLS = (
    "entry", "difficulty_entry_1", "difficulty_entry_2", "difficulty_entry_3",
    "KillCredit1", "KillCredit2", "name", "subname", "IconName", "gossip_menu_id",
    "minlevel", "maxlevel", "exp", "faction", "npcflag",
    "speed_walk", "speed_run", "speed_swim", "speed_flight", "detection_range",
    "rank", "dmgschool", "DamageModifier", "BaseAttackTime", "RangeAttackTime",
    "BaseVariance", "RangeVariance", "unit_class", "unit_flags", "unit_flags2",
    "dynamicflags", "family", "type", "type_flags", "lootid", "pickpocketloot",
    "skinloot", "PetSpellDataId", "VehicleId", "mingold", "maxgold",
    "AIName", "MovementType", "HoverHeight", "HealthModifier", "ManaModifier",
    "ArmorModifier", "ExperienceModifier", "RacialLeader", "movementId",
    "RegenHealth", "CreatureImmunitiesId", "flags_extra", "ScriptName", "VerifiedBuild",
)


def sql_str(value: str) -> str:
    return "'" + value.replace("\\", "\\\\").replace("'", "''") + "'"


def load_forms(path: Path) -> list[dict[str, str]]:
    with path.open(encoding="utf-8-sig", newline="") as fh:
        return [row for row in csv.DictReader(fh) if (row.get("sprite") or "").strip()]


def template_row(form_id: int, name: str) -> str:
    return (
        f"({FORM_ENTRY_BASE + form_id}, 0, 0, 0, "
        f"0, 0, {sql_str(name)}, '', NULL, 0, "
        f"1, 1, 0, 35, 1, "
        f"1, 1.14286, 1, 1, 20, "
        f"0, 0, 1, 2000, 2000, "
        f"1, 1, 1, 258, 0, "
        f"0, 0, 7, 0, 0, 0, "
        f"0, 0, 0, 0, 0, "
        f"'', 0, 1, 1, 1, "
        f"1, 0, 0, 0, "
        f"1, 0, 16785474, 'npc_battlemon_overworld', 12340)"
    )


def write_chunks(fh, header: str, rows: list[str]) -> None:
    for i in range(0, len(rows), CHUNK):
        fh.write(header)
        fh.write(",\n".join(rows[i : i + CHUNK]))
        fh.write(";\n\n")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--forms", type=Path, default=DEFAULT_FORMS)
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = ap.parse_args()
    if not args.forms.is_file():
        raise SystemExit(f"forms.csv not found: {args.forms}")

    forms = load_forms(args.forms)
    templates = []
    models = []
    infos = []
    for form in forms:
        form_id = int(form["id"])
        name = (form.get("name") or "").strip() or f"Battlemon {form_id}"
        display = DISPLAY_NORMAL_BASE + form_id
        shiny = DISPLAY_SHINY_BASE + form_id
        templates.append(template_row(form_id, name))
        models.append(f"({FORM_ENTRY_BASE + form_id}, 0, {display}, 1, 1, 12340)")
        infos.append(f"({display}, 0.8, 1.5, 2, 0, 12340)")
        infos.append(f"({shiny}, 0.8, 1.5, 2, 0, 12340)")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    with args.out.open("w", encoding="utf-8", newline="\n") as fh:
        fh.write("-- One NPC per Battlemon form so the nameplate is the form name.\n")
        fh.write("-- Generated by tools/export_form_npcs_sql.py from addon forms.csv.\n")
        fh.write("-- Rerunnable. Do not edit an already-applied file; re-run the tool.\n\n")
        write_chunks(
            fh,
            "REPLACE INTO `creature_template` (\n  "
            + ", ".join(f"`{c}`" for c in TEMPLATE_COLS)
            + "\n) VALUES\n",
            templates,
        )
        write_chunks(
            fh,
            "REPLACE INTO `creature_template_model` (\n"
            "  `CreatureID`, `Idx`, `CreatureDisplayID`, `DisplayScale`, "
            "`Probability`, `VerifiedBuild`\n) VALUES\n",
            models,
        )
        write_chunks(
            fh,
            "REPLACE INTO `creature_model_info` (\n"
            "  `DisplayID`, `BoundingRadius`, `CombatReach`, `Gender`, "
            "`DisplayID_Other_Gender`, `VerifiedBuild`\n) VALUES\n",
            infos,
        )
    print(f"wrote {len(forms)} form NPCs -> {args.out}")


if __name__ == "__main__":
    main()
