-- [F-029] mod-arac: charbaseinfo: 38 inserts, 0 updates, 0 deletes

-- New entries
DELETE FROM `charbaseinfo` WHERE `race` = @Human AND `class` = @Hunter;
INSERT INTO `charbaseinfo` (`race`, `class`) VALUES (@Human, @Hunter);
DELETE FROM `charbaseinfo` WHERE `race` = @Human AND `class` = @Shaman;
INSERT INTO `charbaseinfo` (`race`, `class`) VALUES (@Human, @Shaman);
DELETE FROM `charbaseinfo` WHERE `race` = @Human AND `class` = @Druid;
INSERT INTO `charbaseinfo` (`race`, `class`) VALUES (@Human, @Druid);
DELETE FROM `charbaseinfo` WHERE `race` = @Orc AND `class` = @Paladin;
INSERT INTO `charbaseinfo` (`race`, `class`) VALUES (@Orc, @Paladin);
DELETE FROM `charbaseinfo` WHERE `race` = @Orc AND `class` = @Priest;
INSERT INTO `charbaseinfo` (`race`, `class`) VALUES (@Orc, @Priest);
DELETE FROM `charbaseinfo` WHERE `race` = @Orc AND `class` = @Mage;
INSERT INTO `charbaseinfo` (`race`, `class`) VALUES (@Orc, @Mage);
DELETE FROM `charbaseinfo` WHERE `race` = @Orc AND `class` = @Druid;
INSERT INTO `charbaseinfo` (`race`, `class`) VALUES (@Orc, @Druid);
DELETE FROM `charbaseinfo` WHERE `race` = @Dwarf AND `class` = @Shaman;
INSERT INTO `charbaseinfo` (`race`, `class`) VALUES (@Dwarf, @Shaman);
DELETE FROM `charbaseinfo` WHERE `race` = @Dwarf AND `class` = @Mage;
INSERT INTO `charbaseinfo` (`race`, `class`) VALUES (@Dwarf, @Mage);
DELETE FROM `charbaseinfo` WHERE `race` = @Dwarf AND `class` = @Warlock;
INSERT INTO `charbaseinfo` (`race`, `class`) VALUES (@Dwarf, @Warlock);
DELETE FROM `charbaseinfo` WHERE `race` = @Dwarf AND `class` = @Druid;
INSERT INTO `charbaseinfo` (`race`, `class`) VALUES (@Dwarf, @Druid);
DELETE FROM `charbaseinfo` WHERE `race` = @NightElf AND `class` = @Paladin;
INSERT INTO `charbaseinfo` (`race`, `class`) VALUES (@NightElf, @Paladin);
DELETE FROM `charbaseinfo` WHERE `race` = @NightElf AND `class` = @Shaman;
INSERT INTO `charbaseinfo` (`race`, `class`) VALUES (@NightElf, @Shaman);
DELETE FROM `charbaseinfo` WHERE `race` = @NightElf AND `class` = @Mage;
INSERT INTO `charbaseinfo` (`race`, `class`) VALUES (@NightElf, @Mage);
DELETE FROM `charbaseinfo` WHERE `race` = @NightElf AND `class` = @Warlock;
INSERT INTO `charbaseinfo` (`race`, `class`) VALUES (@NightElf, @Warlock);
DELETE FROM `charbaseinfo` WHERE `race` = @Undead AND `class` = @Paladin;
INSERT INTO `charbaseinfo` (`race`, `class`) VALUES (@Undead, @Paladin);
DELETE FROM `charbaseinfo` WHERE `race` = @Undead AND `class` = @Hunter;
INSERT INTO `charbaseinfo` (`race`, `class`) VALUES (@Undead, @Hunter);
DELETE FROM `charbaseinfo` WHERE `race` = @Undead AND `class` = @Shaman;
INSERT INTO `charbaseinfo` (`race`, `class`) VALUES (@Undead, @Shaman);
DELETE FROM `charbaseinfo` WHERE `race` = @Undead AND `class` = @Druid;
INSERT INTO `charbaseinfo` (`race`, `class`) VALUES (@Undead, @Druid);
DELETE FROM `charbaseinfo` WHERE `race` = @Tauren AND `class` = @Paladin;
INSERT INTO `charbaseinfo` (`race`, `class`) VALUES (@Tauren, @Paladin);
DELETE FROM `charbaseinfo` WHERE `race` = @Tauren AND `class` = @Rogue;
INSERT INTO `charbaseinfo` (`race`, `class`) VALUES (@Tauren, @Rogue);
DELETE FROM `charbaseinfo` WHERE `race` = @Tauren AND `class` = @Priest;
INSERT INTO `charbaseinfo` (`race`, `class`) VALUES (@Tauren, @Priest);
DELETE FROM `charbaseinfo` WHERE `race` = @Tauren AND `class` = @Mage;
INSERT INTO `charbaseinfo` (`race`, `class`) VALUES (@Tauren, @Mage);
DELETE FROM `charbaseinfo` WHERE `race` = @Tauren AND `class` = @Warlock;
INSERT INTO `charbaseinfo` (`race`, `class`) VALUES (@Tauren, @Warlock);
DELETE FROM `charbaseinfo` WHERE `race` = @Gnome AND `class` = @Paladin;
INSERT INTO `charbaseinfo` (`race`, `class`) VALUES (@Gnome, @Paladin);
DELETE FROM `charbaseinfo` WHERE `race` = @Gnome AND `class` = @Hunter;
INSERT INTO `charbaseinfo` (`race`, `class`) VALUES (@Gnome, @Hunter);
DELETE FROM `charbaseinfo` WHERE `race` = @Gnome AND `class` = @Priest;
INSERT INTO `charbaseinfo` (`race`, `class`) VALUES (@Gnome, @Priest);
DELETE FROM `charbaseinfo` WHERE `race` = @Gnome AND `class` = @Shaman;
INSERT INTO `charbaseinfo` (`race`, `class`) VALUES (@Gnome, @Shaman);
DELETE FROM `charbaseinfo` WHERE `race` = @Gnome AND `class` = @Druid;
INSERT INTO `charbaseinfo` (`race`, `class`) VALUES (@Gnome, @Druid);
DELETE FROM `charbaseinfo` WHERE `race` = @Troll AND `class` = @Paladin;
INSERT INTO `charbaseinfo` (`race`, `class`) VALUES (@Troll, @Paladin);
DELETE FROM `charbaseinfo` WHERE `race` = @Troll AND `class` = @Warlock;
INSERT INTO `charbaseinfo` (`race`, `class`) VALUES (@Troll, @Warlock);
DELETE FROM `charbaseinfo` WHERE `race` = @Troll AND `class` = @Druid;
INSERT INTO `charbaseinfo` (`race`, `class`) VALUES (@Troll, @Druid);
DELETE FROM `charbaseinfo` WHERE `race` = @BloodElf AND `class` = @Warrior;
INSERT INTO `charbaseinfo` (`race`, `class`) VALUES (@BloodElf, @Warrior);
DELETE FROM `charbaseinfo` WHERE `race` = @BloodElf AND `class` = @Shaman;
INSERT INTO `charbaseinfo` (`race`, `class`) VALUES (@BloodElf, @Shaman);
DELETE FROM `charbaseinfo` WHERE `race` = @BloodElf AND `class` = @Druid;
INSERT INTO `charbaseinfo` (`race`, `class`) VALUES (@BloodElf, @Druid);
DELETE FROM `charbaseinfo` WHERE `race` = @Draenei AND `class` = @Rogue;
INSERT INTO `charbaseinfo` (`race`, `class`) VALUES (@Draenei, @Rogue);
DELETE FROM `charbaseinfo` WHERE `race` = @Draenei AND `class` = @Warlock;
INSERT INTO `charbaseinfo` (`race`, `class`) VALUES (@Draenei, @Warlock);
DELETE FROM `charbaseinfo` WHERE `race` = @Draenei AND `class` = @Druid;
INSERT INTO `charbaseinfo` (`race`, `class`) VALUES (@Draenei, @Druid);
