-- [F-029] mod-arac: skillraceclassinfo: 0 inserts, 68 updates, 0 deletes

-- Changed values (original in parentheses)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 117; -- skill: 44 (axes: orc/dwarf/tauren/troll hunters)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 122; -- skill: 172 (two-handed axes: paladins)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 123; -- skill: 160 (two-handed maces: paladins)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 124; -- skill: 160 (two-handed maces: druids)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 125; -- skill: 55 (two-handed swords: hunters)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 126; -- skill: 45 (bows: orc/night elf/troll/blood elf hunters)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 127; -- skill: 45 (bows: warriors, hunters, rogues)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 128; -- skill: 226 (crossbows: warriors, rogues)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 129; -- skill: 173 (daggers: rogues, warlocks)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 131; -- skill: 118 (dual wield: rogues)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 132; -- skill: 118 (dual wield: warriors, hunters)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 133; -- skill: 46 (guns: dwarf/tauren hunters)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 134; -- skill: 46 (guns: warriors, rogues)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 138; -- skill: 136 (staves: priests, shamans, mages, warlocks, druids)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 139; -- skill: 136 (staves: warriors, hunters)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 140; -- skill: 43 (swords: human/orc/night elf/undead/gnome/draenei warriors)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 142; -- skill: 176 (thrown: rogues)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 143; -- skill: 176 (thrown: hunters)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 144; -- skill: 228 (wands: priests, mages, warlocks)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 323; -- skill: 173 (daggers: priests, shamans, mages)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 325; -- skill: 54 (maces: rogues)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 328; -- skill: 43 (swords: hunters)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 330; -- skill: 473 (fist weapons: warriors, hunters, rogues, shamans, druids)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 621; -- skill: 172 (two-handed axes: orc/dwarf warriors)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 622; -- skill: 172 (two-handed axes: warriors)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 624; -- skill: 160 (two-handed maces: tauren warriors)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 625; -- skill: 160 (two-handed maces: warriors)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 626; -- skill: 55 (two-handed swords: warriors)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 628; -- skill: 44 (axes: warriors)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 629; -- skill: 44 (axes: warrior, paladin, hunter, death knight, mage)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 630; -- skill: 44 (axes: warriors)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 631; -- skill: 173 (daggers: rogues)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 632; -- skill: 173 (daggers: warriors)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 633; -- skill: 173 (daggers: night elf/undead/gnome/troll warriors)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 634; -- skill: 173 (daggers: rogues)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 635; -- skill: 46 (guns: hunters)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 636; -- skill: 54 (maces: warriors)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 637; -- skill: 54 (maces: warriors)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 638; -- skill: 43 (swords: warriors)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 639; -- skill: 176 (thrown: troll warriors)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 640; -- skill: 176 (thrown: warriors)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 641; -- skill: 173 (daggers: tauren druids)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 642; -- skill: 173 (daggers: warriors)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 643; -- skill: 54 (maces: night elf druids)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 644; -- skill: 54 (maces: hunters)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 701; -- skill: 172 (two-handed axes: shamans)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 702; -- skill: 160 (two-handed maces: shamans)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 872; -- skill: 43 (swords: rogues)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 878; -- skill: 226 (crossbows: draenei hunters)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 879; -- skill: 226 (crossbows: hunters)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 880; -- skill: 43 (swords: draenei hunters)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 881; -- skill: 43 (swords: mages, warlocks)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 883; -- skill: 118 (dual wield: shaman)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 884; -- skill: 55 (two-handed swords: blood elf paladins)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 885; -- skill: 43 (swords: human/dwarf/draenei paladins)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 886; -- skill: 43 (swords: paladins)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 888; -- skill: 54 (maces: paladins)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 889; -- skill: 54 (maces: blood elf paladins)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 898; -- skill: 55 (two-handed swords: death knights)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 901; -- skill: 55 (two-handed swords: paladins)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 907; -- skill: 172 (two-handed axes: death knights)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 908; -- skill: 160 (two-handed maces: death knights)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 910; -- skill: 43 (swords: death knights)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 912; -- skill: 44 (axes: death knights)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 913; -- skill: 118 (dual wield: death knights)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 914; -- skill: 54 (maces: death knights)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 915; -- skill: 229 (polearms: death knights)
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | @PlayableRaceMask WHERE `id` = 970; -- skill: 172 (two-handed axes: hunters)
