-- [F-029] mod-arac: skilllineability: 0 inserts, 38 updates, 0 deletes

-- Changed values
UPDATE `skilllineability` SET `required_races` = `required_races` | @AllianceMask WHERE `id` = 7594;
UPDATE `skilllineability` SET `required_races` = `required_races` | @AllianceMask WHERE `id` = 12518;
UPDATE `skilllineability` SET `required_races` = `required_races` | @HordeMask  WHERE `id` = 13151;
UPDATE `skilllineability` SET `required_races` = `required_races` | @BloodElfMask, `required_classes` = `required_classes` | @ManaClassMask & ~@DruidMask WHERE `id` = 14013;
UPDATE `skilllineability` SET `required_classes` = `required_classes` | @WarriorMask | @PaladinMask | @HunterMask | @RogueMask | @DeathKnightMask WHERE `id` = 14022;
UPDATE `skilllineability` SET `required_classes` = `required_classes` | @PriestMask | @ShamanMask | @MageMask | @WarlockMask | @DruidMask WHERE `id` = 14023;
UPDATE `skilllineability` SET `required_races` = `required_races` | @AllianceMask WHERE `id` = 14779;
UPDATE `skilllineability` SET `required_races` = `required_races` | @HordeMask  WHERE `id` = 14784;
UPDATE `skilllineability` SET `required_races` = `required_races` | @AllianceMask WHERE `id` = 14787;
UPDATE `skilllineability` SET `required_races` = `required_races` | @AllianceMask WHERE `id` = 14788;
UPDATE `skilllineability` SET `required_races` = `required_races` | @AllianceMask WHERE `id` = 14795;
UPDATE `skilllineability` SET `required_classes` = `required_classes` | @PriestMask | @MageMask | @WarlockMask WHERE `id` = 15034;
UPDATE `skilllineability` SET `required_classes` = `required_classes` | @PaladinMask | @ShamanMask | @DruidMask WHERE `id` = 15035;
UPDATE `skilllineability` SET `required_races` = `required_races` | @HordeMask  WHERE `id` = 15252;
UPDATE `skilllineability` SET `required_races` = `required_races` | @HordeMask  WHERE `id` = 15253;
UPDATE `skilllineability` SET `required_races` = `required_races` | @BloodElfMask WHERE `id` = 17510;
UPDATE `skilllineability` SET `required_races` = `required_races` | @AllianceMask WHERE `id` = 18299;
UPDATE `skilllineability` SET `required_races` = `required_races` | @HordeMask  WHERE `id` = 18308;
UPDATE `skilllineability` SET `required_races` = `required_races` | @HordeMask  WHERE `id` = 18311;
UPDATE `skilllineability` SET `required_races` = `required_races` | @HordeMask  WHERE `id` = 18314;
UPDATE `skilllineability` SET `required_races` = `required_races` | @AllianceMask WHERE `id` = 20089;
UPDATE `skilllineability` SET `required_races` = `required_races` | @HordeMask  WHERE `id` = 20090;
UPDATE `skilllineability` SET `required_races` = `required_races` | @AllianceMask WHERE `id` = 20091;
UPDATE `skilllineability` SET `required_races` = `required_races` | @HordeMask  WHERE `id` = 20092;
UPDATE `skilllineability` SET `required_races` = `required_races` | @Draenei WHERE `id` = 20171;
UPDATE `skilllineability` SET `required_classes` = 0 WHERE `id` = 20665;
UPDATE `skilllineability` SET `skill_line` = 756, `spell_id` = 80865, `required_races` = @BloodElfMask, `acquire_method` = 2 WHERE `id` = 20684;
UPDATE `skilllineability` SET `skill_line` = 756, `spell_id` = 80866, `required_races` = @BloodElfMask, `required_classes` = @DruidMask, `acquire_method` = 2 WHERE `id` = 20685;
UPDATE `skilllineability` SET `skill_line` = 756, `spell_id` = 80867, `required_races` = @BloodElfMask, `required_classes` = @DruidMask, `acquire_method` = 2 WHERE `id` = 20686;
UPDATE `skilllineability` SET `skill_line` = 756, `spell_id` = 80868, `required_races` = @BloodElfMask, `required_classes` = @WarriorMask, `acquire_method` = 2 WHERE `id` = 20687;
UPDATE `skilllineability` SET `skill_line` = 760, `spell_id` = 80869, `required_races` = @DraeneiMask, `required_classes` = @DruidMask, `acquire_method` = 2 WHERE `id` = 20688;
UPDATE `skilllineability` SET `skill_line` = 760, `spell_id` = 80870, `required_races` = @DraeneiMask, `required_classes` = @RogueMask, `acquire_method` = 2 WHERE `id` = 20689;
UPDATE `skilllineability` SET `skill_line` = 760, `spell_id` = 80871, `required_races` = @DraeneiMask, `required_classes` = @WarlockMask, `acquire_method` = 2 WHERE `id` = 20690;
UPDATE `skilllineability` SET `skill_line` = 760, `spell_id` = 80872, `required_races` = @DraeneiMask, `required_classes` = @DruidMask, `acquire_method` = 2 WHERE `id` = 20691;
UPDATE `skilllineability` SET `skill_line` = 760, `spell_id` = 80873, `required_races` = @DraeneiMask, `required_classes` = @RogueMask, `acquire_method` = 2 WHERE `id` = 20692;
UPDATE `skilllineability` SET `skill_line` = 760, `spell_id` = 80874, `required_races` = @DraeneiMask, `required_classes` = @WarlockMask, `acquire_method` = 2 WHERE `id` = 20693;
UPDATE `skilllineability` SET `required_races` = 0 WHERE `id` = 20867;
UPDATE `skilllineability` SET `required_races` = 0 WHERE `id` = 20868;
