SET @GoblinMask  =  256;
SET @WorgenMask  = 2048;
SET @PaladinMask =    2;
SET @ShamanMask  =   64;
SET @DruidMask   = 1024;
INSERT IGNORE INTO `playercreateinfo_spell_custom` VALUES
-- Goblin Paladin
(@GoblinMask, @PaladinMask, '669', 'Language Orcish'),
(@GoblinMask, @PaladinMask, '69041', 'Rocket Barrage'),
(@GoblinMask, @PaladinMask, '69042', 'Time is Money'),
(@GoblinMask, @PaladinMask, '69044', 'Best Deals Anywhere'),
(@GoblinMask, @PaladinMask, '69045', 'Better Living Through Chemistry'),
(@GoblinMask, @PaladinMask, '69046', 'Pack Hobgoblin'),
(@GoblinMask, @PaladinMask, '69070', 'Rocket Jump'),
(@GoblinMask, @PaladinMask, '81', 'Dodge'),
(@GoblinMask, @PaladinMask, '107', 'Block'),
(@GoblinMask, @PaladinMask, '198', 'One-Handed Maces'),
(@GoblinMask, @PaladinMask, '199', 'Two-Handed Maces'),
(@GoblinMask, @PaladinMask, '203', 'Unarmed'),
(@GoblinMask, @PaladinMask, '204', 'Defense'),
(@GoblinMask, @PaladinMask, '522', 'SPELLDEFENSE(DND)'),
(@GoblinMask, @PaladinMask, '635', 'Holy Light'),
(@GoblinMask, @PaladinMask, '750', 'Plate Armor'),
-- (@GoblinMask, @PaladinMask, '1020', 'Divine Shield'), -- Removed?
(@GoblinMask, @PaladinMask, '1038', 'Hand of Salvation'),
(@GoblinMask, @PaladinMask, '1044', 'Hand of Freedom'),
(@GoblinMask, @PaladinMask, '2382', 'Generic'),
(@GoblinMask, @PaladinMask, '2479', 'Honorless Target'),
(@GoblinMask, @PaladinMask, '3050', 'Detect'),
(@GoblinMask, @PaladinMask, '3127', 'Parry'),
(@GoblinMask, @PaladinMask, '3365', 'Opening'),
(@GoblinMask, @PaladinMask, '4987', 'Cleanse'),
(@GoblinMask, @PaladinMask, '5502', 'Sense Undead'),
-- (@GoblinMask, @PaladinMask, '5627', 'Turn Undead'), -- Removed?
(@GoblinMask, @PaladinMask, '6233', 'Closing'),
(@GoblinMask, @PaladinMask, '6246', 'Closing'),
(@GoblinMask, @PaladinMask, '6247', 'Opening'),
(@GoblinMask, @PaladinMask, '6477', 'Opening'),
(@GoblinMask, @PaladinMask, '6478', 'Opening'),
(@GoblinMask, @PaladinMask, '6603', 'Attack'),
(@GoblinMask, @PaladinMask, '7266', 'Duel'),
(@GoblinMask, @PaladinMask, '7267', 'Grovel'),
(@GoblinMask, @PaladinMask, '7355', 'Stuck'),
(@GoblinMask, @PaladinMask, '8386', 'Attacking'),
(@GoblinMask, @PaladinMask, '8737', 'Mail'),
(@GoblinMask, @PaladinMask, '9077', 'Leather'),
(@GoblinMask, @PaladinMask, '9078', 'Cloth'),
(@GoblinMask, @PaladinMask, '9116', 'Shield'),
(@GoblinMask, @PaladinMask, '9125', 'Generic'),
(@GoblinMask, @PaladinMask, '10278', 'Hand of Protection'),
(@GoblinMask, @PaladinMask, '10308', 'Hammer of Justice'),
(@GoblinMask, @PaladinMask, '10326', 'Turn Evil'),
(@GoblinMask, @PaladinMask, '19746', 'Concentration Aura'),
(@GoblinMask, @PaladinMask, '19752', 'Divine Intervention'),
(@GoblinMask, @PaladinMask, '20271', 'Judgement of Light'),
(@GoblinMask, @PaladinMask, '20773', 'Redemption'),
(@GoblinMask, @PaladinMask, '21084', 'Seal of Righteousness'),
(@GoblinMask, @PaladinMask, '21651', 'Opening'),
(@GoblinMask, @PaladinMask, '21652', 'Closing'),
(@GoblinMask, @PaladinMask, '22027', 'Remove Insignia'),
(@GoblinMask, @PaladinMask, '22810', 'Opening - No Text'),
(@GoblinMask, @PaladinMask, '23214', 'Charger'),
(@GoblinMask, @PaladinMask, '25780', 'Righteous Fury'),
-- (@GoblinMask, @PaladinMask, '25895', 'Greater Blessing of Salvation'), -- Removed?
(@GoblinMask, @PaladinMask, '25898', 'Greater Blessing of Kings'),
(@GoblinMask, @PaladinMask, '27136', 'Holy Light'),
(@GoblinMask, @PaladinMask, '27137', 'Flash of Light'),
(@GoblinMask, @PaladinMask, '27138', 'Exorcism'),
(@GoblinMask, @PaladinMask, '27139', 'Holy Wrath'),
(@GoblinMask, @PaladinMask, '27140', 'Blessing of Might'),
(@GoblinMask, @PaladinMask, '27141', 'Greater Blessing of Might'),
(@GoblinMask, @PaladinMask, '27142', 'Blessing of Wisdom'),
(@GoblinMask, @PaladinMask, '27143', 'Greater Blessing of Wisdom'),
-- (@GoblinMask, @PaladinMask, '27144', 'Blessing of Light'), -- Removed?
-- (@GoblinMask, @PaladinMask, '27145', 'Greater Blessing of Light'), -- Removed?
-- (@GoblinMask, @PaladinMask, '27148', 'Blessing of Sacrifice'), -- Removed?
(@GoblinMask, @PaladinMask, '27149', 'Devotion Aura'),
(@GoblinMask, @PaladinMask, '27150', 'Retribution Aura'),
(@GoblinMask, @PaladinMask, '27151', 'Shadow Resistance Aura'),
(@GoblinMask, @PaladinMask, '27152', 'Frost Resistance Aura'),
(@GoblinMask, @PaladinMask, '27153', 'Fire Resistance Aura'),
(@GoblinMask, @PaladinMask, '27154', 'Lay on Hands'),
-- (@GoblinMask, @PaladinMask, '27155', 'Seal of Righteousness'), -- Removed?
-- (@GoblinMask, @PaladinMask, '27158', 'Seal of the Crusader'), -- Removed?
-- (@GoblinMask, @PaladinMask, '27160', 'Seal of Light'), -- Removed?
-- (@GoblinMask, @PaladinMask, '27166', 'Seal of Wisdom'), -- Removed?
-- (@GoblinMask, @PaladinMask, '27169', 'Greater Blessing of Sanctuary'), -- Removed?
(@GoblinMask, @PaladinMask, '27173', 'Consecration'),
(@GoblinMask, @PaladinMask, '27180', 'Hammer of Wrath'),
(@GoblinMask, @PaladinMask, '27762', 'Libram'),
(@GoblinMask, @PaladinMask, '31789', 'Righteous Defense'),
(@GoblinMask, @PaladinMask, '31801', 'Seal of Vengeance'),
(@GoblinMask, @PaladinMask, '31884', 'Avenging Wrath'),
-- (@GoblinMask, @PaladinMask, '31895', 'Seal of Justice'), -- Removed?
(@GoblinMask, @PaladinMask, '32223', 'Crusader Aura'),
(@GoblinMask, @PaladinMask, '33776', 'Spiritual Attunement'),

-- Goblin Druid
(@GoblinMask, @DruidMask, '669', 'Language Orcish'),
(@GoblinMask, @DruidMask, '69041', 'Rocket Barrage'),
(@GoblinMask, @DruidMask, '69042', 'Time is Money'),
(@GoblinMask, @DruidMask, '69044', 'Best Deals Anywhere'),
(@GoblinMask, @DruidMask, '69045', 'Better Living Through Chemistry'),
(@GoblinMask, @DruidMask, '69046', 'Pack Hobgoblin'),
(@GoblinMask, @DruidMask, '69070', 'Rocket Jump'),
(@GoblinMask, @DruidMask, '81', 'Dodge'),
(@GoblinMask, @DruidMask, '198', 'One-Handed Maces'),
(@GoblinMask, @DruidMask, '203', 'Unarmed'),
(@GoblinMask, @DruidMask, '204', 'Defense'),
(@GoblinMask, @DruidMask, '227', 'Staves'),
(@GoblinMask, @DruidMask, '522', 'SPELLDEFENSE(DND)'),
(@GoblinMask, @DruidMask, '1178', 'Bear Form(Passive)'),
(@GoblinMask, @DruidMask, '2382', 'Generic'),
(@GoblinMask, @DruidMask, '2479', 'Honorless Target'),
(@GoblinMask, @DruidMask, '3025', 'Cat Form(Passive)'),
(@GoblinMask, @DruidMask, '3050', 'Detect'),
(@GoblinMask, @DruidMask, '3365', 'Opening'),
(@GoblinMask, @DruidMask, '5176', 'Wrath'),
(@GoblinMask, @DruidMask, '5185', 'Healing Touch'),
(@GoblinMask, @DruidMask, '5419', 'Travel Form(Passive)'),
(@GoblinMask, @DruidMask, '5420', 'Tree of Life'),
(@GoblinMask, @DruidMask, '5421', 'Aquatic Form(Passive)'),
(@GoblinMask, @DruidMask, '6233', 'Closing'),
(@GoblinMask, @DruidMask, '6246', 'Closing'),
(@GoblinMask, @DruidMask, '6247', 'Opening'),
(@GoblinMask, @DruidMask, '6477', 'Opening'),
(@GoblinMask, @DruidMask, '6478', 'Opening'),
(@GoblinMask, @DruidMask, '6603', 'Attack'),
(@GoblinMask, @DruidMask, '7266', 'Duel'),
(@GoblinMask, @DruidMask, '7267', 'Grovel'),
(@GoblinMask, @DruidMask, '7355', 'Stuck'),
(@GoblinMask, @DruidMask, '8386', 'Attacking'),
(@GoblinMask, @DruidMask, '9077', 'Leather'),
(@GoblinMask, @DruidMask, '9078', 'Cloth'),
(@GoblinMask, @DruidMask, '9125', 'Generic'),
(@GoblinMask, @DruidMask, '9635', 'Dire Bear Form(Passive)'),
(@GoblinMask, @DruidMask, '21178', 'Bear Form(Passive2)'),
(@GoblinMask, @DruidMask, '21651', 'Opening'),
(@GoblinMask, @DruidMask, '21652', 'Closing'),
(@GoblinMask, @DruidMask, '22027', 'Remove Insignia'),
(@GoblinMask, @DruidMask, '22810', 'Opening - No Text'),
(@GoblinMask, @DruidMask, '24905', 'Moonkin Form(Passive)'),
(@GoblinMask, @DruidMask, '27764', 'Fetish'),
(@GoblinMask, @DruidMask, '33948', 'Flight Form(Passive)'),
(@GoblinMask, @DruidMask, '34123', 'Tree of Life(Passive)'),
(@GoblinMask, @DruidMask, '40121', 'Swift Flight Form(Passive)'),
(@GoblinMask, @DruidMask, '26979', 'Healing Touch'),
(@GoblinMask, @DruidMask, '26990', 'Mark of the Wild'),
(@GoblinMask, @DruidMask, '26985', 'Wrath'),
(@GoblinMask, @DruidMask, '26988', 'Moonfire'),
(@GoblinMask, @DruidMask, '26982', 'Rejuvenation'),
(@GoblinMask, @DruidMask, '26992', 'Thorns'),
(@GoblinMask, @DruidMask, '26989', 'Entangling Roots'),
(@GoblinMask, @DruidMask, '26998', 'Demoralizing Roar'),
(@GoblinMask, @DruidMask, '6795', 'Growl'),
(@GoblinMask, @DruidMask, '26996', 'Maul'),
(@GoblinMask, @DruidMask, '18960', 'Teleport: Moonglade'),
(@GoblinMask, @DruidMask, '9634', 'Dire Bear Form'),
(@GoblinMask, @DruidMask, '768', 'Cat Form'),
(@GoblinMask, @DruidMask, '783', 'Travel Form'),
(@GoblinMask, @DruidMask, '1066', 'Aquatic Form'),
(@GoblinMask, @DruidMask, '40120', 'Swift Flight Form'),
(@GoblinMask, @DruidMask, '5229', 'Enrage'),
(@GoblinMask, @DruidMask, '26980', 'Regrowth'),
(@GoblinMask, @DruidMask, '8983', 'Bash'),
(@GoblinMask, @DruidMask, '8946', 'Cure Poison'),
(@GoblinMask, @DruidMask, '26997', 'Swipe (Bear)'),
-- (@GoblinMask, @DruidMask, '26993', 'Faerie Fire'), -- Removed?
(@GoblinMask, @DruidMask, '18658', 'Hibernate'),
(@GoblinMask, @DruidMask, '27000', 'Claw'),
(@GoblinMask, @DruidMask, '9913', 'Prowl'),
(@GoblinMask, @DruidMask, '26994', 'Rebirth'),
(@GoblinMask, @DruidMask, '27008', 'Rip'),
(@GoblinMask, @DruidMask, '26986', 'Starfire'),
(@GoblinMask, @DruidMask, '27002', 'Shred'),
(@GoblinMask, @DruidMask, '26995', 'Soothe Animal'),
(@GoblinMask, @DruidMask, '27003', 'Rake'),
(@GoblinMask, @DruidMask, '2782', 'Remove Curse'),
(@GoblinMask, @DruidMask, '9846', 'Tigers Fury'),
(@GoblinMask, @DruidMask, '2893', 'Abolish Poison'),
(@GoblinMask, @DruidMask, '33357', 'Dash'),
(@GoblinMask, @DruidMask, '5209', 'Challenging Roar'),
(@GoblinMask, @DruidMask, '27004', 'Cower'),
(@GoblinMask, @DruidMask, '26983', 'Tranquility'),
(@GoblinMask, @DruidMask, '24248', 'Ferocious Bite'),
(@GoblinMask, @DruidMask, '27005', 'Ravage'),
(@GoblinMask, @DruidMask, '5225', 'Track Humanoids'),
-- (@GoblinMask, @DruidMask, '26999', 'Frenzied Regeneration'), -- Removed?
(@GoblinMask, @DruidMask, '27012', 'Hurricane'),
(@GoblinMask, @DruidMask, '27006', 'Pounce'),
(@GoblinMask, @DruidMask, '29166', 'Innervate'),
(@GoblinMask, @DruidMask, '22812', 'Bark Skin'),
(@GoblinMask, @DruidMask, '26991', 'Gift of the Wild'),
(@GoblinMask, @DruidMask, '22570', 'Maim'),
(@GoblinMask, @DruidMask, '33763', 'Lifebloom'),
(@GoblinMask, @DruidMask, '33745', 'Lacerate'),
(@GoblinMask, @DruidMask, '33786', 'Cyclone'),
(@GoblinMask, @DruidMask, '20719', 'Feline Grace'),

-- Worgen Paladin
(@WorgenMask, @PaladinMask, '68975', 'Viciousness'),
(@WorgenMask, @PaladinMask, '68976', 'Aberration'),
(@WorgenMask, @PaladinMask, '68978', 'Flayer'),
(@WorgenMask, @PaladinMask, '68992', 'Darkflight'),
(@WorgenMask, @PaladinMask, '81', 'Dodge'),
(@WorgenMask, @PaladinMask, '107', 'Block'),
(@WorgenMask, @PaladinMask, '198', 'One-Handed Maces'),
(@WorgenMask, @PaladinMask, '199', 'Two-Handed Maces'),
(@WorgenMask, @PaladinMask, '203', 'Unarmed'),
(@WorgenMask, @PaladinMask, '204', 'Defense'),
(@WorgenMask, @PaladinMask, '522', 'SPELLDEFENSE(DND)'),
(@WorgenMask, @PaladinMask, '635', 'Holy Light'),
(@WorgenMask, @PaladinMask, '668', 'Language Common'),
(@WorgenMask, @PaladinMask, '2382', 'Generic'),
(@WorgenMask, @PaladinMask, '2479', 'Honorless Target'),
(@WorgenMask, @PaladinMask, '3050', 'Detect'),
(@WorgenMask, @PaladinMask, '3365', 'Opening'),
(@WorgenMask, @PaladinMask, '6233', 'Closing'),
(@WorgenMask, @PaladinMask, '6246', 'Closing'),
(@WorgenMask, @PaladinMask, '6247', 'Opening'),
(@WorgenMask, @PaladinMask, '6477', 'Opening'),
(@WorgenMask, @PaladinMask, '6478', 'Opening'),
(@WorgenMask, @PaladinMask, '6603', 'Attack'),
(@WorgenMask, @PaladinMask, '7266', 'Duel'),
(@WorgenMask, @PaladinMask, '7267', 'Grovel'),
(@WorgenMask, @PaladinMask, '7355', 'Stuck'),
(@WorgenMask, @PaladinMask, '8386', 'Attacking'),
(@WorgenMask, @PaladinMask, '8737', 'Mail'),
(@WorgenMask, @PaladinMask, '9077', 'Leather'),
(@WorgenMask, @PaladinMask, '9078', 'Cloth'),
(@WorgenMask, @PaladinMask, '9116', 'Shield'),
(@WorgenMask, @PaladinMask, '9125', 'Generic'),
(@WorgenMask, @PaladinMask, '21084', 'Seal of Righteousness'),
(@WorgenMask, @PaladinMask, '21651', 'Opening'),
(@WorgenMask, @PaladinMask, '21652', 'Closing'),
(@WorgenMask, @PaladinMask, '22027', 'Remove Insignia'),
(@WorgenMask, @PaladinMask, '22810', 'Opening - No Text'),
(@WorgenMask, @PaladinMask, '27762', 'Libram'),
(@WorgenMask, @PaladinMask, '27149', 'Devotion Aura'),
(@WorgenMask, @PaladinMask, '27136', 'Holy Light'),
-- (@WorgenMask, @PaladinMask, '27155', 'Seal of Righteousness'), -- Removed?
(@WorgenMask, @PaladinMask, '27140', 'Blessing of Might'),
(@WorgenMask, @PaladinMask, '20271', 'Judgement of Light'),
-- (@WorgenMask, @PaladinMask, '27158', 'Seal of the Crusader'), -- Removed?
(@WorgenMask, @PaladinMask, '10308', 'Hammer of Justice'),
(@WorgenMask, @PaladinMask, '10278', 'Hand of Protection'),
(@WorgenMask, @PaladinMask, '27154', 'Lay on Hands'),
(@WorgenMask, @PaladinMask, '20773', 'Redemption'),
(@WorgenMask, @PaladinMask, '27142', 'Blessing of Wisdom'),
(@WorgenMask, @PaladinMask, '31789', 'Righteous Defense'),
(@WorgenMask, @PaladinMask, '27150', 'Retribution Aura'),
(@WorgenMask, @PaladinMask, '25780', 'Righteous Fury'),
(@WorgenMask, @PaladinMask, '1044', 'Hand of Freedom'),
(@WorgenMask, @PaladinMask, '33776', 'Spiritual Attunement'),
(@WorgenMask, @PaladinMask, '27173', 'Consecration'),
(@WorgenMask, @PaladinMask, '27138', 'Exorcism'),
(@WorgenMask, @PaladinMask, '27137', 'Flash of Light'),
(@WorgenMask, @PaladinMask, '5502', 'Sense Undead'),
(@WorgenMask, @PaladinMask, '19746', 'Concentration Aura'),
-- (@WorgenMask, @PaladinMask, '31895', 'Seal of Justice'), -- Removed?
-- (@WorgenMask, @PaladinMask, '5627', 'Turn Undead'), -- Removed?
(@WorgenMask, @PaladinMask, '1038', 'Hand of Salvation'),
(@WorgenMask, @PaladinMask, '27151', 'Shadow Resistance Aura'),
(@WorgenMask, @PaladinMask, '19752', 'Divine Intervention'),
-- (@WorgenMask, @PaladinMask, '27160', 'Seal of Light'), -- Removed?
(@WorgenMask, @PaladinMask, '27152', 'Frost Resistance Aura'),
-- (@WorgenMask, @PaladinMask, '1020', 'Divine Shield'), -- Removed?
(@WorgenMask, @PaladinMask, '27153', 'Fire Resistance Aura'),
-- (@WorgenMask, @PaladinMask, '27166', 'Seal of Wisdom'), -- Removed?
-- (@WorgenMask, @PaladinMask, '27144', 'Blessing of Light'), -- Removed?
(@WorgenMask, @PaladinMask, '4987', 'Cleanse'),
(@WorgenMask, @PaladinMask, '27180', 'Hammer of Wrath'),
-- (@WorgenMask, @PaladinMask, '27148', 'Blessing of Sacrifice'), -- Removed?
(@WorgenMask, @PaladinMask, '27139', 'Holy Wrath'),
(@WorgenMask, @PaladinMask, '27141', 'Greater Blessing of Might'),
(@WorgenMask, @PaladinMask, '10326', 'Turn Evil'),
(@WorgenMask, @PaladinMask, '27143', 'Greater Blessing of Wisdom'),
(@WorgenMask, @PaladinMask, '25898', 'Greater Blessing of Kings'),
-- (@WorgenMask, @PaladinMask, '27145', 'Greater Blessing of Light'), -- Removed?
-- (@WorgenMask, @PaladinMask, '25895', 'Greater Blessing of Salvation'), -- Removed?
(@WorgenMask, @PaladinMask, '32223', 'Crusader Aura'),
-- (@WorgenMask, @PaladinMask, '27169', 'Greater Blessing of Sanctuary'), -- Removed?
(@WorgenMask, @PaladinMask, '31884', 'Avenging Wrath'),
(@WorgenMask, @PaladinMask, '750', 'Plate Armor'),
(@WorgenMask, @PaladinMask, '3127', 'Parry'),
(@WorgenMask, @PaladinMask, '23214', 'Charger'), -- Only 9?
(@WorgenMask, @PaladinMask, '31801', 'Seal of Vengeance'), -- Only 9?

-- Worgen Shaman
(@WorgenMask, @ShamanMask, '68975', 'Viciousness'),
(@WorgenMask, @ShamanMask, '68976', 'Aberration'),
(@WorgenMask, @ShamanMask, '68978', 'Flayer'),
(@WorgenMask, @ShamanMask, '68992', 'Darkflight'),
(@WorgenMask, @ShamanMask, '81', 'Dodge'),
(@WorgenMask, @ShamanMask, '107', 'Block'),
(@WorgenMask, @ShamanMask, '131', 'Water Breathing'),
(@WorgenMask, @ShamanMask, '198', 'One-Handed Maces'),
(@WorgenMask, @ShamanMask, '203', 'Unarmed'),
(@WorgenMask, @ShamanMask, '204', 'Defense'),
(@WorgenMask, @ShamanMask, '227', 'Staves'),
(@WorgenMask, @ShamanMask, '331', 'Healing Wave'),
(@WorgenMask, @ShamanMask, '403', 'Lightning Bolt'),
(@WorgenMask, @ShamanMask, '421', 'Chain Lightning'),
(@WorgenMask, @ShamanMask, '522', 'SPELLDEFENSE(DND)'),
(@WorgenMask, @ShamanMask, '526', 'Cure Toxins'),
(@WorgenMask, @ShamanMask, '546', 'Water Walking'),
(@WorgenMask, @ShamanMask, '556', 'Astral Recall'),
(@WorgenMask, @ShamanMask, '668', 'Language Common'),
(@WorgenMask, @ShamanMask, '2062', 'Earth Elemental Totem'),
(@WorgenMask, @ShamanMask, '2382', 'Generic'),
(@WorgenMask, @ShamanMask, '2479', 'Honorless Target'),
(@WorgenMask, @ShamanMask, '2484', 'Earthbind Totem'),
(@WorgenMask, @ShamanMask, '2645', 'Ghost Wolf'),
(@WorgenMask, @ShamanMask, '2825', 'Bloodlust'),
-- (@WorgenMask, @ShamanMask, '2870', 'Cure Disease'), -- Removed?
(@WorgenMask, @ShamanMask, '2894', 'Fire Elemental Totem'),
(@WorgenMask, @ShamanMask, '3050', 'Detect'),
(@WorgenMask, @ShamanMask, '3365', 'Opening'),
(@WorgenMask, @ShamanMask, '3738', 'Wrath of Air Totem'),
(@WorgenMask, @ShamanMask, '6196', 'Far Sight'),
(@WorgenMask, @ShamanMask, '6233', 'Closing'),
(@WorgenMask, @ShamanMask, '6246', 'Closing'),
(@WorgenMask, @ShamanMask, '6247', 'Opening'),
(@WorgenMask, @ShamanMask, '6477', 'Opening'),
(@WorgenMask, @ShamanMask, '6478', 'Opening'),
(@WorgenMask, @ShamanMask, '6495', 'Sentry Totem'),
(@WorgenMask, @ShamanMask, '6603', 'Attack'),
(@WorgenMask, @ShamanMask, '7266', 'Duel'),
(@WorgenMask, @ShamanMask, '7267', 'Grovel'),
(@WorgenMask, @ShamanMask, '7355', 'Stuck'),
(@WorgenMask, @ShamanMask, '8012', 'Purge'),
(@WorgenMask, @ShamanMask, '8143', 'Tremor Totem'),
(@WorgenMask, @ShamanMask, '8166', 'Poison Cleansing Totem'),
(@WorgenMask, @ShamanMask, '8170', 'Cleansing Totem'),
(@WorgenMask, @ShamanMask, '8177', 'Grounding Totem'),
(@WorgenMask, @ShamanMask, '8386', 'Attacking'),
(@WorgenMask, @ShamanMask, '9077', 'Leather'),
(@WorgenMask, @ShamanMask, '9078', 'Cloth'),
(@WorgenMask, @ShamanMask, '9116', 'Shield'),
(@WorgenMask, @ShamanMask, '9125', 'Generic'),
(@WorgenMask, @ShamanMask, '20777', 'Ancestral Spirit'),
(@WorgenMask, @ShamanMask, '21651', 'Opening'),
(@WorgenMask, @ShamanMask, '21652', 'Closing'),
(@WorgenMask, @ShamanMask, '22027', 'Remove Insignia'),
(@WorgenMask, @ShamanMask, '22810', 'Opening - No Text'),
-- (@WorgenMask, @ShamanMask, '25359', 'Grace of Air Totem'), -- Removed?
(@WorgenMask, @ShamanMask, '25396', 'Healing Wave'),
(@WorgenMask, @ShamanMask, '25420', 'Lesser Healing Wave'),
(@WorgenMask, @ShamanMask, '25423', 'Chain Heal'),
(@WorgenMask, @ShamanMask, '25449', 'Lightning Bolt'),
(@WorgenMask, @ShamanMask, '25454', 'Earth Shock'),
(@WorgenMask, @ShamanMask, '25457', 'Flame Shock'),
(@WorgenMask, @ShamanMask, '25464', 'Frost Shock'),
(@WorgenMask, @ShamanMask, '25472', 'Lightning Shield'),
-- (@WorgenMask, @ShamanMask, '25485', 'Rockbiter Weapon'), -- Removed?
(@WorgenMask, @ShamanMask, '25489', 'Flametongue Weapon'),
(@WorgenMask, @ShamanMask, '25500', 'Frostbrand Weapon'),
(@WorgenMask, @ShamanMask, '25505', 'Windfury Weapon'),
(@WorgenMask, @ShamanMask, '25509', 'Stoneskin Totem'),
(@WorgenMask, @ShamanMask, '25525', 'Stoneclaw Totem'),
(@WorgenMask, @ShamanMask, '25528', 'Strength of Earth Totem'),
(@WorgenMask, @ShamanMask, '25533', 'Searing Totem'),
(@WorgenMask, @ShamanMask, '25547', 'Fire Nova'),
(@WorgenMask, @ShamanMask, '25552', 'Magma Totem'),
(@WorgenMask, @ShamanMask, '25557', 'Flametongue Totem'),
(@WorgenMask, @ShamanMask, '25560', 'Frost Resistance Totem'),
(@WorgenMask, @ShamanMask, '25563', 'Fire Resistance Totem'),
(@WorgenMask, @ShamanMask, '25567', 'Healing Stream Totem'),
(@WorgenMask, @ShamanMask, '25570', 'Mana Spring Totem'),
(@WorgenMask, @ShamanMask, '25574', 'Nature Resistance Totem'),
-- (@WorgenMask, @ShamanMask, '25577', 'Windwall Totem'), -- Removed?
-- (@WorgenMask, @ShamanMask, '25587', 'Windfury Totem'), -- Removed?
-- (@WorgenMask, @ShamanMask, '25908', 'Tranquil Air Totem'), -- Removed?
(@WorgenMask, @ShamanMask, '27763', 'Totem'),
(@WorgenMask, @ShamanMask, '33736', 'Water Shield'),
(@WorgenMask, @ShamanMask, '36936', 'Totemic Recall');
