INSERT IGNORE INTO `playercreateinfo_spell_custom` VALUES
-- Mag'har Orc Warrior
(@MagharOrc, @WarriorMask, '78', 'Heroic Strike'),
(@MagharOrc, @WarriorMask, '81', 'Dodge'),
(@MagharOrc, @WarriorMask, '107', 'Block'),
(@MagharOrc, @WarriorMask, '196', 'One-Handed Axes'),
(@MagharOrc, @WarriorMask, '197', 'Two-Handed Axes'),
(@MagharOrc, @WarriorMask, '201', 'One-Handed Swords'),
(@MagharOrc, @WarriorMask, '203', 'Unarmed'),
(@MagharOrc, @WarriorMask, '204', 'Defense'),
(@MagharOrc, @WarriorMask, '522', 'SPELLDEFENSE(DND)'),
(@MagharOrc, @WarriorMask, '669', 'Language Orcish'),
(@MagharOrc, @WarriorMask, '2382', 'Generic'),
(@MagharOrc, @WarriorMask, '2457', 'Battle Stance'),
(@MagharOrc, @WarriorMask, '2479', 'Honorless Target'),
(@MagharOrc, @WarriorMask, '3050', 'Detect'),
(@MagharOrc, @WarriorMask, '3365', 'Opening'),
(@MagharOrc, @WarriorMask, '5301', 'Defensive State(DND)'),
(@MagharOrc, @WarriorMask, '6233', 'Closing'),
(@MagharOrc, @WarriorMask, '6246', 'Closing'),
(@MagharOrc, @WarriorMask, '6247', 'Opening'),
(@MagharOrc, @WarriorMask, '6477', 'Opening'),
(@MagharOrc, @WarriorMask, '6478', 'Opening'),
(@MagharOrc, @WarriorMask, '6603', 'Attack'),
(@MagharOrc, @WarriorMask, '7266', 'Duel'),
(@MagharOrc, @WarriorMask, '7267', 'Grovel'),
(@MagharOrc, @WarriorMask, '7355', 'Stuck'),
(@MagharOrc, @WarriorMask, '7376', 'Defensive Stance Passive'),
(@MagharOrc, @WarriorMask, '7381', 'Berserker Stance Passive'),
(@MagharOrc, @WarriorMask, '8386', 'Attacking'),
(@MagharOrc, @WarriorMask, '8737', 'Mail'),
(@MagharOrc, @WarriorMask, '9077', 'Leather'),
(@MagharOrc, @WarriorMask, '9078', 'Cloth'),
(@MagharOrc, @WarriorMask, '9116', 'Shield'),
(@MagharOrc, @WarriorMask, '9125', 'Generic'),
(@MagharOrc, @WarriorMask, '110001', 'Ancestral Call'),
(@MagharOrc, @WarriorMask, '110002', 'Savage Blood'),
(@MagharOrc, @WarriorMask, '110004', 'Unwavering Will'),
(@MagharOrc, @WarriorMask, '21156', 'Battle Stance Passive'),
(@MagharOrc, @WarriorMask, '110003', 'Sympathetic Vigor'),
(@MagharOrc, @WarriorMask, '21651', 'Opening'),
(@MagharOrc, @WarriorMask, '21652', 'Closing'),
(@MagharOrc, @WarriorMask, '22027', 'Remove Insignia'),
(@MagharOrc, @WarriorMask, '22810', 'Opening - No Text'),
(@MagharOrc, @WarriorMask, '32215', 'Victorious State'),
(@MagharOrc, @WarriorMask, '2048', 'Battle Shout'),
(@MagharOrc, @WarriorMask, '30324', 'Heroic Strike'),
(@MagharOrc, @WarriorMask, '11578', 'Charge'),
(@MagharOrc, @WarriorMask, '25208', 'Rend'),
(@MagharOrc, @WarriorMask, '25264', 'Thunder Clap'),
(@MagharOrc, @WarriorMask, '2687', 'Bloodrage'),
(@MagharOrc, @WarriorMask, '71', 'Defensive Stance'),
(@MagharOrc, @WarriorMask, '25225', 'Sunder Armor'),
(@MagharOrc, @WarriorMask, '355', 'Taunt'),
(@MagharOrc, @WarriorMask, '11585', 'Overpower'),
(@MagharOrc, @WarriorMask, '29704', 'Shield Bash'),
(@MagharOrc, @WarriorMask, '25203', 'Demoralizing Shout'),
(@MagharOrc, @WarriorMask, '30357', 'Revenge'),
(@MagharOrc, @WarriorMask, '25266', 'Mocking Blow'),
(@MagharOrc, @WarriorMask, '2565', 'Shield Block'),
(@MagharOrc, @WarriorMask, '676', 'Disarm'),
(@MagharOrc, @WarriorMask, '25231', 'Cleave'),
(@MagharOrc, @WarriorMask, '20230', 'Retaliation'),
(@MagharOrc, @WarriorMask, '5246', 'Intimidating Shout'),
(@MagharOrc, @WarriorMask, '25236', 'Execute'),
(@MagharOrc, @WarriorMask, '1161', 'Challenging Shout'),
(@MagharOrc, @WarriorMask, '871', 'Shield Wall'),
(@MagharOrc, @WarriorMask, '2458', 'Berserker Stance'),
(@MagharOrc, @WarriorMask, '25275', 'Intercept'),
(@MagharOrc, @WarriorMask, '25242', 'Slam'),
(@MagharOrc, @WarriorMask, '18499', 'Berserker Rage'),
(@MagharOrc, @WarriorMask, '1680', 'Whirlwind'),
(@MagharOrc, @WarriorMask, '6554', 'Pummel'),
(@MagharOrc, @WarriorMask, '1719', 'Recklessness'),
(@MagharOrc, @WarriorMask, '34428', 'Victory Rush'),
(@MagharOrc, @WarriorMask, '23920', 'Spell Reflection'),
(@MagharOrc, @WarriorMask, '469', 'Commanding Shout'),
(@MagharOrc, @WarriorMask, '3411', 'Intervene'),
(@MagharOrc, @WarriorMask, '25212', 'Hamstring'),
(@MagharOrc, @WarriorMask, '674', 'Dual Wield'),
(@MagharOrc, @WarriorMask, '750', 'Plate Armor'),
(@MagharOrc, @WarriorMask, '12678', 'Stance Mastery'),
-- Mag'har Orc Paladin
(@MagharOrc, @PaladinMask, '81', 'Dodge'),
(@MagharOrc, @PaladinMask, '107', 'Block'),
(@MagharOrc, @PaladinMask, '198', 'One-Handed Maces'),
(@MagharOrc, @PaladinMask, '199', 'Two-Handed Maces'),
(@MagharOrc, @PaladinMask, '203', 'Unarmed'),
(@MagharOrc, @PaladinMask, '204', 'Defense'),
(@MagharOrc, @PaladinMask, '522', 'SPELLDEFENSE(DND)'),
(@MagharOrc, @PaladinMask, '635', 'Holy Light'),
(@MagharOrc, @PaladinMask, '669', 'Language Orcish'),
(@MagharOrc, @PaladinMask, '750', 'Plate Armor'),
-- (@MagharOrc, @PaladinMask, '1020', 'Divine Shield'), -- Removed?
(@MagharOrc, @PaladinMask, '1038', 'Hand of Salvation'),
(@MagharOrc, @PaladinMask, '1044', 'Hand of Freedom'),
(@MagharOrc, @PaladinMask, '2382', 'Generic'),
(@MagharOrc, @PaladinMask, '2479', 'Honorless Target'),
(@MagharOrc, @PaladinMask, '3050', 'Detect'),
(@MagharOrc, @PaladinMask, '3127', 'Parry'),
(@MagharOrc, @PaladinMask, '3365', 'Opening'),
(@MagharOrc, @PaladinMask, '4987', 'Cleanse'),
(@MagharOrc, @PaladinMask, '5502', 'Sense Undead'),
-- (@MagharOrc, @PaladinMask, '5627', 'Turn Undead'), -- Removed?
(@MagharOrc, @PaladinMask, '6233', 'Closing'),
(@MagharOrc, @PaladinMask, '6246', 'Closing'),
(@MagharOrc, @PaladinMask, '6247', 'Opening'),
(@MagharOrc, @PaladinMask, '6477', 'Opening'),
(@MagharOrc, @PaladinMask, '6478', 'Opening'),
(@MagharOrc, @PaladinMask, '6603', 'Attack'),
(@MagharOrc, @PaladinMask, '7266', 'Duel'),
(@MagharOrc, @PaladinMask, '7267', 'Grovel'),
(@MagharOrc, @PaladinMask, '7355', 'Stuck'),
(@MagharOrc, @PaladinMask, '8386', 'Attacking'),
(@MagharOrc, @PaladinMask, '8737', 'Mail'),
(@MagharOrc, @PaladinMask, '9077', 'Leather'),
(@MagharOrc, @PaladinMask, '9078', 'Cloth'),
(@MagharOrc, @PaladinMask, '9116', 'Shield'),
(@MagharOrc, @PaladinMask, '9125', 'Generic'),
(@MagharOrc, @PaladinMask, '10278', 'Hand of Protection'),
(@MagharOrc, @PaladinMask, '10308', 'Hammer of Justice'),
(@MagharOrc, @PaladinMask, '10326', 'Turn Evil'),
(@MagharOrc, @PaladinMask, '19746', 'Concentration Aura'),
(@MagharOrc, @PaladinMask, '19752', 'Divine Intervention'),
(@MagharOrc, @PaladinMask, '20271', 'Judgement of Light'),
(@MagharOrc, @PaladinMask, '110001', 'Ancestral Call'),
(@MagharOrc, @PaladinMask, '110002', 'Savage Blood'),
(@MagharOrc, @PaladinMask, '110004', 'Unwavering Will'),
(@MagharOrc, @PaladinMask, '110003', 'Sympathetic Vigor'),
(@MagharOrc, @PaladinMask, '20773', 'Redemption'),
(@MagharOrc, @PaladinMask, '21084', 'Seal of Righteousness'),
(@MagharOrc, @PaladinMask, '21651', 'Opening'),
(@MagharOrc, @PaladinMask, '21652', 'Closing'),
(@MagharOrc, @PaladinMask, '22027', 'Remove Insignia'),
(@MagharOrc, @PaladinMask, '22810', 'Opening - No Text'),
(@MagharOrc, @PaladinMask, '23214', 'Charger'),
(@MagharOrc, @PaladinMask, '25780', 'Righteous Fury'),
-- (@MagharOrc, @PaladinMask, '25895', 'Greater Blessing of Salvation'), -- Removed?
(@MagharOrc, @PaladinMask, '25898', 'Greater Blessing of Kings'),
(@MagharOrc, @PaladinMask, '27136', 'Holy Light'),
(@MagharOrc, @PaladinMask, '27137', 'Flash of Light'),
(@MagharOrc, @PaladinMask, '27138', 'Exorcism'),
(@MagharOrc, @PaladinMask, '27139', 'Holy Wrath'),
(@MagharOrc, @PaladinMask, '27140', 'Blessing of Might'),
(@MagharOrc, @PaladinMask, '27141', 'Greater Blessing of Might'),
(@MagharOrc, @PaladinMask, '27142', 'Blessing of Wisdom'),
(@MagharOrc, @PaladinMask, '27143', 'Greater Blessing of Wisdom'),
-- (@MagharOrc, @PaladinMask, '27144', 'Blessing of Light'), -- Removed?
-- (@MagharOrc, @PaladinMask, '27145', 'Greater Blessing of Light'), -- Removed?
-- (@MagharOrc, @PaladinMask, '27148', 'Blessing of Sacrifice'), -- Removed?
(@MagharOrc, @PaladinMask, '27149', 'Devotion Aura'),
(@MagharOrc, @PaladinMask, '27150', 'Retribution Aura'),
(@MagharOrc, @PaladinMask, '27151', 'Shadow Resistance Aura'),
(@MagharOrc, @PaladinMask, '27152', 'Frost Resistance Aura'),
(@MagharOrc, @PaladinMask, '27153', 'Fire Resistance Aura'),
(@MagharOrc, @PaladinMask, '27154', 'Lay on Hands'),
-- (@MagharOrc, @PaladinMask, '27155', 'Seal of Righteousness'), -- Removed?
-- (@MagharOrc, @PaladinMask, '27158', 'Seal of the Crusader'), -- Removed?
-- (@MagharOrc, @PaladinMask, '27160', 'Seal of Light'), -- Removed?
-- (@MagharOrc, @PaladinMask, '27166', 'Seal of Wisdom'), -- Removed?
-- (@MagharOrc, @PaladinMask, '27169', 'Greater Blessing of Sanctuary'), -- Removed?
(@MagharOrc, @PaladinMask, '27173', 'Consecration'),
(@MagharOrc, @PaladinMask, '27180', 'Hammer of Wrath'),
(@MagharOrc, @PaladinMask, '27762', 'Libram'),
(@MagharOrc, @PaladinMask, '31789', 'Righteous Defense'),
(@MagharOrc, @PaladinMask, '31801', 'Seal of Vengeance'),
(@MagharOrc, @PaladinMask, '31884', 'Avenging Wrath'),
-- (@MagharOrc, @PaladinMask, '31895', 'Seal of Justice'), -- Removed?
(@MagharOrc, @PaladinMask, '32223', 'Crusader Aura'),
(@MagharOrc, @PaladinMask, '33776', 'Spiritual Attunement'),
-- Mag'har Orc Hunter
(@MagharOrc, @HunterMask, '75', 'Auto Shot'),
(@MagharOrc, @HunterMask, '81', 'Dodge'),
(@MagharOrc, @HunterMask, '196', 'One-Handed Axes'),
(@MagharOrc, @HunterMask, '203', 'Unarmed'),
(@MagharOrc, @HunterMask, '204', 'Defense'),
(@MagharOrc, @HunterMask, '264', 'Bows'),
(@MagharOrc, @HunterMask, '522', 'SPELLDEFENSE(DND)'),
(@MagharOrc, @HunterMask, '669', 'Language Orcish'),
(@MagharOrc, @HunterMask, '2382', 'Generic'),
(@MagharOrc, @HunterMask, '2479', 'Honorless Target'),
(@MagharOrc, @HunterMask, '2973', 'Raptor Strike'),
(@MagharOrc, @HunterMask, '3050', 'Detect'),
(@MagharOrc, @HunterMask, '3365', 'Opening'),
(@MagharOrc, @HunterMask, '6233', 'Closing'),
(@MagharOrc, @HunterMask, '6246', 'Closing'),
(@MagharOrc, @HunterMask, '6247', 'Opening'),
(@MagharOrc, @HunterMask, '6477', 'Opening'),
(@MagharOrc, @HunterMask, '6478', 'Opening'),
(@MagharOrc, @HunterMask, '6603', 'Attack'),
(@MagharOrc, @HunterMask, '7266', 'Duel'),
(@MagharOrc, @HunterMask, '7267', 'Grovel'),
(@MagharOrc, @HunterMask, '7355', 'Stuck'),
(@MagharOrc, @HunterMask, '8386', 'Attacking'),
(@MagharOrc, @HunterMask, '9077', 'Leather'),
(@MagharOrc, @HunterMask, '9078', 'Cloth'),
(@MagharOrc, @HunterMask, '9125', 'Generic'),
(@MagharOrc, @HunterMask, '13358', 'Defensive State(DND)'),
(@MagharOrc, @HunterMask, '110001', 'Ancestral Call'),
(@MagharOrc, @HunterMask, '110002', 'Savage Blood'),
(@MagharOrc, @HunterMask, '110004', 'Unwavering Will'),
(@MagharOrc, @HunterMask, '110003', 'Sympathetic Vigor'),
(@MagharOrc, @HunterMask, '21651', 'Opening'),
(@MagharOrc, @HunterMask, '21652', 'Closing'),
(@MagharOrc, @HunterMask, '22027', 'Remove Insignia'),
(@MagharOrc, @HunterMask, '22810', 'Opening - No Text'),
(@MagharOrc, @HunterMask, '24949', 'Defensive State 2(DND)'),
(@MagharOrc, @HunterMask, '34082', 'Advantaged State(DND)'),
(@MagharOrc, @HunterMask, '27014', 'Raptor Strike'),
(@MagharOrc, @HunterMask, '1494', 'Track Beasts'),
(@MagharOrc, @HunterMask, '13163', 'Aspect of the Monkey'),
(@MagharOrc, @HunterMask, '27016', 'Serpent Sting'),
(@MagharOrc, @HunterMask, '27019', 'Arcane Shot'),
(@MagharOrc, @HunterMask, '14325', 'Hunters Mark'),
(@MagharOrc, @HunterMask, '5116', 'Concussive Shot'),
(@MagharOrc, @HunterMask, '27044', 'Aspect of the Hawk'),
(@MagharOrc, @HunterMask, '883', 'Call Pet'),
(@MagharOrc, @HunterMask, '2641', 'Dismiss Pet'),
(@MagharOrc, @HunterMask, '6991', 'Feed Pet'),
(@MagharOrc, @HunterMask, '982', 'Revive Pet'),
(@MagharOrc, @HunterMask, '1515', 'Tame Beast'),
(@MagharOrc, @HunterMask, '19883', 'Track Humanoids'),
-- (@MagharOrc, @HunterMask, '27020', 'Distracting Shot'), -- Removed?
(@MagharOrc, @HunterMask, '27046', 'Mend Pet'),
(@MagharOrc, @HunterMask, '14268', 'Alliance Flag'), -- What?
(@MagharOrc, @HunterMask, '6197', 'Eagle Eye'),
(@MagharOrc, @HunterMask, '1002', 'Eyes of the Beast'),
(@MagharOrc, @HunterMask, '14327', 'Scare Beast'),
(@MagharOrc, @HunterMask, '27023', 'Immolation Trap'),
(@MagharOrc, @HunterMask, '36916', 'Mongoose Bite'),
(@MagharOrc, @HunterMask, '27021', 'Multi-Shot'),
(@MagharOrc, @HunterMask, '19884', 'Track Undead'),
(@MagharOrc, @HunterMask, '5118', 'Aspect of the Cheetah'),
-- (@MagharOrc, @HunterMask, '27015', 'Disengage'), -- Removed?
(@MagharOrc, @HunterMask, '14311', 'Freezing Trap'),
(@MagharOrc, @HunterMask, '3043', 'Scorpid Sting'),
(@MagharOrc, @HunterMask, '1462', 'Beast Lore'),
(@MagharOrc, @HunterMask, '19885', 'Track Hidden'),
(@MagharOrc, @HunterMask, '3045', 'Rapid Fire'),
(@MagharOrc, @HunterMask, '19880', 'Track Elementals'),
(@MagharOrc, @HunterMask, '13809', 'Frost Trap'),
(@MagharOrc, @HunterMask, '13161', 'Aspect of the Beast'),
(@MagharOrc, @HunterMask, '5384', 'Feign Death'),
(@MagharOrc, @HunterMask, '1543', 'Flare'),
(@MagharOrc, @HunterMask, '19878', 'Track Demons'),
(@MagharOrc, @HunterMask, '27025', 'Explosive Trap'),
-- (@MagharOrc, @HunterMask, '27018', 'Viper Sting'), -- Removed?
(@MagharOrc, @HunterMask, '13159', 'Aspect of the Pack'),
(@MagharOrc, @HunterMask, '19882', 'Track Giants'),
(@MagharOrc, @HunterMask, '27022', 'Volley'),
(@MagharOrc, @HunterMask, '27045', 'Aspect of the Wild'),
(@MagharOrc, @HunterMask, '19879', 'Track Dragonkin'),
(@MagharOrc, @HunterMask, '19801', 'Tranquilizing Shot'),
(@MagharOrc, @HunterMask, '34120', 'Steady Shot'),
(@MagharOrc, @HunterMask, '34074', 'Aspect of the Viper'),
(@MagharOrc, @HunterMask, '34026', 'Kill Command'),
(@MagharOrc, @HunterMask, '34600', 'Snake Trap'),
(@MagharOrc, @HunterMask, '34477', 'Misdirection'),
(@MagharOrc, @HunterMask, '674', 'Dual Wield'),
(@MagharOrc, @HunterMask, '8737', 'Mail'),
(@MagharOrc, @HunterMask, '5149', 'Beast Training'), -- Only 8?
(@MagharOrc, @HunterMask, '3127', 'Parry'),
-- Mag'har Orc Rogue
(@MagharOrc, @RogueMask, '81', 'Dodge'),
(@MagharOrc, @RogueMask, '203', 'Unarmed'),
(@MagharOrc, @RogueMask, '204', 'Defense'),
(@MagharOrc, @RogueMask, '522', 'SPELLDEFENSE(DND)'),
(@MagharOrc, @RogueMask, '669', 'Language Orcish'),
(@MagharOrc, @RogueMask, '1180', 'Daggers'),
(@MagharOrc, @RogueMask, '1752', 'Sinister Strike'),
(@MagharOrc, @RogueMask, '2098', 'Eviscerate'),
(@MagharOrc, @RogueMask, '2382', 'Generic'),
(@MagharOrc, @RogueMask, '2479', 'Honorless Target'),
(@MagharOrc, @RogueMask, '2567', 'Thrown'),
(@MagharOrc, @RogueMask, '2764', 'Throw'),
(@MagharOrc, @RogueMask, '3050', 'Detect'),
(@MagharOrc, @RogueMask, '3365', 'Opening'),
(@MagharOrc, @RogueMask, '6233', 'Closing'),
(@MagharOrc, @RogueMask, '6246', 'Closing'),
(@MagharOrc, @RogueMask, '6247', 'Opening'),
(@MagharOrc, @RogueMask, '6477', 'Opening'),
(@MagharOrc, @RogueMask, '6478', 'Opening'),
(@MagharOrc, @RogueMask, '6603', 'Attack'),
(@MagharOrc, @RogueMask, '7266', 'Duel'),
(@MagharOrc, @RogueMask, '7267', 'Grovel'),
(@MagharOrc, @RogueMask, '7355', 'Stuck'),
(@MagharOrc, @RogueMask, '8386', 'Attacking'),
(@MagharOrc, @RogueMask, '9077', 'Leather'),
(@MagharOrc, @RogueMask, '9078', 'Cloth'),
(@MagharOrc, @RogueMask, '9125', 'Generic'),
(@MagharOrc, @RogueMask, '16092', 'Defensive State(DND)'),
(@MagharOrc, @RogueMask, '110001', 'Ancestral Call'),
(@MagharOrc, @RogueMask, '110002', 'Savage Blood'),
(@MagharOrc, @RogueMask, '110004', 'Unwavering Will'),
(@MagharOrc, @RogueMask, '21184', 'Rogue Passive(DND)'),
(@MagharOrc, @RogueMask, '110003', 'Sympathetic Vigor'),
(@MagharOrc, @RogueMask, '21651', 'Opening'),
(@MagharOrc, @RogueMask, '21652', 'Closing'),
(@MagharOrc, @RogueMask, '22027', 'Remove Insignia'),
(@MagharOrc, @RogueMask, '22810', 'Opening - No Text'),
(@MagharOrc, @RogueMask, '26865', 'Eviscerate'),
(@MagharOrc, @RogueMask, '26862', 'Sinister Strike'),
(@MagharOrc, @RogueMask, '1787', 'Stealth'),
(@MagharOrc, @RogueMask, '26863', 'Backstab'),
(@MagharOrc, @RogueMask, '921', 'Pick Pocket'),
(@MagharOrc, @RogueMask, '38764', 'Gouge'),
(@MagharOrc, @RogueMask, '26669', 'Evasion'),
(@MagharOrc, @RogueMask, '11297', 'Sap'),
(@MagharOrc, @RogueMask, '6774', 'Slice and Dice'),
(@MagharOrc, @RogueMask, '11305', 'Sprint'),
(@MagharOrc, @RogueMask, '38768', 'Kick'),
(@MagharOrc, @RogueMask, '26866', 'Expose Armor'),
(@MagharOrc, @RogueMask, '26884', 'Garrote'),
(@MagharOrc, @RogueMask, '27448', 'Feint'),
(@MagharOrc, @RogueMask, '1804', 'Pick Lock'),
(@MagharOrc, @RogueMask, '27441', 'Ambush'),
(@MagharOrc, @RogueMask, '2842', 'Poisons'),
(@MagharOrc, @RogueMask, '1725', 'Distract'),
(@MagharOrc, @RogueMask, '26867', 'Rupture'),
(@MagharOrc, @RogueMask, '26889', 'Vanish'),
(@MagharOrc, @RogueMask, '1833', 'Cheap Shot'),
(@MagharOrc, @RogueMask, '1842', 'Disarm Trap'),
(@MagharOrc, @RogueMask, '408', 'Kidney Shot'),
(@MagharOrc, @RogueMask, '2094', 'Blind'),
(@MagharOrc, @RogueMask, '32684', 'Envenom'),
(@MagharOrc, @RogueMask, '26679', 'Deadly Throw'),
(@MagharOrc, @RogueMask, '31224', 'Cloak of Shadows'),
(@MagharOrc, @RogueMask, '5938', 'Shiv'),
(@MagharOrc, @RogueMask, '8643', 'Kidney Shot'),
(@MagharOrc, @RogueMask, '3127', 'Parry'),
(@MagharOrc, @RogueMask, '674', 'Dual Wield'),
(@MagharOrc, @RogueMask, '3776', 'Green Leather Bracers'),
-- (@MagharOrc, @RogueMask, '9186', null), -- Removed?
(@MagharOrc, @RogueMask, '21927', 'Natures Ally'),
(@MagharOrc, @RogueMask, '22054', 'QAEnchant Bracer +7 Intellect'),
-- (@MagharOrc, @RogueMask, '22055', null), -- Removed?
(@MagharOrc, @RogueMask, '2836', 'Detect Traps'),
(@MagharOrc, @RogueMask, '1860', 'Safe Fall'),
-- Mag'har Orc Priest
(@MagharOrc, @PriestMask, '669', 'Language Orcish'),
(@MagharOrc, @PriestMask, '110001', 'Ancestral Call'),
(@MagharOrc, @PriestMask, '110002', 'Savage Blood'),
(@MagharOrc, @PriestMask, '110004', 'Unwavering Will'),
(@MagharOrc, @PriestMask, '110003', 'Sympathetic Vigor'),
(@MagharOrc, @PriestMask, '81', 'Dodge'),
(@MagharOrc, @PriestMask, '198', 'One-Handed Maces'),
(@MagharOrc, @PriestMask, '203', 'Unarmed'),
(@MagharOrc, @PriestMask, '204', 'Defense'),
(@MagharOrc, @PriestMask, '522', 'SPELLDEFENSE(DND)'),
(@MagharOrc, @PriestMask, '585', 'Smite'),
(@MagharOrc, @PriestMask, '2050', 'Lesser Heal'),
(@MagharOrc, @PriestMask, '2382', 'Generic'),
(@MagharOrc, @PriestMask, '2479', 'Honorless Target'),
(@MagharOrc, @PriestMask, '3050', 'Detect'),
(@MagharOrc, @PriestMask, '3365', 'Opening'),
(@MagharOrc, @PriestMask, '5009', 'Wands'),
(@MagharOrc, @PriestMask, '5019', 'Shoot'),
(@MagharOrc, @PriestMask, '6233', 'Closing'),
(@MagharOrc, @PriestMask, '6246', 'Closing'),
(@MagharOrc, @PriestMask, '6247', 'Opening'),
(@MagharOrc, @PriestMask, '6477', 'Opening'),
(@MagharOrc, @PriestMask, '6478', 'Opening'),
(@MagharOrc, @PriestMask, '6603', 'Attack'),
(@MagharOrc, @PriestMask, '7266', 'Duel'),
(@MagharOrc, @PriestMask, '7267', 'Grovel'),
(@MagharOrc, @PriestMask, '7355', 'Stuck'),
(@MagharOrc, @PriestMask, '8386', 'Attacking'),
(@MagharOrc, @PriestMask, '9078', 'Cloth'),
(@MagharOrc, @PriestMask, '9125', 'Generic'),
(@MagharOrc, @PriestMask, '21651', 'Opening'),
(@MagharOrc, @PriestMask, '21652', 'Closing'),
(@MagharOrc, @PriestMask, '22027', 'Remove Insignia'),
(@MagharOrc, @PriestMask, '22810', 'Opening - No Text'),
(@MagharOrc, @PriestMask, '25389', 'Power Word: Fortitude'),
(@MagharOrc, @PriestMask, '25364', 'Smite'),
(@MagharOrc, @PriestMask, '25368', 'Shadow Word: Pain'),
(@MagharOrc, @PriestMask, '25218', 'Power Word: Shield'),
-- (@MagharOrc, @PriestMask, '25429', 'Fade'), -- Removed?
(@MagharOrc, @PriestMask, '25222', 'Renew'),
(@MagharOrc, @PriestMask, '25375', 'Mind Blast'),
(@MagharOrc, @PriestMask, '25435', 'Resurrection'),
(@MagharOrc, @PriestMask, '25431', 'Inner Fire'),
(@MagharOrc, @PriestMask, '528', 'Cure Disease'),
(@MagharOrc, @PriestMask, '10890', 'Psychic Scream'),
(@MagharOrc, @PriestMask, '988', 'Dispel Magic'),
(@MagharOrc, @PriestMask, '6346', 'Fear Ward'),
(@MagharOrc, @PriestMask, '25235', 'Flash Heal'),
(@MagharOrc, @PriestMask, '25384', 'Holy Fire'),
-- (@MagharOrc, @PriestMask, '25596', 'Mind Soothe'), -- Removed?
(@MagharOrc, @PriestMask, '10955', 'Shackle Undead'),
(@MagharOrc, @PriestMask, '10909', 'Mind Vision'),
-- (@MagharOrc, @PriestMask, '25380', 'Mana Burn'), -- Removed?
-- (@MagharOrc, @PriestMask, '10912', 'Mind Control'), -- Removed?
(@MagharOrc, @PriestMask, '25308', 'Prayer of Healing'),
(@MagharOrc, @PriestMask, '25433', 'Shadow Protection'),
(@MagharOrc, @PriestMask, '552', 'Abolish Disease'),
(@MagharOrc, @PriestMask, '1706', 'Levitate'),
(@MagharOrc, @PriestMask, '25213', 'Greater Heal'),
(@MagharOrc, @PriestMask, '25392', 'Prayer of Fortitude'),
(@MagharOrc, @PriestMask, '39374', 'Prayer of Shadow Protection'),
(@MagharOrc, @PriestMask, '32999', 'Prayer of Spirit'),
(@MagharOrc, @PriestMask, '32996', 'Shadow Word: Death'),
(@MagharOrc, @PriestMask, '32546', 'Binding Heal'),
(@MagharOrc, @PriestMask, '34433', 'Shadowfiend'),
(@MagharOrc, @PriestMask, '33076', 'Prayer of Mending'),
(@MagharOrc, @PriestMask, '32375', 'Mass Dispel'),
-- (@MagharOrc, @PriestMask, '25441', 'Feedback'), -- Removed?
(@MagharOrc, @PriestMask, '25312', 'Divine Spirit'),
(@MagharOrc, @PriestMask, '25437', 'Desperate Prayer'),
-- Mag'har Orc Shaman
(@MagharOrc, @ShamanMask, '81', 'Dodge'),
(@MagharOrc, @ShamanMask, '107', 'Block'),
(@MagharOrc, @ShamanMask, '198', 'One-Handed Maces'),
(@MagharOrc, @ShamanMask, '203', 'Unarmed'),
(@MagharOrc, @ShamanMask, '204', 'Defense'),
(@MagharOrc, @ShamanMask, '227', 'Staves'),
(@MagharOrc, @ShamanMask, '331', 'Healing Wave'),
(@MagharOrc, @ShamanMask, '403', 'Lightning Bolt'),
(@MagharOrc, @ShamanMask, '522', 'SPELLDEFENSE(DND)'),
(@MagharOrc, @ShamanMask, '669', 'Language Orcish'),
(@MagharOrc, @ShamanMask, '2382', 'Generic'),
(@MagharOrc, @ShamanMask, '2479', 'Honorless Target'),
(@MagharOrc, @ShamanMask, '3050', 'Detect'),
(@MagharOrc, @ShamanMask, '3365', 'Opening'),
(@MagharOrc, @ShamanMask, '6233', 'Closing'),
(@MagharOrc, @ShamanMask, '6246', 'Closing'),
(@MagharOrc, @ShamanMask, '6247', 'Opening'),
(@MagharOrc, @ShamanMask, '6477', 'Opening'),
(@MagharOrc, @ShamanMask, '6478', 'Opening'),
(@MagharOrc, @ShamanMask, '6603', 'Attack'),
(@MagharOrc, @ShamanMask, '7266', 'Duel'),
(@MagharOrc, @ShamanMask, '7267', 'Grovel'),
(@MagharOrc, @ShamanMask, '7355', 'Stuck'),
(@MagharOrc, @ShamanMask, '8386', 'Attacking'),
(@MagharOrc, @ShamanMask, '9077', 'Leather'),
(@MagharOrc, @ShamanMask, '9078', 'Cloth'),
(@MagharOrc, @ShamanMask, '9116', 'Shield'),
(@MagharOrc, @ShamanMask, '9125', 'Generic'),
(@MagharOrc, @ShamanMask, '110002', 'Savage Blood'),
(@MagharOrc, @ShamanMask, '110004', 'Unwavering Will'),
(@MagharOrc, @ShamanMask, '110003', 'Sympathetic Vigor'),
(@MagharOrc, @ShamanMask, '21651', 'Opening'),
(@MagharOrc, @ShamanMask, '21652', 'Closing'),
(@MagharOrc, @ShamanMask, '22027', 'Remove Insignia'),
(@MagharOrc, @ShamanMask, '22810', 'Opening - No Text'),
(@MagharOrc, @ShamanMask, '27763', 'Totem'),
(@MagharOrc, @ShamanMask, '33697', 'Blood Fury'),
(@MagharOrc, @ShamanMask, '25396', 'Healing Wave'),
(@MagharOrc, @ShamanMask, '25449', 'Lightning Bolt'),
-- (@MagharOrc, @ShamanMask, '25485', 'Rockbiter Weapon'), -- Removed?
(@MagharOrc, @ShamanMask, '25454', 'Earth Shock'),
(@MagharOrc, @ShamanMask, '25509', 'Stoneskin Totem'),
(@MagharOrc, @ShamanMask, '2484', 'Earthbind Totem'),
(@MagharOrc, @ShamanMask, '25472', 'Lightning Shield'),
(@MagharOrc, @ShamanMask, '25525', 'Stoneclaw Totem'),
(@MagharOrc, @ShamanMask, '25457', 'Flame Shock'),
(@MagharOrc, @ShamanMask, '25489', 'Flametongue Weapon'),
(@MagharOrc, @ShamanMask, '25533', 'Searing Totem'),
(@MagharOrc, @ShamanMask, '25528', 'Strength of Earth Totem'),
(@MagharOrc, @ShamanMask, '20777', 'Ancestral Spirit'),
(@MagharOrc, @ShamanMask, '25547', 'Fire Nova'),
(@MagharOrc, @ShamanMask, '8012', 'Purge'),
(@MagharOrc, @ShamanMask, '526', 'Cure Toxins'),
(@MagharOrc, @ShamanMask, '8143', 'Tremor Totem'),
(@MagharOrc, @ShamanMask, '25464', 'Frost Shock'),
(@MagharOrc, @ShamanMask, '25500', 'Frostbrand Weapon'),
(@MagharOrc, @ShamanMask, '2645', 'Ghost Wolf'),
(@MagharOrc, @ShamanMask, '25567', 'Healing Stream Totem'),
(@MagharOrc, @ShamanMask, '25420', 'Lesser Healing Wave'),
-- (@MagharOrc, @ShamanMask, '2870', 'Cure Disease'), -- Removed?
(@MagharOrc, @ShamanMask, '8166', 'Poison Cleansing Totem'),
(@MagharOrc, @ShamanMask, '131', 'Water Breathing'),
(@MagharOrc, @ShamanMask, '25560', 'Frost Resistance Totem'),
(@MagharOrc, @ShamanMask, '6196', 'Far Sight'),
(@MagharOrc, @ShamanMask, '25552', 'Magma Totem'),
(@MagharOrc, @ShamanMask, '25570', 'Mana Spring Totem'),
(@MagharOrc, @ShamanMask, '25563', 'Fire Resistance Totem'),
(@MagharOrc, @ShamanMask, '25557', 'Flametongue Totem'),
(@MagharOrc, @ShamanMask, '546', 'Water Walking'),
(@MagharOrc, @ShamanMask, '556', 'Astral Recall'),
(@MagharOrc, @ShamanMask, '8177', 'Grounding Totem'),
(@MagharOrc, @ShamanMask, '25574', 'Nature Resistance Totem'),
(@MagharOrc, @ShamanMask, '36936', 'Totemic Recall'),
(@MagharOrc, @ShamanMask, '25505', 'Windfury Weapon'),
(@MagharOrc, @ShamanMask, '421', 'Chain Lightning'),
-- (@MagharOrc, @ShamanMask, '25587', 'Windfury Totem'), -- Removed?
(@MagharOrc, @ShamanMask, '6495', 'Sentry Totem'),
-- (@MagharOrc, @ShamanMask, '25577', 'Windwall Totem'), -- Removed?
(@MagharOrc, @ShamanMask, '8170', 'Cleansing Totem'),
(@MagharOrc, @ShamanMask, '25423', 'Chain Heal'),
-- (@MagharOrc, @ShamanMask, '25359', 'Grace of Air Totem'), -- Removed?
-- (@MagharOrc, @ShamanMask, '25908', 'Tranquil Air Totem'), -- Removed?
(@MagharOrc, @ShamanMask, '33736', 'Water Shield'),
(@MagharOrc, @ShamanMask, '3738', 'Wrath of Air Totem'),
(@MagharOrc, @ShamanMask, '2062', 'Earth Elemental Totem'),
(@MagharOrc, @ShamanMask, '2894', 'Fire Elemental Totem'),
(@MagharOrc, @ShamanMask, '2825', 'Bloodlust'), -- Only 9?
(@MagharOrc, @ShamanMask, '25442', 'Chain Lightning'), -- Only 6?
(@MagharOrc, @ShamanMask, '8737', 'Mail'),
(@MagharOrc, @ShamanMask, '20608', 'Reincarnation'), -- Only 6?
-- Mag'har Orc Mage
(@MagharOrc, @MageMask, '669', 'Language Orcish'),
(@MagharOrc, @MageMask, '110001', 'Ancestral Call'),
(@MagharOrc, @MageMask, '110002', 'Savage Blood'),
(@MagharOrc, @MageMask, '110004', 'Unwavering Will'),
(@MagharOrc, @MageMask, '110003', 'Sympathetic Vigor'),
(@MagharOrc, @MageMask, '81', 'Dodge'),
(@MagharOrc, @MageMask, '133', 'Fireball'),
(@MagharOrc, @MageMask, '168', 'Frost Armor'),
(@MagharOrc, @MageMask, '203', 'Unarmed'),
(@MagharOrc, @MageMask, '204', 'Defense'),
(@MagharOrc, @MageMask, '227', 'Staves'),
(@MagharOrc, @MageMask, '522', 'SPELLDEFENSE(DND)'),
(@MagharOrc, @MageMask, '2382', 'Generic'),
(@MagharOrc, @MageMask, '2479', 'Honorless Target'),
(@MagharOrc, @MageMask, '3050', 'Detect'),
(@MagharOrc, @MageMask, '3365', 'Opening'),
(@MagharOrc, @MageMask, '5009', 'Wands'),
(@MagharOrc, @MageMask, '5019', 'Shoot'),
(@MagharOrc, @MageMask, '6233', 'Closing'),
(@MagharOrc, @MageMask, '6246', 'Closing'),
(@MagharOrc, @MageMask, '6247', 'Opening'),
(@MagharOrc, @MageMask, '6477', 'Opening'),
(@MagharOrc, @MageMask, '6478', 'Opening'),
(@MagharOrc, @MageMask, '6603', 'Attack'),
(@MagharOrc, @MageMask, '7266', 'Duel'),
(@MagharOrc, @MageMask, '7267', 'Grovel'),
(@MagharOrc, @MageMask, '7355', 'Stuck'),
(@MagharOrc, @MageMask, '8386', 'Attacking'),
(@MagharOrc, @MageMask, '9078', 'Cloth'),
(@MagharOrc, @MageMask, '9125', 'Generic'),
(@MagharOrc, @MageMask, '21651', 'Opening'),
(@MagharOrc, @MageMask, '21652', 'Closing'),
(@MagharOrc, @MageMask, '22027', 'Remove Insignia'),
(@MagharOrc, @MageMask, '22810', 'Opening - No Text'),
(@MagharOrc, @MageMask, '27126', 'Arcane Intellect'),
(@MagharOrc, @MageMask, '27070', 'Fireball'),
(@MagharOrc, @MageMask, '22018', null),
(@MagharOrc, @MageMask, '27072', 'Frostbolt'),
(@MagharOrc, @MageMask, '22019', null),
(@MagharOrc, @MageMask, '27079', 'Fire Blast'),
(@MagharOrc, @MageMask, '38704', 'Arcane Missiles'),
(@MagharOrc, @MageMask, '28272', 'Polymorph (Pig)'),
(@MagharOrc, @MageMask, '28271', 'Polymorph (Turtle)'),
(@MagharOrc, @MageMask, '12826', 'Polymorph (Sheep)'),
(@MagharOrc, @MageMask, '27088', 'Frost Nova'),
(@MagharOrc, @MageMask, '33944', 'Dampen Magic'),
(@MagharOrc, @MageMask, '130', 'Slow Fall'),
(@MagharOrc, @MageMask, '27082', 'Arcane Explosion'),
(@MagharOrc, @MageMask, '27086', 'Flamestrike'),
(@MagharOrc, @MageMask, '33946', 'Amplify Magic'),
(@MagharOrc, @MageMask, '475', 'Remove Curse'),
(@MagharOrc, @MageMask, '1953', 'Blink'),
(@MagharOrc, @MageMask, '27085', 'Blizzard'),
(@MagharOrc, @MageMask, '12051', 'Evocation'),
(@MagharOrc, @MageMask, '27128', 'Fire Ward'),
(@MagharOrc, @MageMask, '27131', 'Mana Shield'),
(@MagharOrc, @MageMask, '32796', 'Frost Ward'),
(@MagharOrc, @MageMask, '27074', 'Scorch'),
(@MagharOrc, @MageMask, '2139', 'Counterspell'),
(@MagharOrc, @MageMask, '27101', 'Conjure Mana Gem'),
(@MagharOrc, @MageMask, '27124', 'Ice Armor'),
(@MagharOrc, @MageMask, '45438', 'Ice Block'),
(@MagharOrc, @MageMask, '27125', 'Mage Armor'),
(@MagharOrc, @MageMask, '27127', 'Arcane Brilliance'),
(@MagharOrc, @MageMask, '30482', 'Molten Armor'),
(@MagharOrc, @MageMask, '30451', 'Arcane Blast'),
(@MagharOrc, @MageMask, '30455', 'Ice Lance'),
(@MagharOrc, @MageMask, '66', 'Invisibility'),
(@MagharOrc, @MageMask, '43987', 'Ritual of Refreshment'),
(@MagharOrc, @MageMask, '30449', 'Spellsteal'),
(@MagharOrc, @MageMask, '27087', 'Cone of Cold'),
-- Mag'har Orc Warlock
(@MagharOrc, @WarlockMask, '81', 'Dodge'),
(@MagharOrc, @WarlockMask, '203', 'Unarmed'),
(@MagharOrc, @WarlockMask, '204', 'Defense'),
(@MagharOrc, @WarlockMask, '522', 'SPELLDEFENSE(DND)'),
(@MagharOrc, @WarlockMask, '669', 'Language Orcish'),
(@MagharOrc, @WarlockMask, '686', 'Shadow Bolt'),
(@MagharOrc, @WarlockMask, '687', 'Demon Skin'),
(@MagharOrc, @WarlockMask, '1180', 'Daggers'),
(@MagharOrc, @WarlockMask, '2382', 'Generic'),
(@MagharOrc, @WarlockMask, '2479', 'Honorless Target'),
(@MagharOrc, @WarlockMask, '3050', 'Detect'),
(@MagharOrc, @WarlockMask, '3365', 'Opening'),
(@MagharOrc, @WarlockMask, '5009', 'Wands'),
(@MagharOrc, @WarlockMask, '5019', 'Shoot'),
(@MagharOrc, @WarlockMask, '6233', 'Closing'),
(@MagharOrc, @WarlockMask, '6246', 'Closing'),
(@MagharOrc, @WarlockMask, '6247', 'Opening'),
(@MagharOrc, @WarlockMask, '6477', 'Opening'),
(@MagharOrc, @WarlockMask, '6478', 'Opening'),
(@MagharOrc, @WarlockMask, '6603', 'Attack'),
(@MagharOrc, @WarlockMask, '7266', 'Duel'),
(@MagharOrc, @WarlockMask, '7267', 'Grovel'),
(@MagharOrc, @WarlockMask, '7355', 'Stuck'),
(@MagharOrc, @WarlockMask, '8386', 'Attacking'),
(@MagharOrc, @WarlockMask, '9078', 'Cloth'),
(@MagharOrc, @WarlockMask, '9125', 'Generic'),
(@MagharOrc, @WarlockMask, '110002', 'Savage Blood'),
(@MagharOrc, @WarlockMask, '110004', 'Unwavering Will'),
(@MagharOrc, @WarlockMask, '110003', 'Sympathetic Vigor'),
(@MagharOrc, @WarlockMask, '21651', 'Opening'),
(@MagharOrc, @WarlockMask, '21652', 'Closing'),
(@MagharOrc, @WarlockMask, '22027', 'Remove Insignia'),
(@MagharOrc, @WarlockMask, '22810', 'Opening - No Text'),
(@MagharOrc, @WarlockMask, '33702', 'Blood Fury'),
(@MagharOrc, @WarlockMask, '27215', 'Immolate'),
(@MagharOrc, @WarlockMask, '27209', 'Shadow Bolt'),
(@MagharOrc, @WarlockMask, '27216', 'Corruption'),
(@MagharOrc, @WarlockMask, '30909', 'Curse of Weakness'),
(@MagharOrc, @WarlockMask, '27222', 'Life Tap'),
(@MagharOrc, @WarlockMask, '27218', 'Curse of Agony'),
(@MagharOrc, @WarlockMask, '6215', 'Fear'),
(@MagharOrc, @WarlockMask, '27230', 'Create Healthstone'),
(@MagharOrc, @WarlockMask, '27217', 'Drain Soul'),
(@MagharOrc, @WarlockMask, '27259', 'Health Funnel'),
-- (@MagharOrc, @WarlockMask, '27226', 'Curse of Recklessness'), -- Removed?
(@MagharOrc, @WarlockMask, '27220', 'Drain Life'),
(@MagharOrc, @WarlockMask, '5697', 'Unending Breath'),
(@MagharOrc, @WarlockMask, '27238', 'Create Soulstone'),
(@MagharOrc, @WarlockMask, '30459', 'Searing Pain'),
(@MagharOrc, @WarlockMask, '27260', 'Demon Armor'),
(@MagharOrc, @WarlockMask, '27212', 'Rain of Fire'),
(@MagharOrc, @WarlockMask, '698', 'Ritual of Summoning'),
(@MagharOrc, @WarlockMask, '5500', 'Sense Demons'),
-- (@MagharOrc, @WarlockMask, '30908', 'Drain Mana'), -- Removed?
(@MagharOrc, @WarlockMask, '11719', 'Curse of Tongues'),
(@MagharOrc, @WarlockMask, '132', 'Detect Invisibility'),
(@MagharOrc, @WarlockMask, '18647', 'Banish'),
(@MagharOrc, @WarlockMask, '27213', 'Hellfire'),
(@MagharOrc, @WarlockMask, '11726', 'Subjugate Demon'),
(@MagharOrc, @WarlockMask, '27228', 'Curse of the Elements'),
(@MagharOrc, @WarlockMask, '28610', 'Shadow Ward'),
(@MagharOrc, @WarlockMask, '28172', 'Create Spellstone'),
(@MagharOrc, @WarlockMask, '27250', 'Create Firestone'),
(@MagharOrc, @WarlockMask, '17928', 'Howl of Terror'),
(@MagharOrc, @WarlockMask, '27223', 'Death Coil'),
-- (@MagharOrc, @WarlockMask, '27229', 'Curse of Shadow'), -- Removed?
(@MagharOrc, @WarlockMask, '30545', 'Soul Fire'),
(@MagharOrc, @WarlockMask, '30910', 'Curse of Doom'),
(@MagharOrc, @WarlockMask, '18540', 'Ritual of Doom'),
(@MagharOrc, @WarlockMask, '28189', 'Fel Armor'),
(@MagharOrc, @WarlockMask, '32231', 'Incinerate'),
(@MagharOrc, @WarlockMask, '29858', 'Soulshatter'),
(@MagharOrc, @WarlockMask, '29893', 'Ritual of Souls'),
(@MagharOrc, @WarlockMask, '27243', 'Seed of Corruption'),
(@MagharOrc, @WarlockMask, '23161', 'Dreadsteed'),
(@MagharOrc, @WarlockMask, '688', 'Summon Imp'),
(@MagharOrc, @WarlockMask, '697', 'Summon Voidwalker'),
(@MagharOrc, @WarlockMask, '712', 'Summon Succubus'),
(@MagharOrc, @WarlockMask, '691', 'Summon Felhunter'),
(@MagharOrc, @WarlockMask, '126', 'Eye of Kilrogg'),
-- Mag'har Orc Druid
(@MagharOrc, @DruidMask, '669', 'Language Orcish'),
(@MagharOrc, @DruidMask, '110001', 'Ancestral Call'),
(@MagharOrc, @DruidMask, '110002', 'Savage Blood'),
(@MagharOrc, @DruidMask, '110004', 'Unwavering Will'),
(@MagharOrc, @DruidMask, '110003', 'Sympathetic Vigor'),
(@MagharOrc, @DruidMask, '81', 'Dodge'),
(@MagharOrc, @DruidMask, '198', 'One-Handed Maces'),
(@MagharOrc, @DruidMask, '203', 'Unarmed'),
(@MagharOrc, @DruidMask, '204', 'Defense'),
(@MagharOrc, @DruidMask, '227', 'Staves'),
(@MagharOrc, @DruidMask, '522', 'SPELLDEFENSE(DND)'),
(@MagharOrc, @DruidMask, '1178', 'Bear Form(Passive)'),
(@MagharOrc, @DruidMask, '2382', 'Generic'),
(@MagharOrc, @DruidMask, '2479', 'Honorless Target'),
(@MagharOrc, @DruidMask, '3025', 'Cat Form(Passive)'),
(@MagharOrc, @DruidMask, '3050', 'Detect'),
(@MagharOrc, @DruidMask, '3365', 'Opening'),
(@MagharOrc, @DruidMask, '5176', 'Wrath'),
(@MagharOrc, @DruidMask, '5185', 'Healing Touch'),
(@MagharOrc, @DruidMask, '5419', 'Travel Form(Passive)'),
(@MagharOrc, @DruidMask, '5420', 'Tree of Life'),
(@MagharOrc, @DruidMask, '5421', 'Aquatic Form(Passive)'),
(@MagharOrc, @DruidMask, '6233', 'Closing'),
(@MagharOrc, @DruidMask, '6246', 'Closing'),
(@MagharOrc, @DruidMask, '6247', 'Opening'),
(@MagharOrc, @DruidMask, '6477', 'Opening'),
(@MagharOrc, @DruidMask, '6478', 'Opening'),
(@MagharOrc, @DruidMask, '6603', 'Attack'),
(@MagharOrc, @DruidMask, '7266', 'Duel'),
(@MagharOrc, @DruidMask, '7267', 'Grovel'),
(@MagharOrc, @DruidMask, '7355', 'Stuck'),
(@MagharOrc, @DruidMask, '8386', 'Attacking'),
(@MagharOrc, @DruidMask, '9077', 'Leather'),
(@MagharOrc, @DruidMask, '9078', 'Cloth'),
(@MagharOrc, @DruidMask, '9125', 'Generic'),
(@MagharOrc, @DruidMask, '9635', 'Dire Bear Form(Passive)'),
(@MagharOrc, @DruidMask, '21178', 'Bear Form(Passive2)'),
(@MagharOrc, @DruidMask, '21651', 'Opening'),
(@MagharOrc, @DruidMask, '21652', 'Closing'),
(@MagharOrc, @DruidMask, '22027', 'Remove Insignia'),
(@MagharOrc, @DruidMask, '22810', 'Opening - No Text'),
(@MagharOrc, @DruidMask, '24905', 'Moonkin Form(Passive)'),
(@MagharOrc, @DruidMask, '27764', 'Fetish'),
(@MagharOrc, @DruidMask, '33948', 'Flight Form(Passive)'),
(@MagharOrc, @DruidMask, '34123', 'Tree of Life(Passive)'),
(@MagharOrc, @DruidMask, '40121', 'Swift Flight Form(Passive)'),
(@MagharOrc, @DruidMask, '26979', 'Healing Touch'),
(@MagharOrc, @DruidMask, '26990', 'Mark of the Wild'),
(@MagharOrc, @DruidMask, '26985', 'Wrath'),
(@MagharOrc, @DruidMask, '26988', 'Moonfire'),
(@MagharOrc, @DruidMask, '26982', 'Rejuvenation'),
(@MagharOrc, @DruidMask, '26992', 'Thorns'),
(@MagharOrc, @DruidMask, '26989', 'Entangling Roots'),
(@MagharOrc, @DruidMask, '26998', 'Demoralizing Roar'),
(@MagharOrc, @DruidMask, '6795', 'Growl'),
(@MagharOrc, @DruidMask, '26996', 'Maul'),
(@MagharOrc, @DruidMask, '18960', 'Teleport: Moonglade'),
(@MagharOrc, @DruidMask, '9634', 'Dire Bear Form'),
(@MagharOrc, @DruidMask, '768', 'Cat Form'),
(@MagharOrc, @DruidMask, '783', 'Travel Form'),
(@MagharOrc, @DruidMask, '1066', 'Aquatic Form'),
(@MagharOrc, @DruidMask, '40120', 'Swift Flight Form'),
(@MagharOrc, @DruidMask, '5229', 'Enrage'),
(@MagharOrc, @DruidMask, '26980', 'Regrowth'),
(@MagharOrc, @DruidMask, '8983', 'Bash'),
(@MagharOrc, @DruidMask, '8946', 'Cure Poison'),
(@MagharOrc, @DruidMask, '26997', 'Swipe (Bear)'),
-- (@MagharOrc, @DruidMask, '26993', 'Faerie Fire'), -- Removed?
(@MagharOrc, @DruidMask, '18658', 'Hibernate'),
(@MagharOrc, @DruidMask, '27000', 'Claw'),
(@MagharOrc, @DruidMask, '9913', 'Prowl'),
(@MagharOrc, @DruidMask, '26994', 'Rebirth'),
(@MagharOrc, @DruidMask, '27008', 'Rip'),
(@MagharOrc, @DruidMask, '26986', 'Starfire'),
(@MagharOrc, @DruidMask, '27002', 'Shred'),
(@MagharOrc, @DruidMask, '26995', 'Soothe Animal'),
(@MagharOrc, @DruidMask, '27003', 'Rake'),
(@MagharOrc, @DruidMask, '2782', 'Remove Curse'),
(@MagharOrc, @DruidMask, '9846', 'Tigers Fury'),
(@MagharOrc, @DruidMask, '2893', 'Abolish Poison'),
(@MagharOrc, @DruidMask, '33357', 'Dash'),
(@MagharOrc, @DruidMask, '5209', 'Challenging Roar'),
(@MagharOrc, @DruidMask, '27004', 'Cower'),
(@MagharOrc, @DruidMask, '26983', 'Tranquility'),
(@MagharOrc, @DruidMask, '24248', 'Ferocious Bite'),
(@MagharOrc, @DruidMask, '27005', 'Ravage'),
(@MagharOrc, @DruidMask, '5225', 'Track Humanoids'),
-- (@MagharOrc, @DruidMask, '26999', 'Frenzied Regeneration'), -- Removed?
(@MagharOrc, @DruidMask, '27012', 'Hurricane'),
(@MagharOrc, @DruidMask, '27006', 'Pounce'),
(@MagharOrc, @DruidMask, '29166', 'Innervate'),
(@MagharOrc, @DruidMask, '22812', 'Bark Skin'),
(@MagharOrc, @DruidMask, '26991', 'Gift of the Wild'),
(@MagharOrc, @DruidMask, '22570', 'Maim'),
(@MagharOrc, @DruidMask, '33763', 'Lifebloom'),
(@MagharOrc, @DruidMask, '33745', 'Lacerate'),
(@MagharOrc, @DruidMask, '33786', 'Cyclone'),
(@MagharOrc, @DruidMask, '20719', 'Feline Grace');
