// Generated by tools/highmountain_appearance.py from the pinned Highmountain discovery.
#ifndef ESTERIA_HIGHMOUNTAIN_APPEARANCE_H
#define ESTERIA_HIGHMOUNTAIN_APPEARANCE_H

#include <array>
#include <cstdint>

namespace HighmountainAppearance
{
    struct Option
    {
        std::uint16_t field;
        std::uint16_t count;
        std::uint16_t factor;
    };

    struct Requirement
    {
        std::uint16_t option;
        std::uint16_t value;
        std::uint16_t required;
        std::uint32_t mask;
    };

    inline constexpr std::array<Option, 21> MaleOptions = {{
        {1, 5, 1}, // Face
        {0, 9, 1}, // Skin Color
        {2, 10, 1}, // Horn Style
        {2, 2, 90}, // Horn Markings
        {2, 9, 10}, // Beard
        {1, 9, 5}, // Hair
        {0, 26, 9}, // Eye Color
        {3, 4, 64}, // Body Paint
        {5, 3, 1}, // Body Paint Color
        {3, 8, 1}, // Foremane
        {1, 5, 45}, // Nose Piercing
        {5, 3, 3}, // Headdress
        {4, 4, 1}, // Horn Wraps
        {3, 8, 8}, // Horn Decoration
        {4, 4, 4}, // Tail Decoration
        {5, 3, 9}, // Tail
        {5, 1, 1}, // Jewelry Color
        {5, 3, 27}, // Feather
        {4, 4, 16}, // Horn Color
        {4, 4, 64}, // Eyesight
        {5, 3, 81}, // Eye Style
    }};

    inline constexpr std::array<char const*, 21> MaleLabels = {
        "Face",
        "Skin Color",
        "Horn Style",
        "Horn Markings",
        "Beard",
        "Hair",
        "Eye Color",
        "Body Paint",
        "Body Paint Color",
        "Foremane",
        "Nose Piercing",
        "Headdress",
        "Horn Wraps",
        "Horn Decoration",
        "Tail Decoration",
        "Tail",
        "Jewelry Color",
        "Feather",
        "Horn Color",
        "Eyesight",
        "Eye Style",
    };

    inline constexpr std::array<std::uint16_t, 6> MaleCapacities = {234, 225, 180, 256, 256, 243};

    inline constexpr std::array<Requirement, 13> MaleRequirements = {{
        {3, 1, 2, 511},
        {12, 1, 2, 465},
        {12, 2, 2, 465},
        {12, 3, 2, 4},
        {13, 1, 2, 465},
        {13, 1, 12, 6},
        {13, 2, 2, 2},
        {13, 3, 2, 4},
        {13, 4, 2, 8},
        {13, 5, 2, 465},
        {13, 5, 12, 6},
        {13, 6, 2, 32},
        {13, 7, 2, 256},
    }};

    inline constexpr std::array<Option, 23> FemaleOptions = {{
        {1, 4, 1}, // Face
        {0, 9, 1}, // Skin Color
        {2, 9, 1}, // Hair
        {0, 26, 9}, // Eye Color
        {2, 9, 9}, // Horn Style
        {5, 2, 3}, // Horn Markings
        {3, 7, 1}, // Foremane
        {3, 5, 7}, // Earrings
        {1, 4, 4}, // Body Paint
        {2, 3, 81}, // Body Paint Color
        {5, 2, 6}, // Feather
        {1, 4, 16}, // Hair Decoration
        {5, 1, 1}, // Jewelry Color
        {1, 4, 64}, // Nose Piercing
        {4, 3, 64}, // Headdress
        {5, 2, 12}, // Horn Wraps
        {5, 2, 24}, // Horn Decoration
        {4, 4, 1}, // Horn Color
        {5, 2, 48}, // Tail
        {3, 5, 35}, // Tail Decoration
        {4, 4, 4}, // Necklace
        {4, 4, 16}, // Eyesight
        {5, 3, 1}, // Eye Style
    }};

    inline constexpr std::array<char const*, 23> FemaleLabels = {
        "Face",
        "Skin Color",
        "Hair",
        "Eye Color",
        "Horn Style",
        "Horn Markings",
        "Foremane",
        "Earrings",
        "Body Paint",
        "Body Paint Color",
        "Feather",
        "Hair Decoration",
        "Jewelry Color",
        "Nose Piercing",
        "Headdress",
        "Horn Wraps",
        "Horn Decoration",
        "Horn Color",
        "Tail",
        "Tail Decoration",
        "Necklace",
        "Eyesight",
        "Eye Style",
    };

    inline constexpr std::array<std::uint16_t, 6> FemaleCapacities = {234, 256, 243, 175, 192, 96};

    inline constexpr std::array<Requirement, 3> FemaleRequirements = {{
        {5, 1, 4, 255},
        {15, 1, 4, 255},
        {16, 1, 4, 255},
    }};

    template<class Options, class Requirements>
    constexpr bool ValidateProfile(std::array<std::uint8_t, 6> const& fields, Options const& options,
        Requirements const& requirements, std::array<std::uint16_t, 6> const& capacities)
    {
        for (unsigned i = 0; i < fields.size(); ++i)
            if (fields[i] >= capacities[i])
                return false;
        auto choice = [&](unsigned index)
        {
            Option const& option = options[index];
            return (fields[option.field] / option.factor) % option.count;
        };
        for (Requirement const& requirement : requirements)
            if (choice(requirement.option) == requirement.value
                && !(requirement.mask & (1u << choice(requirement.required))))
                return false;
        return true;
    }

    constexpr bool Validate(unsigned gender, std::array<std::uint8_t, 6> const& fields)
    {
        if (gender == 0)
            return ValidateProfile(fields, MaleOptions, MaleRequirements, MaleCapacities);
        if (gender == 1)
            return ValidateProfile(fields, FemaleOptions, FemaleRequirements, FemaleCapacities);
        return false;
    }
}

#endif
