// Generated by tools/vulpera_race_pack.py from the pinned Vulpera discovery.
#ifndef ESTERIA_VULPERA_APPEARANCE_H
#define ESTERIA_VULPERA_APPEARANCE_H

#include <array>
#include <cstdint>

namespace VulperaAppearance
{
    struct Option
    {
        std::uint16_t field;
        std::uint16_t count;
        std::uint16_t factor;
    };

    struct Requirement
    {
        std::uint16_t option;
        std::uint16_t value;
        std::uint16_t required;
        std::uint64_t mask;
    };

    inline constexpr std::array<Option, 10> MaleOptions = {{
        {1, 6, 1}, // Face
        {0, 8, 1}, // Fur Color
        {4, 1, 1}, // Hair Style
        {2, 6, 1}, // Ears
        {1, 6, 6}, // Snout
        {3, 33, 1}, // Eye Color
        {3, 2, 33}, // Earrings
        {0, 3, 8}, // Pattern
        {2, 4, 6}, // Eyesight
        {4, 3, 1}, // Eye Style
    }};

    inline constexpr std::array<char const*, 10> MaleLabels = {
        "Face",
        "Fur Color",
        "Hair Style",
        "Ears",
        "Snout",
        "Eye Color",
        "Earrings",
        "Pattern",
        "Eyesight",
        "Eye Style",
    };

    inline constexpr std::array<std::uint16_t, 5> MaleCapacities = {24, 36, 24, 66, 3};

    inline constexpr std::array<Requirement, 2> MaleRequirements = {{
        {9, 1, 5, 536838144},
        {9, 2, 5, 536838144},
    }};

    inline constexpr std::array<Option, 10> FemaleOptions = {{
        {1, 6, 1}, // Face
        {0, 8, 1}, // Fur Color
        {4, 1, 1}, // Hair Style
        {2, 8, 1}, // Ears
        {0, 3, 8}, // Pattern
        {1, 6, 6}, // Snout
        {3, 33, 1}, // Eye Color
        {3, 2, 33}, // Earrings
        {2, 4, 8}, // Eyesight
        {4, 3, 1}, // Eye Style
    }};

    inline constexpr std::array<char const*, 10> FemaleLabels = {
        "Face",
        "Fur Color",
        "Hair Style",
        "Ears",
        "Pattern",
        "Snout",
        "Eye Color",
        "Earrings",
        "Eyesight",
        "Eye Style",
    };

    inline constexpr std::array<std::uint16_t, 5> FemaleCapacities = {24, 36, 32, 66, 3};

    inline constexpr std::array<Requirement, 2> FemaleRequirements = {{
        {9, 1, 6, 536838144},
        {9, 2, 6, 536838144},
    }};

    template<class Options, class Requirements>
    constexpr bool ValidateProfile(std::array<std::uint8_t, 5> const& fields, Options const& options,
        Requirements const& requirements, std::array<std::uint16_t, 5> const& capacities)
    {
        for (unsigned i = 0; i < fields.size(); ++i)
            if (fields[i] >= capacities[i])
                return false;
        auto choice = [&](unsigned index)
        {
            Option const& option = options[index];
            return (fields[option.field] / option.factor) % option.count;
        };
        for (Requirement const& requirement : requirements)
            if (choice(requirement.option) == requirement.value
                && !(requirement.mask & (std::uint64_t{1} << choice(requirement.required))))
                return false;
        return true;
    }

    constexpr bool Validate(unsigned gender, std::array<std::uint8_t, 5> const& fields)
    {
        if (gender == 0)
            return ValidateProfile(fields, MaleOptions, MaleRequirements, MaleCapacities);
        if (gender == 1)
            return ValidateProfile(fields, FemaleOptions, FemaleRequirements, FemaleCapacities);
        return false;
    }
    struct ClassRequirement
    {
        std::uint16_t option;
        std::uint16_t value;
        std::uint32_t mask;
    };

    inline constexpr std::array<ClassRequirement, 72> MaleClasses = {{
        {0, 0, 4294967295u},
        {0, 1, 4294967295u},
        {0, 2, 4294967295u},
        {0, 3, 4294967295u},
        {0, 4, 4294967295u},
        {0, 5, 4294967295u},
        {1, 0, 4294967295u},
        {1, 1, 4294967295u},
        {1, 2, 4294967295u},
        {1, 3, 4294967295u},
        {1, 4, 4294967295u},
        {1, 5, 4294967295u},
        {1, 6, 4294967295u},
        {1, 7, 4294967295u},
        {2, 0, 4294967295u},
        {3, 0, 4294967295u},
        {3, 1, 4294967295u},
        {3, 2, 4294967295u},
        {3, 3, 4294967295u},
        {3, 4, 4294967295u},
        {3, 5, 4294967295u},
        {4, 0, 4294967295u},
        {4, 1, 4294967295u},
        {4, 2, 4294967295u},
        {4, 3, 4294967295u},
        {4, 4, 4294967295u},
        {4, 5, 4294967295u},
        {5, 0, 32735u},
        {5, 1, 32735u},
        {5, 2, 32735u},
        {5, 3, 32735u},
        {5, 4, 32735u},
        {5, 5, 32735u},
        {5, 6, 32735u},
        {5, 7, 32735u},
        {5, 8, 32735u},
        {5, 9, 32735u},
        {5, 10, 32735u},
        {5, 11, 32735u},
        {5, 12, 32735u},
        {5, 13, 32735u},
        {5, 14, 32u},
        {5, 15, 4294967295u},
        {5, 16, 4294967295u},
        {5, 17, 4294967295u},
        {5, 18, 4294967295u},
        {5, 19, 4294967295u},
        {5, 20, 4294967295u},
        {5, 21, 4294967295u},
        {5, 22, 4294967295u},
        {5, 23, 4294967295u},
        {5, 24, 4294967295u},
        {5, 25, 4294967295u},
        {5, 26, 4294967295u},
        {5, 27, 4294967295u},
        {5, 28, 4294967295u},
        {5, 29, 4294967295u},
        {5, 30, 4294967295u},
        {5, 31, 4294967295u},
        {5, 32, 4294967295u},
        {6, 0, 4294967295u},
        {6, 1, 4294967295u},
        {7, 0, 4294967295u},
        {7, 1, 4294967295u},
        {7, 2, 4294967295u},
        {8, 0, 4294967295u},
        {8, 1, 30687u},
        {8, 2, 30687u},
        {8, 3, 30687u},
        {9, 0, 4294967295u},
        {9, 1, 4294967295u},
        {9, 2, 4294967295u},
    }};

    inline constexpr std::array<ClassRequirement, 74> FemaleClasses = {{
        {0, 0, 4294967295u},
        {0, 1, 4294967295u},
        {0, 2, 4294967295u},
        {0, 3, 4294967295u},
        {0, 4, 4294967295u},
        {0, 5, 4294967295u},
        {1, 0, 4294967295u},
        {1, 1, 4294967295u},
        {1, 2, 4294967295u},
        {1, 3, 4294967295u},
        {1, 4, 4294967295u},
        {1, 5, 4294967295u},
        {1, 6, 4294967295u},
        {1, 7, 4294967295u},
        {2, 0, 4294967295u},
        {3, 0, 4294967295u},
        {3, 1, 4294967295u},
        {3, 2, 4294967295u},
        {3, 3, 4294967295u},
        {3, 4, 4294967295u},
        {3, 5, 4294967295u},
        {3, 6, 4294967295u},
        {3, 7, 4294967295u},
        {4, 0, 4294967295u},
        {4, 1, 4294967295u},
        {4, 2, 4294967295u},
        {5, 0, 4294967295u},
        {5, 1, 4294967295u},
        {5, 2, 4294967295u},
        {5, 3, 4294967295u},
        {5, 4, 4294967295u},
        {5, 5, 4294967295u},
        {6, 0, 32735u},
        {6, 1, 32735u},
        {6, 2, 32735u},
        {6, 3, 32735u},
        {6, 4, 32735u},
        {6, 5, 32735u},
        {6, 6, 32735u},
        {6, 7, 32735u},
        {6, 8, 32735u},
        {6, 9, 32735u},
        {6, 10, 32735u},
        {6, 11, 32735u},
        {6, 12, 32735u},
        {6, 13, 32735u},
        {6, 14, 32u},
        {6, 15, 4294967295u},
        {6, 16, 4294967295u},
        {6, 17, 4294967295u},
        {6, 18, 4294967295u},
        {6, 19, 4294967295u},
        {6, 20, 4294967295u},
        {6, 21, 4294967295u},
        {6, 22, 4294967295u},
        {6, 23, 4294967295u},
        {6, 24, 4294967295u},
        {6, 25, 4294967295u},
        {6, 26, 4294967295u},
        {6, 27, 4294967295u},
        {6, 28, 4294967295u},
        {6, 29, 4294967295u},
        {6, 30, 4294967295u},
        {6, 31, 4294967295u},
        {6, 32, 4294967295u},
        {7, 0, 4294967295u},
        {7, 1, 4294967295u},
        {8, 0, 4294967295u},
        {8, 1, 30687u},
        {8, 2, 30687u},
        {8, 3, 30687u},
        {9, 0, 4294967295u},
        {9, 1, 4294967295u},
        {9, 2, 4294967295u},
    }};

    constexpr std::array<std::uint8_t, 5> Fields(std::uint8_t skin, std::uint8_t face,
        std::uint8_t hairStyle, std::uint8_t hairColor, std::uint8_t facialStyle)
    {
        return {skin, face, hairStyle, hairColor, facialStyle};
    }

    constexpr bool ChoiceAllowed(unsigned gender, unsigned classId, unsigned option, unsigned value)
    {
        if (gender > 1 || classId < 1 || classId > 32)
            return false;
        auto allowed = [&](auto const& rows)
        {
            for (ClassRequirement const& row : rows)
                if (row.option == option && row.value == value)
                    return (row.mask & (1u << (classId - 1))) != 0;
            return false;
        };
        return gender ? allowed(FemaleClasses) : allowed(MaleClasses);
    }

    constexpr bool ValidateClass(unsigned gender, unsigned classId, std::array<std::uint8_t, 5> const& fields)
    {
        if (!Validate(gender, fields))
            return false;
        auto const& options = gender ? FemaleOptions : MaleOptions;
        for (unsigned i = 0; i < options.size(); ++i)
            if (!ChoiceAllowed(gender, classId, i, (fields[options[i].field] / options[i].factor) % options[i].count))
                return false;
        return true;
    }

    constexpr std::array<std::uint8_t, 5> Normalize(unsigned gender, unsigned classId,
        std::array<std::uint8_t, 5> fields)
    {
        if (gender > 1)
            return {};
        auto const& options = gender ? FemaleOptions : MaleOptions;
        auto const& capacities = gender ? FemaleCapacities : MaleCapacities;
        for (unsigned field = 0; field < fields.size(); ++field)
            if (fields[field] >= capacities[field])
                fields[field] = 0;
        for (unsigned i = 0; i < options.size(); ++i)
        {
            auto const& option = options[i];
            unsigned value = (fields[option.field] / option.factor) % option.count;
            if (ChoiceAllowed(gender, classId, i, value))
                continue;
            for (unsigned replacement = 0; replacement < option.count; ++replacement)
                if (ChoiceAllowed(gender, classId, i, replacement))
                {
                    fields[option.field] = static_cast<std::uint8_t>(fields[option.field]
                        - value * option.factor + replacement * option.factor);
                    break;
                }
        }
        auto const& requirements = gender ? FemaleRequirements : MaleRequirements;
        for (auto const& rule : requirements)
        {
            auto const& option = options[rule.option];
            auto const& required = options[rule.required];
            unsigned value = (fields[option.field] / option.factor) % option.count;
            unsigned prerequisite = (fields[required.field] / required.factor) % required.count;
            if (value == rule.value && !(rule.mask & (std::uint64_t{1} << prerequisite)))
                fields[option.field] = static_cast<std::uint8_t>(fields[option.field] - value * option.factor);
        }
        return fields;
    }
}

#endif
