-- charsections: 80 inserts, 0 updates, 0 deletes

-- New entries
DELETE FROM `charsections` WHERE `id` = 30426;
INSERT INTO `charsections` (`id`, `race`, `gender`, `base_section`, `texture_1`, `texture_2`, `texture_3`, `flags`, `type`, `color_index`) VALUES (30426, @Sethrak, @Male, @Skin, 'Character\\Sethrak\\Male\\sethrak_black.blp', '', '', 17, 0, 0);
DELETE FROM `charsections` WHERE `id` = 30427;
INSERT INTO `charsections` (`id`, `race`, `gender`, `base_section`, `texture_1`, `texture_2`, `texture_3`, `flags`, `type`, `color_index`) VALUES (30427, @Sethrak, @Male, @Face, '', '', '', 1, 0, 0);
DELETE FROM `charsections` WHERE `id` = 30428;
INSERT INTO `charsections` (`id`, `race`, `gender`, `base_section`, `texture_1`, `texture_2`, `texture_3`, `flags`, `type`, `color_index`) VALUES (30428, @Sethrak, @Male, @Skin, 'Character\\Sethrak\\Male\\sethrak_black.blp', '', '', 17, 0, 1);
DELETE FROM `charsections` WHERE `id` = 30429;
INSERT INTO `charsections` (`id`, `race`, `gender`, `base_section`, `texture_1`, `texture_2`, `texture_3`, `flags`, `type`, `color_index`) VALUES (30429, @Sethrak, @Male, @Face, '', '', '', 1, 0, 1);
DELETE FROM `charsections` WHERE `id` = 30430;
INSERT INTO `charsections` (`id`, `race`, `gender`, `base_section`, `texture_1`, `texture_2`, `texture_3`, `flags`, `type`, `color_index`) VALUES (30430, @Sethrak, @Male, @Skin, 'Character\\Sethrak\\Male\\sethrak_black.blp', '', '', 17, 0, 2);
DELETE FROM `charsections` WHERE `id` = 30431;
INSERT INTO `charsections` (`id`, `race`, `gender`, `base_section`, `texture_1`, `texture_2`, `texture_3`, `flags`, `type`, `color_index`) VALUES (30431, @Sethrak, @Male, @Face, '', '', '', 1, 0, 2);
DELETE FROM `charsections` WHERE `id` = 30432;
INSERT INTO `charsections` (`id`, `race`, `gender`, `base_section`, `texture_1`, `texture_2`, `texture_3`, `flags`, `type`, `color_index`) VALUES (30432, @Sethrak, @Male, @Skin, 'Character\\Sethrak\\Male\\sethrak_black.blp', '', '', 17, 0, 3);
DELETE FROM `charsections` WHERE `id` = 30433;
INSERT INTO `charsections` (`id`, `race`, `gender`, `base_section`, `texture_1`, `texture_2`, `texture_3`, `flags`, `type`, `color_index`) VALUES (30433, @Sethrak, @Male, @Face, '', '', '', 1, 0, 3);
DELETE FROM `charsections` WHERE `id` = 30434;
INSERT INTO `charsections` (`id`, `race`, `gender`, `base_section`, `texture_1`, `texture_2`, `texture_3`, `flags`, `type`, `color_index`) VALUES (30434, @Sethrak, @Male, @Skin, 'Character\\Sethrak\\Male\\sethrak_black.blp', '', '', 17, 0, 4);
DELETE FROM `charsections` WHERE `id` = 30435;
INSERT INTO `charsections` (`id`, `race`, `gender`, `base_section`, `texture_1`, `texture_2`, `texture_3`, `flags`, `type`, `color_index`) VALUES (30435, @Sethrak, @Male, @Face, '', '', '', 1, 0, 4);
DELETE FROM `charsections` WHERE `id` = 30436;
INSERT INTO `charsections` (`id`, `race`, `gender`, `base_section`, `texture_1`, `texture_2`, `texture_3`, `flags`, `type`, `color_index`) VALUES (30436, @Sethrak, @Male, @Skin, 'Character\\Sethrak\\Male\\sethrak_black.blp', '', '', 17, 0, 5);
DELETE FROM `charsections` WHERE `id` = 30437;
INSERT INTO `charsections` (`id`, `race`, `gender`, `base_section`, `texture_1`, `texture_2`, `texture_3`, `flags`, `type`, `color_index`) VALUES (30437, @Sethrak, @Male, @Face, '', '', '', 1, 0, 5);
DELETE FROM `charsections` WHERE `id` = 30438;
INSERT INTO `charsections` (`id`, `race`, `gender`, `base_section`, `texture_1`, `texture_2`, `texture_3`, `flags`, `type`, `color_index`) VALUES (30438, @Sethrak, @Male, @FacialHair, '', '', '', 17, 0, 0);
DELETE FROM `charsections` WHERE `id` = 30439;
INSERT INTO `charsections` (`id`, `race`, `gender`, `base_section`, `texture_1`, `texture_2`, `texture_3`, `flags`, `type`, `color_index`) VALUES (30439, @Sethrak, @Male, @Hair, '', '', '', 17, 0, 0);
DELETE FROM `charsections` WHERE `id` = 30440;
INSERT INTO `charsections` (`id`, `race`, `gender`, `base_section`, `texture_1`, `texture_2`, `texture_3`, `flags`, `type`, `color_index`) VALUES (30440, @Sethrak, @Male, @Underwear, '', '', '', 17, 0, 0);
DELETE FROM `charsections` WHERE `id` = 30441;
INSERT INTO `charsections` (`id`, `race`, `gender`, `base_section`, `texture_1`, `texture_2`, `texture_3`, `flags`, `type`, `color_index`) VALUES (30441, @Sethrak, @Male, @Underwear, '', '', '', 17, 0, 1);
DELETE FROM `charsections` WHERE `id` = 30442;
INSERT INTO `charsections` (`id`, `race`, `gender`, `base_section`, `texture_1`, `texture_2`, `texture_3`, `flags`, `type`, `color_index`) VALUES (30442, @Sethrak, @Male, @Underwear, '', '', '', 17, 0, 2);
DELETE FROM `charsections` WHERE `id` = 30443;
INSERT INTO `charsections` (`id`, `race`, `gender`, `base_section`, `texture_1`, `texture_2`, `texture_3`, `flags`, `type`, `color_index`) VALUES (30443, @Sethrak, @Male, @Underwear, '', '', '', 17, 0, 3);
DELETE FROM `charsections` WHERE `id` = 30444;
INSERT INTO `charsections` (`id`, `race`, `gender`, `base_section`, `texture_1`, `texture_2`, `texture_3`, `flags`, `type`, `color_index`) VALUES (30444, @Sethrak, @Male, @Underwear, '', '', '', 17, 0, 4);
DELETE FROM `charsections` WHERE `id` = 30445;
INSERT INTO `charsections` (`id`, `race`, `gender`, `base_section`, `texture_1`, `texture_2`, `texture_3`, `flags`, `type`, `color_index`) VALUES (30445, @Sethrak, @Male, @Underwear, '', '', '', 17, 0, 5);
DELETE FROM `charsections` WHERE `id` = 30446;
INSERT INTO `charsections` (`id`, `race`, `gender`, `base_section`, `texture_1`, `texture_2`, `texture_3`, `flags`, `type`, `color_index`) VALUES (30446, @Sethrak, @Female, @Skin, 'Character\\Sethrak\\Female\\snakeloa_1_body_blue.blp', '', '', 17, 0, 0);
DELETE FROM `charsections` WHERE `id` = 30447;
INSERT INTO `charsections` (`id`, `race`, `gender`, `base_section`, `texture_1`, `texture_2`, `texture_3`, `flags`, `type`, `color_index`) VALUES (30447, @Sethrak, @Female, @Face, '', '', '', 1, 0, 0);
DELETE FROM `charsections` WHERE `id` = 30448;
INSERT INTO `charsections` (`id`, `race`, `gender`, `base_section`, `texture_1`, `texture_2`, `texture_3`, `flags`, `type`, `color_index`) VALUES (30448, @Sethrak, @Female, @Underwear, '', '', '', 17, 0, 0);
DELETE FROM `charsections` WHERE `id` = 30449;
INSERT INTO `charsections` (`id`, `race`, `gender`, `base_section`, `texture_1`, `texture_2`, `texture_3`, `flags`, `type`, `color_index`) VALUES (30449, @Sethrak, @Female, @Skin, 'Character\\Sethrak\\Female\\snakeloa_1_body_blue.blp', '', '', 17, 0, 1);
DELETE FROM `charsections` WHERE `id` = 30450;
INSERT INTO `charsections` (`id`, `race`, `gender`, `base_section`, `texture_1`, `texture_2`, `texture_3`, `flags`, `type`, `color_index`) VALUES (30450, @Sethrak, @Female, @Face, '', '', '', 1, 0, 1);
DELETE FROM `charsections` WHERE `id` = 30451;
INSERT INTO `charsections` (`id`, `race`, `gender`, `base_section`, `texture_1`, `texture_2`, `texture_3`, `flags`, `type`, `color_index`) VALUES (30451, @Sethrak, @Female, @Underwear, '', '', '', 17, 0, 1);
DELETE FROM `charsections` WHERE `id` = 30452;
INSERT INTO `charsections` (`id`, `race`, `gender`, `base_section`, `texture_1`, `texture_2`, `texture_3`, `flags`, `type`, `color_index`) VALUES (30452, @Sethrak, @Female, @Skin, 'Character\\Sethrak\\Female\\snakeloa_1_body_blue.blp', '', '', 17, 0, 2);
DELETE FROM `charsections` WHERE `id` = 30453;
INSERT INTO `charsections` (`id`, `race`, `gender`, `base_section`, `texture_1`, `texture_2`, `texture_3`, `flags`, `type`, `color_index`) VALUES (30453, @Sethrak, @Female, @Face, '', '', '', 1, 0, 2);
DELETE FROM `charsections` WHERE `id` = 30454;
INSERT INTO `charsections` (`id`, `race`, `gender`, `base_section`, `texture_1`, `texture_2`, `texture_3`, `flags`, `type`, `color_index`) VALUES (30454, @Sethrak, @Female, @Underwear, '', '', '', 17, 0, 2);
DELETE FROM `charsections` WHERE `id` = 30455;
INSERT INTO `charsections` (`id`, `race`, `gender`, `base_section`, `texture_1`, `texture_2`, `texture_3`, `flags`, `type`, `color_index`) VALUES (30455, @Sethrak, @Female, @Skin, 'Character\\Sethrak\\Female\\snakeloa_1_body_blue.blp', '', '', 17, 0, 3);
DELETE FROM `charsections` WHERE `id` = 30456;
INSERT INTO `charsections` (`id`, `race`, `gender`, `base_section`, `texture_1`, `texture_2`, `texture_3`, `flags`, `type`, `color_index`) VALUES (30456, @Sethrak, @Female, @Face, '', '', '', 1, 0, 3);
DELETE FROM `charsections` WHERE `id` = 30457;
INSERT INTO `charsections` (`id`, `race`, `gender`, `base_section`, `texture_1`, `texture_2`, `texture_3`, `flags`, `type`, `color_index`) VALUES (30457, @Sethrak, @Female, @Underwear, '', '', '', 17, 0, 3);
DELETE FROM `charsections` WHERE `id` = 30458;
INSERT INTO `charsections` (`id`, `race`, `gender`, `base_section`, `texture_1`, `texture_2`, `texture_3`, `flags`, `type`, `color_index`) VALUES (30458, @Sethrak, @Female, @Skin, 'Character\\Sethrak\\Female\\snakeloa_1_body_blue.blp', '', '', 17, 0, 4);
DELETE FROM `charsections` WHERE `id` = 30459;
INSERT INTO `charsections` (`id`, `race`, `gender`, `base_section`, `texture_1`, `texture_2`, `texture_3`, `flags`, `type`, `color_index`) VALUES (30459, @Sethrak, @Female, @Face, '', '', '', 1, 0, 4);
DELETE FROM `charsections` WHERE `id` = 30460;
INSERT INTO `charsections` (`id`, `race`, `gender`, `base_section`, `texture_1`, `texture_2`, `texture_3`, `flags`, `type`, `color_index`) VALUES (30460, @Sethrak, @Female, @Underwear, '', '', '', 17, 0, 4);
DELETE FROM `charsections` WHERE `id` = 30461;
INSERT INTO `charsections` (`id`, `race`, `gender`, `base_section`, `texture_1`, `texture_2`, `texture_3`, `flags`, `type`, `color_index`) VALUES (30461, @Sethrak, @Female, @Skin, 'Character\\Sethrak\\Female\\snakeloa_1_body_blue.blp', '', '', 17, 0, 5);
DELETE FROM `charsections` WHERE `id` = 30462;
INSERT INTO `charsections` (`id`, `race`, `gender`, `base_section`, `texture_1`, `texture_2`, `texture_3`, `flags`, `type`, `color_index`) VALUES (30462, @Sethrak, @Female, @Face, '', '', '', 1, 0, 5);
DELETE FROM `charsections` WHERE `id` = 30463;
INSERT INTO `charsections` (`id`, `race`, `gender`, `base_section`, `texture_1`, `texture_2`, `texture_3`, `flags`, `type`, `color_index`) VALUES (30463, @Sethrak, @Female, @Underwear, '', '', '', 17, 0, 5);
DELETE FROM `charsections` WHERE `id` = 30464;
INSERT INTO `charsections` (`id`, `race`, `gender`, `base_section`, `texture_1`, `texture_2`, `texture_3`, `flags`, `type`, `color_index`) VALUES (30464, @Sethrak, @Female, @FacialHair, '', '', '', 17, 0, 0);
DELETE FROM `charsections` WHERE `id` = 30465;
INSERT INTO `charsections` (`id`, `race`, `gender`, `base_section`, `texture_1`, `texture_2`, `texture_3`, `flags`, `type`, `color_index`) VALUES (30465, @Sethrak, @Female, @Hair, '', '', '', 17, 0, 0);
