-- Ogre (Horde, race 60) and Furbolg (Alliance, race 61) startup, stats, language, totems
-- and the two chrraces_dbc overlay rows. Generated by tools/ogre_furbolg_race_pack.py.
-- The client/server ChrRaces.dbc files are staged as a matched set with this revision.

-- Ogre (60), horde; generated by tools/ogre_furbolg_race_pack.py.

SET @RACE := 60;
SET @DONOR := 2;

DELETE FROM `playercreateinfo` WHERE `race` = @RACE;
INSERT INTO `playercreateinfo` (`race`, `class`, `map`, `zone`, `position_x`, `position_y`, `position_z`, `orientation`)
SELECT @RACE, `class`, `map`, `zone`, `position_x`, `position_y`, `position_z`, `orientation`
FROM `playercreateinfo` WHERE `race` = @DONOR;

DELETE FROM `player_race_stats` WHERE `Race` = @RACE;
INSERT INTO `player_race_stats` (`Race`, `Strength`, `Agility`, `Stamina`, `Intellect`, `Spirit`)
SELECT @RACE, `Strength`, `Agility`, `Stamina`, `Intellect`, `Spirit`
FROM `player_race_stats` WHERE `Race` = @DONOR;

DELETE FROM `playercreateinfo_item` WHERE `race` = @RACE;
INSERT INTO `playercreateinfo_item` (`race`, `class`, `itemid`, `amount`, `Note`)
SELECT @RACE, `class`, `itemid`, `amount`, `Note`
FROM `playercreateinfo_item` WHERE `race` = @DONOR;

DELETE FROM `playercreateinfo_action` WHERE `race` = @RACE;
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`)
SELECT @RACE, `class`, `button`, `action`, `type`
FROM `playercreateinfo_action` WHERE `race` = @DONOR;

DELETE FROM `player_totem_model` WHERE `RaceID` = @RACE;
INSERT INTO `player_totem_model` (`TotemID`, `RaceID`, `ModelID`)
SELECT `TotemID`, @RACE, `ModelID` FROM `player_totem_model` WHERE `RaceID` = 2;

DELETE FROM `custom_race_start_spell` WHERE `race` = @RACE;
INSERT INTO `custom_race_start_spell` (`race`, `classMask`, `spell`, `comment`) VALUES
(@RACE, 0, 669, 'Language Orcish');

DELETE FROM `custom_race_start_skill` WHERE `race` = @RACE;
INSERT INTO `custom_race_start_skill` (`race`, `classMask`, `skill`, `rank`, `comment`) VALUES
(@RACE, 0, 109, 0, 'Language Orcish');

-- Furbolg (61), alliance; generated by tools/ogre_furbolg_race_pack.py.

SET @RACE := 61;
SET @DONOR := 4;

DELETE FROM `playercreateinfo` WHERE `race` = @RACE;
INSERT INTO `playercreateinfo` (`race`, `class`, `map`, `zone`, `position_x`, `position_y`, `position_z`, `orientation`)
SELECT @RACE, `class`, `map`, `zone`, `position_x`, `position_y`, `position_z`, `orientation`
FROM `playercreateinfo` WHERE `race` = @DONOR;

DELETE FROM `player_race_stats` WHERE `Race` = @RACE;
INSERT INTO `player_race_stats` (`Race`, `Strength`, `Agility`, `Stamina`, `Intellect`, `Spirit`)
SELECT @RACE, `Strength`, `Agility`, `Stamina`, `Intellect`, `Spirit`
FROM `player_race_stats` WHERE `Race` = @DONOR;

DELETE FROM `playercreateinfo_item` WHERE `race` = @RACE;
INSERT INTO `playercreateinfo_item` (`race`, `class`, `itemid`, `amount`, `Note`)
SELECT @RACE, `class`, `itemid`, `amount`, `Note`
FROM `playercreateinfo_item` WHERE `race` = @DONOR;

DELETE FROM `playercreateinfo_action` WHERE `race` = @RACE;
INSERT INTO `playercreateinfo_action` (`race`, `class`, `button`, `action`, `type`)
SELECT @RACE, `class`, `button`, `action`, `type`
FROM `playercreateinfo_action` WHERE `race` = @DONOR;

DELETE FROM `player_totem_model` WHERE `RaceID` = @RACE;
INSERT INTO `player_totem_model` (`TotemID`, `RaceID`, `ModelID`)
SELECT `TotemID`, @RACE, `ModelID` FROM `player_totem_model` WHERE `RaceID` = 11;

DELETE FROM `custom_race_start_spell` WHERE `race` = @RACE;
INSERT INTO `custom_race_start_spell` (`race`, `classMask`, `spell`, `comment`) VALUES
(@RACE, 0, 668, 'Language Common');

DELETE FROM `custom_race_start_skill` WHERE `race` = @RACE;
INSERT INTO `custom_race_start_skill` (`race`, `classMask`, `skill`, `rank`, `comment`) VALUES
(@RACE, 0, 98, 0, 'Language Common');

DELETE FROM `chrraces_dbc` WHERE `ID` = 60;
INSERT INTO `chrraces_dbc` (`ID`, `Flags`, `FactionID`, `MaleDisplayId`, `FemaleDisplayId`, `ClientPrefix`,
    `BaseLanguage`, `ClientFilestring`, `Alliance`, `Name_Lang_enUS`)
VALUES (60, 14, 2, 60053, 60054, 'Og', 1,
    'OgreHorde', 1, 'Ogre');

DELETE FROM `chrraces_dbc` WHERE `ID` = 61;
INSERT INTO `chrraces_dbc` (`ID`, `Flags`, `FactionID`, `MaleDisplayId`, `FemaleDisplayId`, `ClientPrefix`,
    `BaseLanguage`, `ClientFilestring`, `Alliance`, `Name_Lang_enUS`)
VALUES (61, 14, 4, 60055, 60056, 'Fu', 7,
    'Furbolg', 0, 'Furbolg');
