-- chrraces: 0 inserts, 19 updates, 0 deletes

-- Changed values
UPDATE `chrraces` SET `name_neutral_kokr` = '인간', `name_neutral_frfr` = 'Humain', `name_neutral_dede` = 'Mensch', `name_neutral_zhcn` = '人类', `name_neutral_eses` = 'Humano', `name_neutral_esmx` = 'Humano', `name_neutral_ruru` = 'Человек', `name_female_frfr` = 'Humaine', `name_female_eses` = 'Humana', `name_female_esmx` = 'Humana', `name_male_frfr` = 'Humain', `name_male_dede` = 'Mensch', `name_male_eses` = 'Humano', `name_male_esmx` = 'Humano', `name_male_ruru` = 'Человек' WHERE `id` = 1;
UPDATE `chrraces` SET `name_neutral_kokr` = '오크', `name_neutral_frfr` = 'Orc', `name_neutral_dede` = 'Orc', `name_neutral_zhcn` = '兽人', `name_neutral_eses` = 'Orco', `name_neutral_esmx` = 'Orco', `name_neutral_ruru` = 'Орк', `name_female_frfr` = 'Orque', `name_female_eses` = 'Orco', `name_female_esmx` = 'Orco', `name_male_frfr` = 'Orc', `name_male_dede` = 'Orc', `name_male_eses` = 'Orco', `name_male_esmx` = 'Orco', `name_male_ruru` = 'Орк' WHERE `id` = 2;
UPDATE `chrraces` SET `name_neutral_kokr` = '드워프', `name_neutral_frfr` = 'Nain', `name_neutral_dede` = 'Zwerg', `name_neutral_zhcn` = '矮人', `name_neutral_eses` = 'Enano', `name_neutral_esmx` = 'Enano', `name_neutral_ruru` = 'Дворф', `name_female_frfr` = 'Naine', `name_female_eses` = 'Enana', `name_female_esmx` = 'Enana', `name_male_frfr` = 'Nain', `name_male_dede` = 'Zwerg', `name_male_eses` = 'Enano', `name_male_esmx` = 'Enano', `name_male_ruru` = 'Дворф' WHERE `id` = 3;
UPDATE `chrraces` SET `name_neutral_kokr` = '나이트 엘프', `name_neutral_frfr` = 'Elfe de la nuit', `name_neutral_dede` = 'Nachtelf', `name_neutral_zhcn` = '暗夜精灵', `name_neutral_eses` = 'Elfo de la noche', `name_neutral_esmx` = 'Elfo de la noche', `name_neutral_ruru` = 'Ночной эльф', `name_female_frfr` = 'Elfe de la nuit', `name_female_dede` = 'Nachtelfe', `name_female_eses` = 'Elfa de la noche', `name_female_esmx` = 'Elfa de la noche', `name_female_ruru` = 'Ночная эльфийка', `name_male_frfr` = 'Elfe de la nuit', `name_male_dede` = 'Nachtelf', `name_male_eses` = 'Elfo de la noche', `name_male_esmx` = 'Elfo de la noche', `name_male_ruru` = 'Ночной эльф' WHERE `id` = 4;
UPDATE `chrraces` SET `name_neutral_kokr` = '언데드', `name_neutral_frfr` = 'Mort-vivant', `name_neutral_dede` = 'Untoter', `name_neutral_zhcn` = '亡灵', `name_neutral_eses` = 'No-muerto', `name_neutral_esmx` = 'No-muerto', `name_neutral_ruru` = 'Нежить', `name_female_frfr` = 'Morte-vivante', `name_female_dede` = 'Untote', `name_female_eses` = 'No-muerta', `name_female_esmx` = 'No-muerta', `name_female_ruru` = 'Нежить', `name_male_frfr` = 'Mort-vivant', `name_male_dede` = 'Untoter', `name_male_eses` = 'No-muerto', `name_male_esmx` = 'No-muerto' WHERE `id` = 5;
UPDATE `chrraces` SET `name_neutral_kokr` = '타우렌', `name_neutral_frfr` = 'Tauren', `name_neutral_dede` = 'Tauren', `name_neutral_zhcn` = '牛头人', `name_neutral_eses` = 'Tauren', `name_neutral_esmx` = 'Tauren', `name_neutral_ruru` = 'Таурен', `name_female_frfr` = 'Taurène', `name_female_eses` = 'Tauren', `name_female_esmx` = 'Tauren', `name_male_frfr` = 'Tauren', `name_male_dede` = 'Tauren', `name_male_eses` = 'Tauren', `name_male_esmx` = 'Tauren', `name_male_ruru` = 'Таурен' WHERE `id` = 6;
UPDATE `chrraces` SET `name_neutral_kokr` = '노움', `name_neutral_frfr` = 'Gnome', `name_neutral_dede` = 'Gnom', `name_neutral_zhcn` = '侏儒', `name_neutral_eses` = 'Gnomo', `name_neutral_esmx` = 'Gnomo', `name_neutral_ruru` = 'Гном', `name_female_frfr` = 'Gnome', `name_female_eses` = 'Gnoma', `name_female_esmx` = 'Gnoma', `name_male_frfr` = 'Gnome', `name_male_dede` = 'Gnom', `name_male_eses` = 'Gnomo', `name_male_esmx` = 'Gnomo', `name_male_ruru` = 'Гном' WHERE `id` = 7;
UPDATE `chrraces` SET `name_neutral_kokr` = '트롤', `name_neutral_frfr` = 'Troll', `name_neutral_dede` = 'Troll', `name_neutral_zhcn` = '巨魔', `name_neutral_eses` = 'Trol', `name_neutral_esmx` = 'Trol', `name_neutral_ruru` = 'Тролль', `name_female_frfr` = 'Trollesse', `name_female_eses` = 'Trol', `name_female_esmx` = 'Trol', `name_male_frfr` = 'Troll', `name_male_dede` = 'Troll', `name_male_eses` = 'Trol', `name_male_esmx` = 'Trol', `name_male_ruru` = 'Тролль' WHERE `id` = 8;
-- UPDATE `chrraces` SET `flags` = 4, `faction_id` = 2, `exploration_sound_id` = 4141, `base_language` = 1, `cinematic_sequence_id` = 141, `alliance` = 1, `name_neutral_kokr` = '고블린', `name_neutral_frfr` = 'Gobelin', `name_neutral_dede` = 'Goblin', `name_neutral_zhcn` = '地精', `name_neutral_eses` = 'Goblin', `name_neutral_esmx` = 'Goblin', `name_neutral_ruru` = 'Гоблин', `name_female_frfr` = 'Gobeline', `name_female_eses` = 'Goblin', `name_female_esmx` = 'Goblin', `name_male_frfr` = 'Gobelin', `name_male_dede` = 'Goblin', `name_male_eses` = 'Goblin', `name_male_esmx` = 'Goblin', `name_male_ruru` = 'Гоблин', `facial_hair_customization_1` = 'PIERCINGS', `facial_hair_customization_2` = 'PIERCINGS' WHERE `id` = 9;
UPDATE `chrraces` SET `name_neutral_kokr` = '블러드 엘프', `name_neutral_frfr` = 'Elfe de sang', `name_neutral_dede` = 'Blutelf', `name_neutral_zhcn` = '血精灵', `name_neutral_eses` = 'Elfo de sangre', `name_neutral_esmx` = 'Elfo de sangre', `name_neutral_ruru` = 'Син\'Дорей', `name_female_frfr` = 'Elfe de sang', `name_female_dede` = 'Blutelfe', `name_female_eses` = 'Elfa de sangre', `name_female_esmx` = 'Elfa de sangre', `name_female_ruru` = 'Син\'Дорейка', `name_male_frfr` = 'Elfe de sang', `name_male_dede` = 'Blutelf', `name_male_eses` = 'Elfo de sangre', `name_male_esmx` = 'Elfo de sangre', `name_male_ruru` = 'Син\'Дорей' WHERE `id` = 10;
UPDATE `chrraces` SET `name_neutral_kokr` = '드레나이', `name_neutral_frfr` = 'Draeneï', `name_neutral_dede` = 'Draenei', `name_neutral_zhcn` = '德莱尼', `name_neutral_eses` = 'Draenei', `name_neutral_esmx` = 'Draenei', `name_neutral_ruru` = 'Дреней', `name_female_frfr` = 'Draeneï', `name_female_eses` = 'Draenei', `name_female_esmx` = 'Draenei', `name_male_frfr` = 'Draeneï', `name_male_dede` = 'Draenei', `name_male_eses` = 'Draenei', `name_male_esmx` = 'Draenei', `name_male_ruru` = 'Дреней' WHERE `id` = 11;
-- UPDATE `chrraces` SET `flags` = 6, `exploration_sound_id` = 4143, `male_display_id` = 29422, `female_display_id` = 29423, `client_prefix` = 'Wo', `client_filestring` = 'Worgen', `cinematic_sequence_id` = 61, `alliance` = 0, `name_neutral_enus` = 'Worgen', `name_neutral_kokr` = '늑대인간', `name_neutral_frfr` = 'Worgen', `name_neutral_dede` = 'Worgen', `name_neutral_zhcn` = '狼人', `name_neutral_eses` = 'Huargen', `name_neutral_esmx` = 'Huargen', `name_neutral_ruru` = 'Ворген', `name_female_frfr` = 'Worgen', `name_female_eses` = 'Huargen', `name_female_esmx` = 'Huargen', `name_male_frfr` = 'Worgen', `name_male_dede` = 'Worgen', `name_male_eses` = 'Huargen', `name_male_esmx` = 'Huargen', `name_male_ruru` = 'Ворген', `facial_hair_customization_1` = 'FEATURES', `facial_hair_customization_2` = 'EARS' WHERE `id` = 12;
UPDATE `chrraces` SET `name_neutral_kokr` = '나가', `name_neutral_frfr` = 'Naga', `name_neutral_dede` = 'Naga', `name_neutral_zhcn` = '纳迦', `name_neutral_eses` = 'Naga', `name_neutral_esmx` = 'Naga', `name_neutral_ruru` = 'Нага', `name_female_frfr` = 'Naga', `name_female_eses` = 'Naga', `name_female_esmx` = 'Naga', `name_female_ruru` = 'Нага', `name_male_frfr` = 'Naga', `name_male_dede` = 'Naga', `name_male_eses` = 'Naga', `name_male_esmx` = 'Naga', `name_male_ruru` = 'Наг' WHERE `id` = 13;
UPDATE `chrraces` SET `name_neutral_kokr` = '뒤틀린 드레나이', `name_neutral_frfr` = 'Roué', `name_neutral_dede` = 'Zerschlagener', `name_neutral_zhcn` = '破碎者', `name_neutral_eses` = 'Tábido', `name_neutral_esmx` = 'Tábido', `name_neutral_ruru` = 'Падший', `name_female_frfr` = 'Rouée', `name_female_eses` = 'Tábida', `name_female_esmx` = 'Tábida', `name_female_ruru` = 'Падшая', `name_male_frfr` = 'Roué', `name_male_dede` = 'Zerschlagener', `name_male_eses` = 'Tábido', `name_male_esmx` = 'Tábido', `name_male_ruru` = 'Падший' WHERE `id` = 14;
UPDATE `chrraces` SET `name_neutral_kokr` = '해골', `name_neutral_frfr` = 'Squelette', `name_neutral_dede` = 'Skelett', `name_neutral_zhcn` = '骷髅', `name_neutral_eses` = 'Esqueleto', `name_neutral_esmx` = 'Esqueleto', `name_neutral_ruru` = 'Скелет', `name_female_frfr` = 'Squelette', `name_female_eses` = 'Esqueleto', `name_female_esmx` = 'Esqueleto', `name_male_frfr` = 'Squelette', `name_male_dede` = 'Skelett', `name_male_eses` = 'Esqueleto', `name_male_esmx` = 'Esqueleto', `name_male_ruru` = 'Скелет' WHERE `id` = 15;
UPDATE `chrraces` SET `name_neutral_kokr` = '브리쿨', `name_neutral_frfr` = 'Vrykul', `name_neutral_dede` = 'Vrykul', `name_neutral_zhcn` = '维库人', `name_neutral_eses` = 'Vrykul', `name_neutral_esmx` = 'Vrykul', `name_neutral_ruru` = 'Врайкул', `name_female_frfr` = 'Vrykule', `name_female_eses` = 'Vrykul', `name_female_esmx` = 'Vrykul', `name_male_frfr` = 'Vrykul', `name_male_dede` = 'Vrykul', `name_male_eses` = 'Vrykul', `name_male_esmx` = 'Vrykul', `name_male_ruru` = 'Врайкул' WHERE `id` = 16;
UPDATE `chrraces` SET `name_neutral_kokr` = '투스카르', `name_neutral_frfr` = 'Rohart', `name_neutral_dede` = 'Tuskarr', `name_neutral_zhcn` = '海象人', `name_neutral_eses` = 'Colmillarr', `name_neutral_esmx` = 'Colmillarr', `name_neutral_ruru` = 'Клыкарр', `name_female_frfr` = 'Rohart', `name_female_eses` = 'Colmillarr', `name_female_esmx` = 'Colmillarr', `name_male_frfr` = 'Rohart', `name_male_dede` = 'Tuskarr', `name_male_eses` = 'Colmillarr', `name_male_esmx` = 'Colmillarr', `name_male_ruru` = 'Клыкарр' WHERE `id` = 17;
UPDATE `chrraces` SET `name_neutral_kokr` = '숲 트롤', `name_neutral_frfr` = 'Troll des forêts', `name_neutral_dede` = 'Waldtroll', `name_neutral_zhcn` = '森林巨魔', `name_neutral_eses` = 'Trol de bosque', `name_neutral_esmx` = 'Trol de bosque', `name_neutral_ruru` = 'Лесной тролль', `name_female_frfr` = 'Trollesse des forêts', `name_female_eses` = 'Trol de bosque', `name_female_esmx` = 'Trol de bosque', `name_male_frfr` = 'Troll des forêts', `name_male_dede` = 'Waldtroll', `name_male_eses` = 'Trol de bosque', `name_male_esmx` = 'Trol de bosque', `name_male_ruru` = 'Лесной тролль' WHERE `id` = 18;
UPDATE `chrraces` SET `name_neutral_kokr` = '타운카', `name_neutral_frfr` = 'Taunka', `name_neutral_dede` = 'Taunka', `name_neutral_zhcn` = '牦牛人', `name_neutral_eses` = 'Taunka', `name_neutral_esmx` = 'Taunka', `name_neutral_ruru` = 'Таунка', `name_female_frfr` = 'Taunka', `name_female_eses` = 'Taunka', `name_female_esmx` = 'Taunka', `name_female_ruru` = 'Таунка', `name_male_frfr` = 'Taunka', `name_male_dede` = 'Taunka', `name_male_eses` = 'Taunka', `name_male_esmx` = 'Taunka', `name_male_ruru` = 'Таунка' WHERE `id` = 19;
UPDATE `chrraces` SET `name_neutral_kokr` = '노스렌드 해골', `name_neutral_frfr` = 'Squelette du Norfendre', `name_neutral_dede` = 'Skelett aus Nordend', `name_neutral_zhcn` = '诺森德骷髅', `name_neutral_eses` = 'Esqueleto de Rasganorte', `name_neutral_esmx` = 'Esqueleto de Rasganorte', `name_neutral_ruru` = 'Нордскольский скелет', `name_female_frfr` = 'Squelette du Norfendre', `name_female_eses` = 'Esqueleto de Rasganorte', `name_female_esmx` = 'Esqueleto de Rasganorte', `name_male_frfr` = 'Squelette du Norfendre', `name_male_dede` = 'Skelett aus Nordend', `name_male_eses` = 'Esqueleto de Rasganorte', `name_male_esmx` = 'Esqueleto de Rasganorte', `name_male_ruru` = 'Нордскольский скелет' WHERE `id` = 20;
UPDATE `chrraces` SET `name_neutral_kokr` = '얼음 트롤', `name_neutral_frfr` = 'Troll des glaces', `name_neutral_dede` = 'Eistroll', `name_neutral_zhcn` = '冰巨魔', `name_neutral_eses` = 'Trol de hielo', `name_neutral_esmx` = 'Trol de hielo', `name_neutral_ruru` = 'Ледяной тролль', `name_female_frfr` = 'Trollesse des glaces', `name_female_eses` = 'Trol de hielo', `name_female_esmx` = 'Trol de hielo', `name_male_frfr` = 'Troll des glaces', `name_male_dede` = 'Eistroll', `name_male_eses` = 'Trol de hielo', `name_male_esmx` = 'Trol de hielo', `name_male_ruru` = 'Ледяной тролль' WHERE `id` = 21;
